export const BUSINESS_CONTENT: Record<string, Record<string, any>> = {
  'Business Strategy & Management': {
    'Strategic Analysis Frameworks': {
      understand: {
        theory: `# Strategic Analysis Frameworks\nStrategy frameworks help managers analyse environments, diagnose problems, and make consistent decisions. Three foundational tools: **SWOT**, **Porter's Five Forces**, and **PESTEL**.\n\n## SWOT Analysis\n| Internal | External |\n|---|---|\n| Strengths | Opportunities |\n| Weaknesses | Threats |\n\n## Porter's Five Forces\n1. **Competitive Rivalry** — number/intensity of competitors\n2. **Threat of New Entrants** — how easy to enter the market\n3. **Bargaining Power of Suppliers** — supplier concentration\n4. **Bargaining Power of Buyers** — buyer switching cost\n5. **Threat of Substitutes** — alternative products/services\n\n## PESTEL\nPolitical · Economic · Social · Technological · Environmental · Legal — macro-environment scan.\n\n## BCG Matrix (portfolio)\n- **Stars**: high growth, high share → invest\n- **Cash Cows**: low growth, high share → harvest\n- **Question Marks**: high growth, low share → invest or divest\n- **Dogs**: low growth, low share → divest`,
        examples: [{ title: 'SWOT for a Fintech Startup', language: 'text', code: `STRENGTHS:  No branch costs, mobile-first, fast onboarding\nWEAKNESSES: No brand trust, limited credit history data\nOPPORTUNITIES: 800M unbanked Indians, UPI growth\nTHREATS: RBI regulations, established banks launching apps\n\nStrategic Insight: Leverage UPI infrastructure (O) to\ncompensate for lack of brand trust (W) via referral programs.`, explanation: 'A good SWOT does not just list factors — it draws SO, WO, ST, WT strategy combinations from the quadrants.' }],
        keyPoints: ['SWOT is internal + external. PESTEL is macro-environment only. Five Forces is industry-level competition analysis', 'BCG Matrix classifies business units by market share and growth rate to guide investment decisions', 'Strategy frameworks are starting points — always validate insights with real data and stakeholder interviews']
      },
      evaluate: { questions: [{ question: 'Porter\'s Five Forces is used to analyse:', options: ['Internal company strengths', 'Industry profitability and competitive dynamics', 'Employee performance', 'Marketing effectiveness'], correctIndex: 1, explanation: 'Five Forces analyses the competitive structure of an industry to determine its attractiveness and where power lies.' }, { question: 'In BCG Matrix, a "Cash Cow" is:', options: ['High growth, high market share', 'Low growth, high market share — generates cash with low investment', 'High growth, low market share', 'Low growth, low market share'], correctIndex: 1, explanation: 'Cash Cows generate steady profit in mature markets. Funds from Cash Cows typically invest in Stars or Question Marks.' }, { question: 'The T in PESTEL stands for:', options: ['Trade', 'Technology', 'Taxation', 'Talent'], correctIndex: 1, explanation: 'PESTEL: Political, Economic, Social, Technological, Environmental, Legal.' }] }
    },
    'Competitive Advantage': {
      understand: {
        theory: `# Competitive Advantage\nA firm has competitive advantage when it consistently outperforms competitors in a sustainable way. Michael Porter identifies two generic strategies:\n\n## Cost Leadership\n- Be the lowest-cost producer in the industry\n- Examples: Walmart, Aldi, Xiaomi\n- Requires: scale, process efficiency, tight cost control\n\n## Differentiation\n- Offer unique value buyers will pay a premium for\n- Examples: Apple, BMW, Starbucks\n- Requires: brand, innovation, quality, customer experience\n\n## Focus (Niche)\n- Target a specific segment with cost or differentiation\n- Examples: Rolls-Royce (premium niche), BIC (low-cost niche)\n\n## Sustainable Competitive Advantage Sources\n1. **Economies of scale** — lower cost per unit at volume\n2. **Network effects** — value increases with users (WhatsApp, Uber)\n3. **Switching costs** — painful to leave (Salesforce, SAP)\n4. **Brand equity** — premium command, trust\n5. **Patents/IP** — legal protection of innovation\n6. **Data moats** — proprietary data that improves product`,
        examples: [{ title: 'Blue Ocean Strategy', language: 'text', code: `Cirque du Soleil created a Blue Ocean by:\n\nELIMINATED: Animal acts, Star performers, Aisle concessions\nREDUCED: Fun/thrill (circus), Danger/risk\nRAISED: Unique venue, Multiple productions\nCREATED: Theme, Refined env., Artistic music & dance\n\nResult: Created uncontested market space — combined\ncircus + theatre. Priced 5× traditional circus.`, explanation: 'Blue Ocean Strategy: instead of beating competitors in existing "red ocean" markets, create uncontested new space by changing the value factors.' }],
        keyPoints: ['Porter warns against being "stuck in the middle" — firms that are neither low-cost nor clearly differentiated underperform both', 'Network effects are the most powerful moat in digital businesses — winner-takes-most dynamics emerge', 'Competitive advantage erodes over time — firms must continually innovate to sustain it (dynamic capabilities)']
      },
      evaluate: { questions: [{ question: 'A company that is the industry\'s lowest-cost producer is pursuing:', options: ['Differentiation strategy', 'Focus strategy', 'Cost Leadership strategy', 'Blue Ocean strategy'], correctIndex: 2, explanation: 'Cost leadership aims to produce at lower cost than all competitors, enabling lower prices or higher margins.' }, { question: 'Network effects mean:', options: ['A product improves when used on faster internet', 'Product value increases as more users join the platform', 'A company expands its network of suppliers', 'Marketing via social networks'], correctIndex: 1, explanation: 'Network effects: each additional user makes the product more valuable for all existing users (e.g. WhatsApp, LinkedIn).' }, { question: '"Stuck in the middle" in Porter\'s framework means:', options: ['A mid-market company', 'A firm that pursues neither cost leadership nor differentiation clearly, underperforming both', 'A growing startup', 'A company entering a new market'], correctIndex: 1, explanation: 'Porter argues that firms trying to be both low-cost AND differentiated end up with no clear advantage — "stuck in the middle".' }] }
    },
    'Operations & Process Management': {
      understand: {
        theory: `# Operations & Process Management\nOperations management designs and controls production and service delivery systems. Key concepts: value chain, process mapping, bottlenecks, and continuous improvement.\n\n## Value Chain (Porter)\nPrimary: Inbound Logistics → Operations → Outbound Logistics → Marketing & Sales → Service\nSupport: Infrastructure, HR, Technology, Procurement\n\n## Lean Principles (Toyota Production System)\n1. Eliminate **Muda** (waste): overproduction, waiting, transport, overprocessing, inventory, motion, defects\n2. **Just-in-Time**: produce exactly what is needed, when needed\n3. **Kaizen**: continuous improvement, small incremental changes\n4. **Kanban**: visual workflow management (limit WIP)\n\n## Key Metrics\n- **Throughput**: units produced per time period\n- **Cycle time**: time per unit from start to finish\n- **OEE** (Overall Equipment Effectiveness): Availability × Performance × Quality\n- **Takt time**: available production time ÷ customer demand`,
        examples: [{ title: 'Bottleneck analysis with Theory of Constraints', language: 'text', code: `Process: Order → [Design 3hr] → [Printing 8hr] → [QC 2hr] → Ship\n\nIdentify bottleneck: Printing (8hr) is the constraint\n\n5 Focusing Steps:\n1. IDENTIFY: Printing dept. is bottleneck\n2. EXPLOIT: No idle time on printer; schedule 24/7\n3. SUBORDINATE: Feed printing only what it can handle\n4. ELEVATE: Buy second printer or outsource overflow\n5. REPEAT: After fixing, find next bottleneck\n\nResult: Overall throughput limited by bottleneck — improving\nnon-bottleneck steps does NOT increase total output.`, explanation: 'Theory of Constraints: the system\'s output is determined by its weakest link (constraint). Improving non-constraints wastes resources.' }],
        keyPoints: ['A process runs at the speed of its bottleneck — identify and resolve it before optimising other steps', 'Lean\'s 7 wastes (TIMWOOD): Transport, Inventory, Motion, Waiting, Overproduction, Overprocessing, Defects', 'Six Sigma targets < 3.4 defects per million opportunities (DPMO) using DMAIC: Define-Measure-Analyse-Improve-Control']
      },
      evaluate: { questions: [{ question: 'What is a bottleneck in process management?', options: ['A narrow storage area', 'The fastest process step', 'The step that limits overall system throughput', 'A quality control failure'], correctIndex: 2, explanation: 'The bottleneck is the process step with the lowest capacity. It determines the maximum output of the entire process.' }, { question: 'Kaizen means:', options: ['Japanese for automation', 'Radical process redesign', 'Continuous improvement through small incremental changes', 'Quality inspection'], correctIndex: 2, explanation: 'Kaizen (改善) = change for better. Small, daily improvements involving all employees — not big-bang projects.' }, { question: 'Takt time = 480 min/day ÷ 60 units/day = ?', options: ['28,800 minutes', '8 min/unit — the pace of production to meet demand', '60 minutes', '480 units'], correctIndex: 1, explanation: 'Takt time is the rate at which you must complete one unit to meet customer demand. 480÷60 = 8 min/unit.' }] }
    },
    'Financial Literacy for Managers': {
      understand: {
        theory: `# Financial Literacy for Managers\nManagers must read three core financial statements and understand unit economics to make decisions.\n\n## Three Financial Statements\n1. **Income Statement (P&L)**: Revenue − Costs = Net Profit\n   - Gross Profit = Revenue − COGS\n   - EBITDA = Operating Earnings before depreciation/amortisation\n\n2. **Balance Sheet**: Assets = Liabilities + Equity (snapshot)\n   - Current assets (cash, receivables) vs. Fixed assets (property)\n   - Current liabilities (short-term debt) vs. Long-term liabilities\n\n3. **Cash Flow Statement**: Operating + Investing + Financing\n   - A profitable company can still go bankrupt if cash flow is negative\n\n## Key Ratios\n- **Gross Margin** = Gross Profit / Revenue\n- **Current Ratio** = Current Assets / Current Liabilities (>1 = healthy)\n- **ROE** = Net Income / Shareholders' Equity\n- **Debt/Equity** = Total Debt / Equity (leverage measure)`,
        examples: [{ title: 'Reading a P&L statement', language: 'text', code: `FY2025 Income Statement (₹ Lakhs)\n\nRevenue:                1,200\nCOGS:                  (720)   [60% of revenue]\nGross Profit:            480   [Gross Margin = 40%]\n\nOperating Expenses:    (240)\nEBITDA:                 240   [20% margin]\n\nDepreciation:           (40)\nEBIT:                   200\nInterest:               (20)\nEBT:                    180\nTax (25%):              (45)\nNet Profit:             135   [Net Margin = 11.25%]`, explanation: 'Reading top-down: revenue flows through cost layers to net profit. Each margin tells a different story about efficiency.' }],
        keyPoints: ['Profit ≠ Cash. A company can show profit but run out of cash if receivables are not collected (working capital trap)', 'EBITDA removes non-cash (depreciation) and financing effects — useful for comparing operational performance across companies', 'Gross Margin reveals pricing power and production efficiency. Net Margin shows overall profitability after all costs']
      },
      evaluate: { questions: [{ question: 'Gross Profit = ?', options: ['Revenue − All Expenses', 'Revenue − COGS (Cost of Goods Sold)', 'Revenue − Operating Expenses', 'Revenue − Interest − Tax'], correctIndex: 1, explanation: 'Gross Profit = Revenue minus the direct cost of producing goods (COGS). Before operating expenses.' }, { question: 'A company is profitable but going bankrupt. Most likely reason?', options: ['Tax errors', 'Negative cash flow — revenue is booked but cash is not collected', 'Too much equity', 'High gross margins'], correctIndex: 1, explanation: 'Accrual accounting books revenue when earned, not when cash arrives. Profitable companies can be cash-poor (e.g., slow receivables).' }, { question: 'Current Ratio < 1 signals:', options: ['Strong liquidity', 'The company may struggle to pay short-term obligations', 'High profitability', 'Undervalued stock'], correctIndex: 1, explanation: 'Current Ratio = Current Assets / Current Liabilities. Below 1 means short-term liabilities exceed liquid assets — liquidity risk.' }] }
    },
    'Leadership & Decision Making': {
      understand: {
        theory: `# Leadership & Decision Making\n## Leadership Styles (Situational Leadership)\n- **Directing**: high task, low relationship — new employees, crisis\n- **Coaching**: high task, high relationship — developing staff\n- **Supporting**: low task, high relationship — competent but uncertain\n- **Delegating**: low task, low relationship — experienced, motivated\n\n## Decision Making Frameworks\n### Rational Model\n1. Define the problem → 2. Identify criteria → 3. Weight criteria → 4. Generate alternatives → 5. Evaluate → 6. Choose best\n\n### RAPID Model (Bain)\n- **R**ecommend, **A**gree, **P**erform, **I**nput, **D**ecide — clarifies who does what\n\n### Decision Matrix\n| Option | Cost(×3) | Speed(×2) | Quality(×5) | Total |\n|--------|----------|-----------|-------------|-------|\n| A      | 4        | 3         | 5           | 43    |\n| B      | 5        | 5         | 3           | 40    |\n\nOption A wins: 4×3 + 3×2 + 5×5 = 12+6+25 = 43`,
        examples: [{ title: 'Cognitive biases in business decisions', language: 'text', code: `CONFIRMATION BIAS: Seeking info that confirms existing view\n  → Actively seek disconfirming evidence; Devil's Advocate\n\nSUNK COST FALLACY: Continuing a failing project because ₹5Cr invested\n  → Ask: "Would we start this project today?"\n\nANCHORING: First offer anchors negotiation perception\n  → Make the first offer; research BATNA before negotiating\n\nAVAILABILITY HEURISTIC: Vivid events feel more likely\n  → Use base rate statistics, not recent memorable examples\n\nGROUPTHINK: Harmony suppresses dissent\n  → Structured debate, anonymous input, red-team exercises`, explanation: 'Recognising cognitive biases does not eliminate them — use structured processes to counteract them systematically.' }],
        keyPoints: ['Great leaders adapt their style to the follower\'s competence and commitment (Situational Leadership — Hersey & Blanchard)', 'Most poor business decisions are explainable by cognitive biases — sunk cost, anchoring, and confirmation bias are most common', 'Decision quality ≠ outcome quality. Good decisions with bad outcomes still had a sound process — focus on improving process']
      },
      evaluate: { questions: [{ question: 'The Sunk Cost Fallacy causes managers to:', options: ['Invest in new projects too quickly', 'Continue failing projects because of past investment, ignoring future prospects', 'Underestimate project costs', 'Cut projects prematurely'], correctIndex: 1, explanation: 'Past costs are sunk — irretrievable. Only future costs and benefits should drive decisions.' }, { question: 'In Situational Leadership, "Delegating" style is best for:', options: ['New employees who need direction', 'Competent, motivated employees who need autonomy', 'Employees in crisis needing support', 'Employees learning new skills'], correctIndex: 1, explanation: 'Delegating is low-directive/low-supportive — appropriate when followers are both competent and committed.' }, { question: 'Groupthink is reduced by:', options: ['Larger teams', 'Assigning a Devil\'s Advocate to argue against the dominant view', 'Faster decision cycles', 'Hierarchical reporting'], correctIndex: 1, explanation: 'Devil\'s Advocate, anonymous voting, and structured debate force dissenting views into consideration.' }] }
    },
    'Marketing Strategy': {
      understand: {
        theory: `# Marketing Strategy\n## STP Framework\n- **Segmentation**: Divide market by demographics, psychographics, geography, behaviour\n- **Targeting**: Choose which segment(s) to serve\n- **Positioning**: Define how you want to be perceived vs. competitors\n\n## Marketing Mix (7Ps)\n1. **Product** — features, quality, design, branding\n2. **Price** — value-based, cost-plus, competitive, freemium\n3. **Place** — distribution channels (direct, retail, online)\n4. **Promotion** — advertising, PR, social, SEO, content\n5. **People** — staff, culture, customer service\n6. **Process** — service delivery systems\n7. **Physical Evidence** — tangibles that signal quality\n\n## Digital Marketing Funnel\nAwareness → Interest → Desire → Action → Retention (AIDAR)\n\nMetrics: Impressions → CTR → Conversion Rate → CAC → LTV`,
        examples: [{ title: 'Positioning statement template', language: 'text', code: `Formula:\n"For [TARGET SEGMENT] who [NEED/WANT],\n[BRAND] is the [MARKET CATEGORY]\nthat [POINT OF DIFFERENCE]\nbecause [REASON TO BELIEVE]."\n\nExample (Slack):\n"For remote teams who struggle with email overload,\nSlack is the team communication platform\nthat organises conversations by topic and integrates\nall your work tools in one place,\nbecause 80% of Fortune 100 companies trust it."`, explanation: 'Positioning statements force clarity: who exactly you serve, what category you compete in, what makes you different, and why it is credible.' }],
        keyPoints: ['CAC (Customer Acquisition Cost) must be less than LTV (Lifetime Value) for a sustainable business. LTV:CAC ratio > 3 is healthy', 'Product-Market Fit (PMF) means customers pull your product — high retention, word-of-mouth, NPS >50. Without PMF, more marketing wastes money', 'Price communicates value. Pricing too low signals low quality. Value-based pricing (charge what the customer gains) outperforms cost-plus']
      },
      evaluate: { questions: [{ question: 'STP in marketing stands for:', options: ['Sales, Trade, Profit', 'Segmentation, Targeting, Positioning', 'Strategy, Tactics, Performance', 'Social, Traditional, Paid'], correctIndex: 1, explanation: 'STP is a core framework: Segment the market, Target the right segment, Position your offer distinctively.' }, { question: 'LTV:CAC ratio of 3:1 means:', options: ['Company spends ₹3 to acquire every ₹1 of revenue — unsustainable', 'A customer generates ₹3 in lifetime value for every ₹1 spent acquiring them — healthy', 'Marketing ROI is 300%', 'Customer retention is 33%'], correctIndex: 1, explanation: 'LTV:CAC ≥ 3 is the benchmark for a healthy SaaS/subscription business. Below 1 means you lose money on every customer.' }, { question: 'Value-based pricing sets price based on:', options: ['Production cost + margin', 'Competitor prices', 'The value the customer receives from the product', 'Government regulations'], correctIndex: 2, explanation: 'Value-based pricing anchors to customer-perceived value — can charge significantly more than cost-plus if value delivered is high.' }] }
    },
    'Organisational Behaviour': {
      understand: {
        theory: `# Organisational Behaviour\nOB studies how individuals and groups behave in organisations. Key areas: motivation, team dynamics, organisational culture, and change management.\n\n## Motivation Theories\n**Maslow's Hierarchy**: Physiological → Safety → Social → Esteem → Self-Actualisation\n**Herzberg's Two-Factor**:\n- **Hygiene factors** (must have or dissatisfied): salary, conditions, job security\n- **Motivators** (drive engagement): achievement, recognition, responsibility, growth\n**Vroom's Expectancy Theory**: Motivation = Expectancy × Instrumentality × Valence\n\n## Team Stages (Tuckman)\nForming → Storming → Norming → Performing → Adjourning\n\n## Kotter's 8-Step Change Model\n1. Create urgency 2. Form coalition 3. Strategic vision 4. Enlist volunteers 5. Enable action 6. Short-term wins 7. Sustain acceleration 8. Institute change`,
        examples: [{ title: 'Applying Herzberg at a startup', language: 'text', code: `HYGIENE (fix first — prevent dissatisfaction):\n✓ Competitive salary (market rate or above)\n✓ Clear equity/ESOP policy\n✓ Ergonomic workspace, tools that work\n✓ Job security (clear runway communication)\n\nMOTIVATORS (drive discretionary effort):\n✓ Meaningful work → show customer impact\n✓ Autonomy → OKRs not micromanagement\n✓ Mastery → learning budget ₹50k/person/year\n✓ Purpose → company mission they believe in\n✓ Recognition → peer kudos, CEO shoutouts`, explanation: 'Herzberg: fixing hygiene factors reduces dissatisfaction but does NOT motivate. True engagement comes from motivators.' }],
        keyPoints: ['Herzberg: salary alone does not motivate — it only prevents dissatisfaction. Meaningful work drives discretionary effort', 'Teams in Storming stage experience conflict — this is normal and necessary. Suppressing conflict leads to groupthink', 'Culture eats strategy for breakfast (Drucker). Changing strategy without changing culture = failed transformation']
      },
      evaluate: { questions: [{ question: 'In Herzberg\'s theory, which is a "motivator" (drives engagement)?', options: ['Salary', 'Job security', 'Working conditions', 'Achievement and recognition'], correctIndex: 3, explanation: 'Hygiene factors prevent dissatisfaction; motivators drive engagement. Achievement, recognition, and growth are motivators.' }, { question: 'Tuckman\'s "Storming" stage is characterised by:', options: ['High productivity', 'Team conflicts as members assert positions and push against structure', 'Polite initial introductions', 'Project completion'], correctIndex: 1, explanation: 'Storming involves conflict as team members challenge each other and the leader. It is necessary before Norming.' }, { question: 'Kotter\'s Change Model starts with:', options: ['Announcing the change plan', 'Creating a sense of urgency about why change is needed', 'Forming the project team', 'Setting quick win targets'], correctIndex: 1, explanation: 'Without urgency, people do not feel compelled to change. Step 1 is creating a burning platform that motivates action.' }] }
    },
    'Business Model Innovation': {
      understand: {
        theory: `# Business Model Innovation\nA business model defines how a company creates, delivers, and captures value. The **Business Model Canvas** (Osterwalder) maps this in 9 building blocks.\n\n## Business Model Canvas\n| Key Partners | Key Activities | Value Propositions | Customer Relationships | Customer Segments |\n|---|---|---|---|---|\n| | Key Resources | | Channels | |\n| Cost Structure | | | Revenue Streams | |\n\n## Revenue Model Types\n- **Subscription**: Netflix, Spotify, SaaS — recurring, predictable\n- **Transaction fee**: Stripe, Zepto — per transaction\n- **Freemium**: Slack, Canva — free base, paid premium\n- **Marketplace**: Amazon, Swiggy — take rate on GMV\n- **Licensing**: Patents, Qualcomm — charge for IP use\n- **Data/Ads**: Google, Facebook — monetise user attention\n\n## Disruption Framework (Christensen)\nDisruptive innovations start by serving overserved or ignored segments at lower quality/price, then improve upmarket to displace incumbents.`,
        examples: [{ title: 'Platform Business Model vs. Pipeline', language: 'text', code: `PIPELINE (traditional value chain):\nInputs → Company creates value → Output → Customer\nExample: Toyota: Steel → Factory → Cars → Dealership\n\nPLATFORM (two-sided marketplace):\nProducers ←→ Platform (facilitates) ←→ Consumers\nExample: Uber: Drivers ←→ Uber App ←→ Riders\n\nKey Difference:\nPipeline: Company owns production\nPlatform: Company owns rules/interactions\n\nPlatform economics: Cross-side network effects\n(more drivers → faster pickups → more riders → more drivers)`, explanation: 'Platform businesses are asset-light but win through network effects. Valuation often exceeds asset-heavy pipeline competitors.' }],
        keyPoints: ['The Business Model Canvas makes strategy tangible — draw it collaboratively, not just as a CEO exercise', 'Freemium works when: free tier creates real value, network effects exist, paid tier has clear premium over free', 'Disruption is not about better products — it is about targeting non-consumers or over-served segments with simpler, cheaper solutions']
      },
      evaluate: { questions: [{ question: 'In the Business Model Canvas, "Value Proposition" describes:', options: ['Revenue streams', 'How you make money', 'The bundle of products/services that create value for a specific customer segment', 'Key business activities'], correctIndex: 2, explanation: 'Value Proposition is the core of the canvas — what unique value you deliver to customers and why they choose you.' }, { question: 'Freemium revenue model works best when:', options: ['All users pay equally', 'Network effects exist and the paid tier offers significantly more value than free', 'Product has high production cost', 'Target market is price-insensitive'], correctIndex: 1, explanation: 'Freemium needs network effects (more users → more value) and a compelling paid upgrade that power users need.' }, { question: 'Christensen\'s Disruptive Innovation theory predicts:', options: ['Incumbents always win technology races', 'New entrants win by starting with underserved/ignored segments then improving upmarket', 'Disruption comes from direct head-to-head competition', 'Better products always win'], correctIndex: 1, explanation: 'Disruption starts below the radar — cheap/simple for non-consumers or over-served. Incumbents ignore it until too late.' }] }
    },
    'Corporate Governance': {
      understand: {
        theory: `# Corporate Governance\nCorporate governance is the system of rules, practices, and processes by which a company is directed and controlled. It balances the interests of stakeholders: shareholders, management, customers, employees, and society.\n\n## Board Structure\n- **Board of Directors**: Fiduciary duty — oversight, not management\n- **Executive Directors**: Inside board (CEO, CFO)\n- **Independent Non-Executive Directors (NEDs)**: Provide oversight; no financial conflict\n- **Audit Committee**: Financial controls, external auditor oversight\n- **Remuneration Committee**: CEO/executive pay\n\n## Agency Problem (Principal-Agent)\nShareholders (principals) hire managers (agents). Managers may pursue personal interests over shareholder interests.\nSolutions: stock options, performance bonuses, board oversight, activist shareholders\n\n## ESG (Environmental, Social, Governance)\n- **E**: Carbon footprint, sustainability\n- **S**: Labour practices, D&I, community\n- **G**: Board diversity, transparency, anti-corruption`,
        examples: [{ title: 'Corporate governance failures — case patterns', language: 'text', code: `ENRON (2001): Fraud via off-balance-sheet entities\nRoot cause: Board failed to question CFO; conflicts of interest;\nAuditors (Arthur Andersen) had consulting revenue to protect\n\nSAYTAM (2009, India): ₹7,136 Cr accounting fraud\nRoot cause: Founder-dominated board; no independent oversight;\nAuditors rubber-stamped statements\n\nCommon patterns:\n1. Dominant founder/CEO with weak board\n2. Conflicts of interest in auditing\n3. Complex structures obscuring reality\n4. Pressure to hit short-term financial targets`, explanation: 'Most governance failures share these patterns. Independent boards, rotating auditors, and whistle-blower protections are structural responses.' }],
        keyPoints: ['Independent NEDs provide oversight because executive directors have conflicts of interest in overseeing themselves', 'ESG metrics are increasingly tied to capital access — institutional investors use ESG scores in investment decisions', 'The Companies Act 2013 (India) mandates at least 1/3 independent directors on listed companies\' boards']
      },
      evaluate: { questions: [{ question: 'What is the Principal-Agent Problem in corporate governance?', options: ['The CEO reports to the CFO', 'Managers (agents) may act in their own interest rather than shareholders\' (principals\') interest', 'Companies need multiple principals', 'Board members cannot be paid'], correctIndex: 1, explanation: 'Shareholders delegate to managers but cannot perfectly monitor them — managers may pursue personal gain, tenure, or risk aversion.' }, { question: 'The G in ESG stands for:', options: ['Growth', 'Geography', 'Governance — board structure, transparency, shareholder rights, anti-corruption', 'Green initiatives'], correctIndex: 2, explanation: 'ESG: Environmental, Social, Governance. Governance covers board composition, executive pay, shareholder rights, and ethical conduct.' }, { question: 'An Audit Committee\'s primary responsibility is:', options: ['Setting executive salaries', 'Overseeing financial reporting integrity and external auditor independence', 'Approving mergers', 'Hiring the CFO'], correctIndex: 1, explanation: 'The Audit Committee ensures accurate financial reporting and that external auditors remain truly independent of management.' }] }
    },
    'Innovation & Design Thinking': {
      understand: {
        theory: `# Innovation & Design Thinking\nDesign Thinking is a human-centred approach to innovation. It reframes problems from customer perspectives before jumping to solutions.\n\n## Design Thinking Process (IDEO/Stanford)\n1. **Empathise** — observe, interview, immerse in user's world\n2. **Define** — synthesise findings into a problem statement (POV)\n3. **Ideate** — generate many ideas; diverge before converging; no judgment\n4. **Prototype** — build a rough, quick representation; fail cheaply\n5. **Test** — put in front of real users; iterate based on feedback\n\n## POV (Point of View) Statement\n"[USER] needs [NEED] because [SURPRISING INSIGHT]"\n\nExample: "Urban commuters need a way to feel productive during metro rides because 45 minutes of dead time daily compounds to losing 180 hours per year."\n\n## Innovation Types\n- **Incremental**: Small improvements to existing products (iPhone updates)\n- **Architectural**: Recombine existing components in new ways (iPad)\n- **Disruptive**: New technology + new business model (Airbnb)\n- **Radical**: Entirely new technology + market (SpaceX)`,
        examples: [{ title: 'Sprint methodology (Google Ventures)', language: 'text', code: `5-Day Design Sprint:\n\nMON: Map the problem; pick a target (long-term goal + sprint questions)\nTUE: Sketch competing solutions independently; review existing ideas\nWED: Decide: storyboard the winning idea\nTHU: Prototype: build a realistic facade (not working software)\nFRI: Test with 5 real users; 80% of usability issues found by user 5\n\nKey principle: 5 days of sprinting > 3 months of building to test\none risky assumption.`, explanation: 'Design Sprints compress months of work into one week by testing a realistic prototype — avoiding costly full builds of wrong ideas.' }],
        keyPoints: ['Diverge (generate many ideas) before converging (pick the best). Most teams converge too fast — first idea is rarely best', 'Prototypes should be cheap and rough — the goal is learning, not impressing. A paper prototype can reveal 80% of UX problems', '"How Might We" (HMW) questions reframe problems as opportunities: "How might we make waiting enjoyable?"']
      },
      evaluate: { questions: [{ question: 'In Design Thinking, the Empathise phase involves:', options: ['Generating solution ideas', 'Building a prototype', 'Observing and interviewing users to understand their actual needs and pain points', 'Testing the final product'], correctIndex: 2, explanation: 'Empathise is about deeply understanding users — their context, motivations, frustrations — before assuming you know the problem.' }, { question: 'A POV (Point of View) statement structure is:', options: ['Problem + Solution + Cost', 'User + Need + Insight (surprising "because" statement)', 'Market + Product + Revenue', 'Goal + Constraint + Timeline'], correctIndex: 1, explanation: 'POV = [User] needs [verb/need] because [surprising insight]. The insight reframes the problem and creates design direction.' }, { question: 'Why should prototypes be rough and cheap?', options: ['Saves time building the final product', 'Rough prototypes are easier to change based on user feedback — you are testing assumptions, not building a product', 'Users prefer simple designs', 'Regulations require it'], correctIndex: 1, explanation: 'High-fidelity prototypes create sunk cost pressure. Rough prototypes stay disposable — learning is the goal, not the artefact.' }] }
    },
    'Negotiation & Conflict Resolution': {
      understand: {
        theory: `# Negotiation & Conflict Resolution\n## Principled Negotiation (Harvard Method — Fisher & Ury)\n4 principles from *Getting to Yes*:\n1. **Separate people from the problem** — don't attack the person\n2. **Focus on interests, not positions** — why they want what they want\n3. **Invent options for mutual gain** — brainstorm before evaluating\n4. **Insist on objective criteria** — market data, precedent, law\n\n## BATNA — Best Alternative to Negotiated Agreement\nYour BATNA = your walk-away power. Know it before negotiating.\nStrengthening BATNA: create multiple alternatives; build relationships; research market\n\n## Conflict Resolution Styles (Thomas-Kilmann)\n- **Competing**: high assertive, low cooperative — useful in crisis\n- **Collaborating**: high assertive, high cooperative — win-win\n- **Compromising**: moderate both — fast resolution with some loss\n- **Avoiding**: low both — appropriate for minor issues\n- **Accommodating**: low assertive, high cooperative — maintain relationship`,
        examples: [{ title: 'Salary negotiation using Harvard Method', language: 'text', code: `POSITION (wrong): "I want ₹20 LPA"\nInterest (right): "I want compensation that reflects market rate\nfor my skills and enables me to focus on work"\n\nObjective Criteria:\n- Glassdoor data: Role pays ₹18-24L in this city\n- Competing offer: ₹19L from Company B (BATNA)\n- Cost of living increase vs. current role: +₹2L\n\nOptions for Mutual Gain:\n- Performance bonus structure\n- Joining bonus if base is fixed\n- Extra leave days / WFH flexibility\n- Accelerated 6-month review\n\nResult: Both sides find creative value beyond base salary`, explanation: 'Interests-based negotiation expands the pie. Position-based creates zero-sum fights. BATNA creates real leverage.' }],
        keyPoints: ['BATNA is your real power in any negotiation — the stronger your alternatives, the less you need this deal', 'Interests vs. Positions: "I want 30 days delivery" (position) vs. "I need it by month-end for our product launch" (interest) — knowing interests opens options', 'Never accept or make the first offer immediately — signal that you are considering your options even if the offer is acceptable']
      },
      evaluate: { questions: [{ question: 'BATNA stands for:', options: ['Best Alternative To Not Agreeing', 'Best Alternative To a Negotiated Agreement', 'Basic Approach To Negotiation Agreement', 'Bilateral Agreement To Negotiate Again'], correctIndex: 1, explanation: 'BATNA is your best option if this negotiation fails. A strong BATNA gives you power to walk away from bad deals.' }, { question: 'Principled negotiation focuses on:', options: ['Winning at all costs', 'Interests (why people want things) not positions (what they demand)', 'Being accommodating to maintain relationships', 'Avoiding conflict entirely'], correctIndex: 1, explanation: 'Focusing on interests (underlying needs/motivations) creates space for creative solutions that meet both sides\' real needs.' }, { question: 'Thomas-Kilmann "Collaborating" style is:', options: ['Quick compromise with partial gains for both', 'High assertiveness + high cooperation — seeks win-win', 'Low effort to avoid conflict', 'Asserting your position firmly'], correctIndex: 1, explanation: 'Collaborating invests time to find solutions that fully satisfy both parties — best for important issues where relationships matter.' }] }
    },
  },

  'Digital Marketing': {
    'SEO & Content Strategy': {
      understand: {
        theory: `# SEO & Content Strategy\nSEO (Search Engine Optimisation) is the practice of improving a website's organic visibility in search results. It divides into three pillars: **Technical**, **On-Page**, and **Off-Page**.\n\n## Technical SEO\n- Core Web Vitals: LCP < 2.5s, FID < 100ms, CLS < 0.1\n- Mobile-first indexing: Google primarily uses mobile version\n- Structured data (schema.org) for rich results\n- Crawlability: robots.txt, sitemap.xml, clean URL structure\n\n## On-Page SEO\n- **Title tag**: Primary keyword near start; 50-60 chars\n- **Meta description**: CTR-driving summary; 150-160 chars\n- **H1/H2/H3**: Logical heading structure; one H1 per page\n- **Keyword density**: Natural use; avoid stuffing\n- **Internal linking**: Distributes PageRank; improves crawl depth\n\n## Content Strategy\n- **Topic clusters**: Pillar page (broad topic) + cluster pages (subtopics) + internal links\n- **Search intent**: Informational | Navigational | Transactional | Commercial investigation`,
        examples: [{ title: 'Keyword research process', language: 'text', code: `Step 1: SEED KEYWORDS — brainstorm core topics\n"digital marketing course India"\n\nStep 2: EXPAND with tools (Ahrefs, SEMrush, Google Search Console)\nSeed → "digital marketing course India online" (1.2K/mo, KD 42)\nSeed → "best digital marketing certification" (3.6K/mo, KD 67)\n\nStep 3: CLUSTER by intent\nInfomational: "what is digital marketing"\nTransactional: "buy digital marketing course"\nNavigational: "HubSpot Academy login"\n\nStep 4: PRIORITISE\nTarget: High volume + Low difficulty + Matches your stage`, explanation: 'Keyword Difficulty (KD) measures how hard it is to rank on page 1. Newer sites should target KD < 40 first.' }],
        keyPoints: ['Core Web Vitals (CWV) are a direct Google ranking factor since 2021 — LCP, FID/INP, CLS measure user experience', 'Topic clusters outperform individual pages — pillar + cluster architecture signals topical authority to search engines', 'Search intent must match your page type: transactional queries need product/service pages, not blog posts']
      },
      evaluate: { questions: [{ question: 'Core Web Vitals measure:', options: ['Server uptime', 'Page speed, interactivity, and visual stability from a user experience perspective', 'Number of backlinks', 'Domain authority'], correctIndex: 1, explanation: 'CWVs measure LCP (load speed), FID/INP (input delay), and CLS (layout shift) — user-centred performance metrics that affect rankings.' }, { question: 'A topic cluster model uses:', options: ['One long article covering everything', 'A broad pillar page + multiple detailed cluster pages on subtopics + internal links between them', 'Only backlinks for authority', 'Social media to build topical authority'], correctIndex: 1, explanation: 'Topic clusters group semantically related content, signalling deep topical authority to Google on a subject area.' }, { question: 'Search intent for "best project management software" is:', options: ['Informational', 'Navigational', 'Transactional', 'Commercial investigation — user is comparing options before buying'], correctIndex: 3, explanation: 'Commercial investigation queries ("best X", "X vs Y", "X review") indicate users researching before a purchase decision.' }] }
    },
    'Paid Advertising (Google & Meta)': {
      understand: {
        theory: `# Paid Advertising: Google & Meta Ads\n\n## Google Ads\n**Ad Rank** = Bid × Quality Score × Expected Impact of Extensions\n**Quality Score** = Expected CTR × Ad Relevance × Landing Page Experience\n\nCampaign types: Search | Display | Shopping | YouTube | Performance Max\n\nSearch match types:\n- **Broad match**: most reach, least control\n- **Phrase match**: "keyword" — query must contain phrase\n- **Exact match**: [keyword] — exact query\n\n## Meta Ads (Facebook/Instagram)\n- **Campaign** → **Ad Set** (audience, budget, schedule) → **Ad** (creative)\n- Audience: Custom (email list, site visitors), Lookalike (1-10% similarity)\n- Bidding: CPM (cost per 1000 impressions), CPC (per click), CPA (per action)\n\n## Attribution Models\n- **Last click**: 100% credit to last touchpoint\n- **First click**: 100% credit to first touchpoint\n- **Linear**: equal credit across all touchpoints\n- **Data-driven (Google)**: ML-assigned credit`,
        examples: [{ title: 'ROAS calculation and optimisation', language: 'text', code: `ROAS = Revenue from Ads / Ad Spend\n\nExample:\nAd spend: ₹1,00,000\nRevenue attributed: ₹4,50,000\nROAS = 4.5x (for every ₹1 spent, ₹4.5 returned)\n\nTarget ROAS: depends on product margin\nIf gross margin = 40%, break-even ROAS = 1/0.4 = 2.5x\nSo 4.5x ROAS → profitable\n\nOptimisation levers:\n• Pause low ROAS keywords/audiences\n• Test new ad creatives (video outperforms static on Meta)\n• Improve landing page conversion rate\n• Bid adjustments by device/time/location`, explanation: 'ROAS alone is insufficient — you need gross margin context. A 10x ROAS on a 5% margin product may still lose money.' }],
        keyPoints: ['Quality Score reduces your cost per click — improving ad relevance and landing page experience lowers effective CPC', 'Lookalike audiences on Meta are one of the highest-performing targeting options — seed with your best customers', 'Always A/B test creatives — creative is the #1 driver of ad performance on Meta. Use 3-5 variations per audience']
      },
      evaluate: { questions: [{ question: 'Google Ad Rank is primarily determined by:', options: ['Highest bidder always wins', 'Bid × Quality Score × Extension impact', 'Daily budget', 'Number of keywords'], correctIndex: 1, explanation: 'Ad Rank determines ad position and actual cost. Quality Score (relevance + landing page) means high-quality ads beat higher bids.' }, { question: 'A Lookalike Audience on Meta is:', options: ['Your existing customer email list uploaded', 'An audience of users similar to a seed audience (e.g., your best customers)', 'All users in a geographic area', 'Users who visited your website'], correctIndex: 1, explanation: 'Lookalike audiences use Meta\'s ML to find users with similar characteristics to your seed audience — typically high-converting.' }, { question: 'ROAS (Return on Ad Spend) = ?', options: ['Ad spend / Revenue', 'Revenue from ads / Ad spend', 'Clicks / Impressions', 'Revenue / Total costs'], correctIndex: 1, explanation: 'ROAS = Revenue from ads ÷ Ad spend. A 4x ROAS means every ₹1 in ads generates ₹4 in revenue.' }] }
    },
    'Social Media Marketing': {
      understand: {
        theory: `# Social Media Marketing\n## Platform-Strategy Fit\n| Platform | Best For | Format |\n|---|---|---|\n| LinkedIn | B2B, hiring, thought leadership | Long posts, articles, carousels |\n| Instagram | Visual brands, D2C, lifestyle | Reels, stories, carousels |\n| YouTube | Education, entertainment, trust | Long-form, Shorts |\n| Twitter/X | News, tech, real-time | Short takes, threads |\n| Facebook | Local biz, communities, ads | Groups, video ads |\n\n## Content Framework (3-1-1 Rule)\n- 3 value posts (educate, entertain, inspire)\n- 1 soft promotion (case study, testimonial)\n- 1 direct CTA (buy, sign up, download)\n\n## Algorithm Signals\n- **Saves & shares** > likes > comments (engagement quality)\n- **Watch time / completion rate** for video (key metric)\n- **Posting consistency**: 3-5x/week beats inconsistent daily\n- **Response time**: Reply to comments in first hour (boosts reach)`,
        examples: [{ title: 'Instagram content strategy for EdTech brand', language: 'text', code: `CONTENT PILLARS (for CareerBoost):\n1. Career Tips (40%): "5 ways to negotiate salary", interview tips\n2. Student Wins (25%): Testimonials, placement stories, salary reveals\n3. Platform Features (15%): Tutorials, new feature demos\n4. Trending/Reactive (10%): React to hiring trends, campus news\n5. Fun/Behind-Scenes (10%): Team culture, memes in niche\n\nFORMAT MIX (Instagram 2024):\n• Reels: 60% of content (algo pushes reels)\n• Carousels: 25% (highest save rate)\n• Stories: Daily (stay top of mind)\n• Lives: Bi-weekly (Q&A with placement team)`, explanation: 'Content pillars ensure variety and strategic purpose. Reels are the primary organic reach driver on Instagram in 2024-25.' }],
        keyPoints: ['Algorithm rewards content quality (saves, shares, completion rate) not posting frequency. One great Reel beats 7 average posts', 'Community management (replying to DMs/comments in first hour) significantly boosts organic reach on Instagram', 'Repurpose across platforms: one LinkedIn article → Twitter thread → Instagram carousel → YouTube Short — maximises content investment']
      },
      evaluate: { questions: [{ question: 'Which engagement type signals highest content quality to Instagram\'s algorithm?', options: ['Likes', 'Comments', 'Saves and Shares', 'Profile visits'], correctIndex: 2, explanation: 'Saves signal "I want to remember this" — strong intent. Shares expand reach. Both are weighted more heavily than passive likes.' }, { question: 'The 3-1-1 content rule means:', options: ['Post 3 times per day', '3 value posts : 1 soft promotion : 1 direct CTA — prevents feed from being too sales-heavy', 'Reply 3 times per comment', '3 hashtags per post'], correctIndex: 1, explanation: '3-1-1 ensures your feed builds trust with value-first content before asking the audience for action.' }, { question: 'LinkedIn content performs best as:', options: ['Short 5-word posts', 'Long-form posts with personal stories, lessons, or data-backed insights (thought leadership)', 'Promotional product announcements only', 'Only company page posts, not personal'], correctIndex: 1, explanation: 'LinkedIn\'s algorithm favours content that generates comments and dwell time. Personal stories and actionable insights perform best.' }] }
    },
    'Email Marketing & CRM': {
      understand: {
        theory: `# Email Marketing & CRM\n## Why Email Still Dominates\n- ROI: ₹42 return for every ₹1 spent (DMA, avg.)\n- You own the list — no algorithm dependency\n- Segmented email converts 6× better than generic blasts\n\n## Email Marketing Metrics\n- **Open Rate**: 20-25% is average; subject line drives this\n- **CTR**: 2-3% average; CTA placement & copy drives this\n- **Bounce rate**: Hard bounce (bad email) > 2% = deliverability risk\n- **Unsubscribe rate**: > 0.5% signals irrelevance\n\n## Automation Flows\n1. **Welcome sequence** (days 1-7): brand intro, top content, first offer\n2. **Nurture sequence**: weekly value email → case study → demo invite\n3. **Abandoned cart**: 1hr → 24hr → 72hr reminder with discount\n4. **Win-back**: Inactive 90+ days → re-engagement campaign\n\n## CRM Best Practices\n- Lead scoring: Prioritise sales team's outreach by engagement\n- Lifecycle stages: Lead → MQL → SQL → Opportunity → Customer → Advocate`,
        examples: [{ title: 'Subject line A/B testing framework', language: 'text', code: `TEST ONE variable at a time:\n\nLENGTH:\nA: "5 resume tips"\nB: "The 5 resume mistakes costing you interview callbacks"\n\nPERSONALISATION:\nA: "New course for data science"\nB: "{{first_name}}, your data science learning path is ready"\n\nEMOTION:\nA: "Interview tips inside"\nB: "I got rejected 11 times before this changed everything"\n\nSample size: 1000+ recipients per variant for significance\nWinner: Open rate + click rate (not just open rate)`, explanation: 'A/B tests need statistical significance. Test subject line for opens, then test email body for clicks — separate experiments.' }],
        keyPoints: ['Segmentation is the single highest-impact email marketing improvement — send relevant content, not mass blasts', 'Subject lines should trigger curiosity or promise clear value. Avoid spam trigger words: FREE, WINNER, URGENT in all caps', 'Email deliverability depends on domain reputation — warm up new domains slowly, maintain low bounce/complaint rates']
      },
      evaluate: { questions: [{ question: 'What makes email marketing ROI exceptional vs. other channels?', options: ['Emails are free to send', 'You own the list — no platform dependency; segmented email converts 6× better than social ads', 'Email has the highest reach', 'Emails are indexed by Google'], correctIndex: 1, explanation: 'Email lists are owned assets. Social reach depends on algorithms; email goes directly to the inbox. Average ROI ~42:1.' }, { question: 'An "abandoned cart" email sequence best practice is:', options: ['Send one email 24 hours later', 'Multi-step: 1 hour → 24 hours → 72 hours, with increasing incentive', 'Only send one email with a discount immediately', 'Send weekly until they buy'], correctIndex: 1, explanation: 'Three-step cadence recovers 5-10% of abandoned carts. First email reminds; second adds urgency; third offers incentive.' }, { question: 'Email Hard Bounce means:', options: ['Email was opened but not clicked', 'Email could not be delivered permanently (invalid address, domain doesn\'t exist)', 'Email was sent to spam', 'Email bounced back due to server overload'], correctIndex: 1, explanation: 'Hard bounces are permanent delivery failures. Keep hard bounce rate < 2% or your sender reputation and deliverability will suffer.' }] }
    },
    'Analytics & Conversion Optimisation': {
      understand: {
        theory: `# Analytics & Conversion Rate Optimisation (CRO)\n## Google Analytics 4 (GA4)\nGA4 is event-based — every interaction is an event. Key metrics:\n- **Users**: unique visitors\n- **Sessions**: grouped visit interactions\n- **Engagement Rate**: sessions with meaningful interaction > 10s\n- **Conversion Rate**: goal completions / sessions\n\n## CRO Framework\n1. **Research**: Heatmaps (Hotjar), session recordings, funnel analysis\n2. **Hypothesis**: "If we [change X], conversion will increase because [user insight Y]"\n3. **A/B Test**: Minimum 2 weeks; 95% statistical significance\n4. **Analyse**: Did conversion metric improve? Secondary effects?\n5. **Iterate**: Document learnings; run next experiment\n\n## Key CRO Levers\n- **Headline clarity**: Specific > clever ("Get hired in 90 days" beats "Unlock your potential")\n- **Social proof**: Logos, testimonials, review counts (above the fold)\n- **Friction reduction**: Fewer form fields, guest checkout, autofill\n- **CTA**: One primary CTA per page; high contrast; specific action verb`,
        examples: [{ title: 'Funnel analysis — finding leakage', language: 'text', code: `E-commerce conversion funnel:\nHome Page:       10,000 users  (baseline)\nProduct Page:     4,000 users  (40% drop — check homepage UX)\nAdd to Cart:      1,200 users  (70% drop — product page issue!)\nCheckout Start:   900 users    (25% drop — acceptable)\nCheckout Submit:  650 users    (28% drop — check form friction)\nPayment:          500 users    (23% drop — payment UX)\n\nBiggest drop: Product Page → Add to Cart (70%)\nFix: A/B test product images, price display, reviews section\n\nExpected impact: Fixing 70% drop-off step > fixing 28% drop-off`, explanation: 'Fix the biggest leaks first. A 10% improvement at the highest-drop step gives more lift than 50% improvement at a low-traffic step.' }],
        keyPoints: ['Statistical significance (>95%) means the result is not due to chance. A/B tests need 100+ conversions per variant minimum', 'Heatmaps reveal what users see and click — most visitors do not scroll past the fold on landing pages', 'Page load speed is a conversion rate factor: 1 second delay = 7% drop in conversions (Amazon/Google studies)']
      },
      evaluate: { questions: [{ question: 'Conversion Rate = ?', options: ['Clicks / Impressions', 'Goal completions / Total sessions', 'Revenue / Ad spend', 'New users / Total users'], correctIndex: 1, explanation: 'Conversion Rate = Conversions (goals) ÷ Sessions. E.g. 500 signups / 10,000 sessions = 5% CVR.' }, { question: 'In a CRO A/B test, what is statistical significance?', options: ['Both variants have equal traffic', 'The result is unlikely to be due to chance (typically 95% confidence threshold)', 'The test ran for 7 days', 'The winning variant has more conversions'], correctIndex: 1, explanation: '95% significance means there is only a 5% chance the observed difference is random. This threshold minimises false positives.' }, { question: 'Heatmaps in CRO are used to:', options: ['Track server performance', 'Visualise where users click, scroll, and spend attention on a page', 'A/B test headlines', 'Analyse email open rates'], correctIndex: 1, explanation: 'Heatmaps (Hotjar, Microsoft Clarity) show user attention and interaction patterns — revealing what gets ignored vs. engaged with.' }] }
    },
    'Influencer & Affiliate Marketing': {
      understand: {
        theory: `# Influencer & Affiliate Marketing\n## Influencer Marketing Tiers\n| Tier | Followers | Avg Engagement | Best For |\n|---|---|---|---|\n| Mega | 1M+ | 1-2% | Brand awareness |\n| Macro | 100K-1M | 2-3% | Reach + credibility |\n| Micro | 10K-100K | 5-8% | Niche targeting, ROI |\n| Nano | 1K-10K | 8-15% | Hyper-local, authentic |\n\n## Key Metrics\n- **EMV** (Earned Media Value): Estimated value of organic influencer reach\n- **CPV** (Cost Per View), **CPE** (Cost Per Engagement)\n- **Attribution**: Unique UTM links, promo codes, affiliate links\n\n## Affiliate Marketing\n- **Publisher/Affiliate**: Promotes product, earns commission on sales\n- **Advertiser**: Pays commission only on conversions (CPA model)\n- **Network**: Tracks conversions (ShareASale, Impact, CJ Affiliate)\n- Commission models: Revenue share (10-30%), CPA (fixed ₹ per sale), Hybrid`,
        examples: [{ title: 'Influencer brief template', language: 'text', code: `CAMPAIGN BRIEF — CareerBoost × [Influencer Name]\n\nObjective: Drive course sign-ups (trackable via promo code CB20)\nTarget audience: Final year engineering students, tier 1-2 cities\n\nContent requirements:\n• 1 × Instagram Reel (60-90s) — organic feel, NOT ad-feel\n• 1 × Instagram Story (swipe-up/link sticker)\n• Creator has full creative control\n• Must disclose: #ad or #sponsored\n\nKey messages (weave in naturally):\n• "AI skills gap" — companies are hiring AI-ready graduates\n• Platform USP: AI mock interview + personalised roadmap\n\nDeliverables & timeline:\n• Draft for review: [DATE]\n• Go-live: [DATE]\n• Post insights (screenshot) within 48hrs of posting`, explanation: 'Good briefs are specific about goals and key messages but give creators freedom. Over-scripting kills authenticity.' }],
        keyPoints: ['Micro-influencers (10K-100K) deliver higher engagement rates and better ROI than mega-influencers for direct response campaigns', 'Always use unique UTM parameters or promo codes per influencer for attribution — vanity metrics (likes) ≠ business results', 'FTC/ASCI disclosure (#ad, #sponsored) is legally required in India and the US — non-compliance risks brand reputation']
      },
      evaluate: { questions: [{ question: 'Why do micro-influencers often outperform mega-influencers for ROI?', options: ['They are cheaper per post', 'Their audiences are smaller but more engaged and trusting — higher conversion rates', 'They post more frequently', 'Mega-influencers are unavailable'], correctIndex: 1, explanation: 'Micro-influencers (10K-100K) have niche, highly engaged audiences. Their recommendations feel more authentic, driving better conversions.' }, { question: 'In affiliate marketing, the advertiser pays the affiliate:', options: ['Upfront for exposure', 'Only when a conversion (sale/lead) occurs — CPA model', 'Per impressions', 'Monthly retainer'], correctIndex: 1, explanation: 'Affiliate marketing is performance-based. Advertisers only pay for results (sales/leads) — no risk for impressions/clicks.' }, { question: 'UTM parameters in influencer links are used for:', options: ['SEO improvement', 'Tracking which influencer/campaign drove traffic and conversions', 'Blocking ad fraud', 'Improving page speed'], correctIndex: 1, explanation: 'UTM parameters append tracking data to URLs (source, medium, campaign) — enabling accurate attribution per influencer.' }] }
    },
    'Brand Building & Storytelling': {
      understand: {
        theory: `# Brand Building & Storytelling\n## What Is a Brand?\nA brand is the sum of associations, perceptions, and feelings people have about a company. Brand equity = the premium customers pay because of the brand.\n\n## Brand Identity Components (Kapferer Prism)\n1. **Physique**: Visual identity, logo, product design\n2. **Personality**: Character traits (bold, friendly, authoritative)\n3. **Culture**: Company values and beliefs\n4. **Relationship**: Customer-brand dynamic (premium service, community)\n5. **Reflection**: The customer it portrays (young, professional, creative)\n6. **Self-Image**: How users feel about themselves using the brand\n\n## Storytelling Framework (ABT — And, But, Therefore)\n"[Setup AND context], BUT [conflict/problem], THEREFORE [resolution]."\n\nExample: "Millions of students graduate every year AND have good GPAs, BUT they lack the skills companies actually need, THEREFORE CareerBoost builds real-world skills through AI-powered practice."\n\n## Brand Archetypes (12 universal)\nHero | Sage | Creator | Explorer | Caregiver | Innocent | Jester | Lover | Outlaw | Ruler | Everyman | Magician`,
        examples: [{ title: 'Apple brand positioning analysis', language: 'text', code: `APPLE BRAND PRISM:\nPhysique: Clean, minimalist, premium materials, white/silver\nPersonality: Innovative, simple, cool, rebel against complexity\nCulture: "Think Different" — creativity, craftsmanship, privacy\nRelationship: Premium, aspirational, loyal community\nReflection: The creative, the curious, the non-conformist\nSelf-Image: "I am creative, smart, I value quality"\n\nArchetype: CREATOR (making things real) + hint of OUTLAW\n\nABT Story:\n"Technology should be accessible to everyone AND computers were\nbeing built for engineers, BUT human creativity needed better\ntools, THEREFORE Apple builds devices that feel like extensions\nof the human mind."`, explanation: 'Prism analysis reveals why Apple\'s brand is coherent across all touchpoints — every decision traces back to these 6 elements.' }],
        keyPoints: ['Brand is what people say about you when you are not in the room (Jeff Bezos). Advertising shapes it; customer experience defines it', 'ABT (And-But-Therefore) structure is the DNA of great brand stories — conflict is essential; problem-solution creates memorability', 'Brand archetypes create instant psychological resonance — choose one primary archetype and stay consistent across all communications']
      },
      evaluate: { questions: [{ question: 'The ABT storytelling framework stands for:', options: ['Awareness, Brand, Transaction', 'And (setup), But (conflict), Therefore (resolution) — the structure of compelling stories', 'Attention, Build, Trust', 'Asset, Budget, Timeline'], correctIndex: 1, explanation: 'ABT is the DNA of all great stories. "And" sets up the world, "But" introduces the problem, "Therefore" provides the resolution.' }, { question: 'Brand equity is best described as:', options: ['The total revenue from brand advertising', 'The premium customers pay because of the brand\'s reputation and associations', 'The value of brand assets on the balance sheet', 'The number of brand followers on social media'], correctIndex: 1, explanation: 'Brand equity is the commercial value derived from brand perception. Customers pay MORE for branded products vs. generics.' }, { question: 'Kapferer\'s Brand Identity Prism has how many facets?', options: ['3', '4', '6', '8'], correctIndex: 2, explanation: 'The prism has 6 facets: Physique, Personality, Culture, Relationship, Reflection, and Self-Image.' }] }
    },
    'Product Launch Strategy': {
      understand: {
        theory: `# Product Launch Strategy\n## Launch Framework: SOSTAC\n- **S**ituation analysis (where are we?)\n- **O**bjectives (where do we want to be?)\n- **S**trategy (how do we get there?)\n- **T**actics (what specifically?)\n- **A**ction (who does what, when?)\n- **C**ontrol (how do we measure?)\n\n## Launch Phases\n**Pre-launch (4-8 weeks before)**:\n- Build waitlist/interest list (email capture)\n- Content seeding (blog, social, PR)\n- Influencer/partner briefing\n- Beta user feedback and testimonial collection\n\n**Launch week**:\n- Hero announcement (PR + social)\n- Email blast to waitlist\n- Paid ads turn on\n- Real-time social monitoring\n\n**Post-launch (30 days)**:\n- Onboarding campaign\n- Collect reviews/testimonials\n- Retargeting non-converters\n- Iteration based on first-user feedback`,
        examples: [{ title: 'Product Hunt launch playbook', language: 'text', code: `PRODUCT HUNT LAUNCH CHECKLIST:\n\nT-7 days:\n□ Schedule post for 12:01 AM PT (Tuesday = best day)\n□ Prepare assets: tagline, gallery, first comment\n□ Identify 50 supporters to upvote at 9 AM PT\n\nLaunch day:\n08:00 PT: Email sequence to user base\n09:00 PT: Notify supporters to upvote\n10:00 PT: LinkedIn post from founder\n12:00 PT: Monitor comments; respond to every comment\n16:00 PT: Mid-day update post on social\n\nKPIs:\n• #1 Product of the Day = 10K+ upvotes typically\n• Traffic spike: 10-30K visitors in 24hrs\n• Conversions: 1-3% of visitors sign up`, explanation: 'Product Hunt launches are community-driven. Timing (12:01 AM PT) + prepared supporters + active founder engagement are the formula.' }],
        keyPoints: ['Pre-launch waitlist building is the most underused strategy — 1,000 email subscribers before launch 10× conversion vs. cold traffic', 'Product Hunt, AppSumo, and BetaList are free launch platforms that can generate 10K+ visitors and media coverage', 'The first 90 days of user experience determine word-of-mouth. A launch without retention strategy = leaky bucket']
      },
      evaluate: { questions: [{ question: 'Why is pre-launch waitlist building critical?', options: ['It builds SEO authority', 'It creates a warm, high-intent audience for day-1 launch, dramatically improving conversion rates', 'It is required by App Store', 'It replaces paid advertising'], correctIndex: 1, explanation: 'Waitlist subscribers opted in because they are interested — they convert far better than cold ad traffic on launch day.' }, { question: 'In the SOSTAC framework, "Control" refers to:', options: ['Management oversight', 'How success will be measured and monitored against objectives', 'Controlling ad spend', 'Product quality control'], correctIndex: 1, explanation: 'Control = metrics and KPIs to track progress and feedback loops to adjust strategy based on results.' }, { question: 'What is the #1 factor in a successful Product Hunt launch?', options: ['Having a premium product', 'Large ad budget', 'Community preparation — supporters who upvote at the optimal time (9 AM PT)', 'Best UI design'], correctIndex: 2, explanation: 'Product Hunt\'s algorithm heavily weights early upvotes. Coordinating supporters to upvote at launch drives visibility to the top.' }] }
    },
    'E-Commerce & D2C Strategy': {
      understand: {
        theory: `# E-Commerce & D2C Strategy\n## D2C vs. Marketplace\n| | D2C (Own Website) | Marketplace (Amazon/Flipkart) |\n|---|---|---|\n| Customer data | Full ownership | No access |\n| Margin | Higher (no platform cut) | Lower (15-25% fee) |\n| Discovery | Difficult (requires marketing) | Built-in traffic |\n| Brand control | Complete | Limited |\n| Trust | Build from scratch | Marketplace trust |\n\n## D2C Unit Economics\n- **AOV** (Average Order Value): Total Revenue / Number of Orders\n- **Repeat Rate**: % customers who buy again\n- **LTV** = AOV × Purchase Frequency × Customer Lifespan\n- **CAC** = Total Marketing Spend / New Customers\n- **Payback Period** = CAC / Monthly Gross Profit per Customer\n\n## Conversion Rate Benchmarks\n- Average e-commerce CVR: 2-3%\n- High-performing: 5-8%\n- Mobile vs. Desktop: Mobile has 30% lower CVR typically`,
        examples: [{ title: 'D2C LTV:CAC model', language: 'text', code: `SKINCARE D2C BRAND:\n\nAOV: ₹1,200\nPurchase Frequency: 4× per year\nAvg. Customer Lifespan: 2 years\nGross Margin: 60%\n\nLTV = ₹1,200 × 4 × 2 = ₹9,600\nLTV with margin = ₹9,600 × 0.60 = ₹5,760\n\nCAC (from Meta/Google): ₹1,800\nLTV:CAC = ₹5,760 / ₹1,800 = 3.2× ✓\n\nPayback Period = ₹1,800 / (₹1,200 × 0.60 / 3) = 7.5 months\n\nActions to improve:\n• Subscriptions → increase purchase frequency\n• Bundles → increase AOV\n• Loyalty programme → increase lifespan`, explanation: 'LTV:CAC > 3× is the baseline for a healthy D2C brand. Improving any LTV component (AOV, frequency, lifespan) compounds significantly.' }],
        keyPoints: ['D2C wins with customer data ownership and higher margins — but requires significant CAC investment to build direct traffic', 'Subscriptions are the most powerful D2C model — predictable revenue, higher LTV, lower churn (inertia effect)', 'Mobile checkout friction kills D2C conversions — mobile-first design, Apple/Google Pay, and minimal form fields are table stakes']
      },
      evaluate: { questions: [{ question: 'LTV (Lifetime Value) formula is:', options: ['Revenue / Customers', 'AOV × Purchase Frequency × Customer Lifespan', 'Total Revenue / CAC', 'Monthly revenue × 12'], correctIndex: 1, explanation: 'LTV = Average Order Value × how often they buy × how long they remain a customer. Multiply by gross margin for true LTV.' }, { question: 'The biggest D2C advantage over marketplace selling is:', options: ['Lower price for customers', 'Full customer data ownership and higher margins without platform fees', 'Built-in traffic and discovery', 'Easier logistics'], correctIndex: 1, explanation: 'Owning customer relationships means you can email, retarget, and build loyalty — impossible with marketplace customers.' }, { question: 'Average e-commerce conversion rate is approximately:', options: ['10-15%', '5-8%', '2-3%', '0.5-1%'], correctIndex: 2, explanation: 'Industry average CVR is 2-3%. Optimised stores achieve 5-8%. Below 1% signals significant UX or targeting issues.' }] }
    },
  },
};
