export const CREATIVE_CONTENT: Record<string, Record<string, any>> = {
  'Creative Writing': {
    'Story Structure & Plot': {
      understand: {
        theory: `# Story Structure & Plot\nAll compelling stories follow structural patterns that create narrative momentum and emotional engagement.\n\n## The Three-Act Structure\n**Act 1 — Setup (25%)**: Introduce protagonist, world, and inciting incident\n- Ordinary world → Call to adventure → Threshold crossing\n\n**Act 2 — Confrontation (50%)**: Rising action, complications, midpoint reversal\n- Rising action → Midpoint → Complications → All-is-lost moment\n\n**Act 3 — Resolution (25%)**: Climax and resolution\n- Climax → Resolution → New normal\n\n## The Hero's Journey (Joseph Campbell)\nA deeper structural pattern underlying mythology and storytelling worldwide:\nOrdinary World → Call to Adventure → Refusal → Meeting Mentor → Crossing Threshold → Tests/Allies/Enemies → Ordeal → Reward → Road Back → Resurrection → Return with Elixir\n\n## Scene-Sequel Structure\n- **Scene**: Goal → Conflict → Disaster (setback)\n- **Sequel**: Reaction → Dilemma → Decision (leads to next goal)\n\nEvery scene should move the story forward AND increase the stakes.\n\n## Plot Devices\n- **Foreshadowing**: Hint at future events without revealing them\n- **Red herring**: Mislead reader intentionally\n- **Chekhov's Gun**: Introduced element must be used later\n- **Inciting incident**: Event that disrupts protagonist's ordinary world`,
        examples: [{ title: 'Three-act structure in a short story', language: 'text', code: `SHORT STORY: "The Interview" (1,500 words)\n\nACT 1 (375 words):\n• Ordinary world: Priya, 23, anxious fresh graduate\n  in her first real job interview suit\n• Inciting incident: She's given a coding problem\n  she's never seen before in front of 5 interviewers\n• Internal goal: Not to freeze. Not to disappoint her\n  parents who sacrificed to send her to college.\n\nACT 2 (750 words):\n• Rising action: She starts — gets stuck — starts again\n  Interviewer hints. She misunderstands.\n• Midpoint: She realises she's over-thinking it\n  and admits "I don't know this yet — but here's\n  how I'd approach figuring it out"\n• Complication: Interviewer asks a follow-up that\n  goes deeper — does she really understand?\n• All-is-lost: She gives a wrong answer with confidence\n\nACT 3 (375 words):\n• Climax: Interviewer smiles — "That wrong answer\n  showed better thinking than the right answer"\n• Resolution: She gets the job not for her knowledge\n  but for her thinking approach\n• New normal: She realises competence ≠ confidence`, explanation: 'Three-act structure is a tool, not a rigid rule. Use it to check: Is there a clear inciting incident? Does the midpoint change direction? Is there genuine conflict?' }],
        keyPoints: ['Every scene needs a goal, conflict, and outcome — scenes without conflict are mere description and should be cut or combined', 'The inciting incident should force the protagonist into action — it disrupts the ordinary world and makes the story\'s central question impossible to ignore', 'Act 2\'s midpoint is often under-used — it should create a major reversal or revelation that pivots the second half of the story in a new direction']
      },
      evaluate: { questions: [{ question: 'Chekhov\'s Gun in storytelling means:', options: ['Stories should involve weapons', 'Every introduced element should serve the story — if you show a gun in Act 1, it must fire by Act 3', 'Characters should be named after weapons', 'Plot twists should be unexpected'], correctIndex: 1, explanation: 'Chekhov\'s rule: "If in the first act you have hung a pistol on the wall, then in the following one it should be fired." Don\'t introduce elements that don\'t serve the story.' }, { question: 'The "All-is-lost" moment in three-act structure occurs:', options: ['At the very beginning', 'In Act 1 after the inciting incident', 'Near the end of Act 2 — when the protagonist appears furthest from their goal', 'After the climax'], correctIndex: 2, explanation: 'All-is-lost (also called "dark night of the soul") is the lowest point before the Act 3 climax. Creates maximum tension and makes the eventual victory meaningful.' }, { question: 'A scene without conflict is problematic because:', options: ['Conflict is required by publishers', 'Scenes exist to advance plot — conflict creates the obstacle/setback that makes progress difficult and keeps readers engaged', 'Readers dislike peaceful scenes', 'It breaks copyright rules'], correctIndex: 1, explanation: 'Goal + conflict + setback = a functional scene. Description without conflict is backstory or texture — valuable occasionally, but not as a full scene.' }] }
    },
    'Character Development': {
      understand: {
        theory: `# Character Development\nCompelling characters are the heart of memorable fiction. Readers follow characters, not plots.\n\n## Character Dimensions\n**Outer layer** — Physical appearance, mannerisms, speech pattern, occupation\n**Inner layer** — Beliefs, fears, desires, wounds (backstory)\n**Deepest layer** — Worldview: how they interpret everything that happens to them\n\n## The Character Triangle\n- **Want**: What they consciously pursue (external goal)\n- **Need**: What they unconsciously require for growth (internal)\n- **Fear**: What they avoid that keeps them from their need\n\nGreat stories force the protagonist to confront their deepest fear to get what they truly need — and this often costs them what they thought they wanted.\n\n## Character Wound\nThe defining experience from the past that shaped the character's core beliefs about themselves or the world. The wound creates behaviour patterns and defensive mechanisms.\n\nExample: A character abandoned in childhood (wound) → believes they are unlovable → pushes people away before they can leave → struggles to trust → sabotages relationships (behaviour)\n\n## Character Arc Types\n- **Positive arc**: Character changes for the better (overcomes wound)\n- **Negative arc**: Character fails to change or changes for the worse\n- **Flat arc**: Character's worldview is correct; they change the world around them`,
        examples: [{ title: 'Character profile development', language: 'text', code: `CHARACTER PROFILE: ARJUN MEHTA\n\nOUTER LAYER:\n• 26-year-old software engineer at startup\n• Speaks in precise, technical language\n  even in personal conversations\n• Sits with back to the wall in restaurants\n• Never misses a deadline — ever\n\nINNER LAYER:\n• WANT: To get the lead developer role (promotion)\n• NEED: To trust others and delegate\n• FEAR: That if he's not indispensable, he's worthless\n\nWOUND:\n• Father lost his job when Arjun was 12\n  "If I'm not perfect, everything falls apart"\n\nBELIEF SYSTEM:\n• Control = safety. Vulnerability = failure.\n• "People leave when things get hard.\n  I can only rely on myself."\n\nSTORY IMPLICATION:\n• His control-freak behaviour will cause the team\n  to resent him (external conflict)\n• He'll have to delegate to save the project\n  (confronting his deepest fear)\n• Cost: vulnerability, trust — finally achieves\n  connection he's been avoiding`, explanation: 'Characters who behave consistently with their wound, beliefs, and fears feel real. Behaviour that contradicts the wound without explanation breaks reader immersion.' }],
        keyPoints: ['The most powerful character moment is when WANT conflicts with NEED — when getting what they want would prevent what they need for genuine growth', 'Character wound should explain behaviour without excusing it — readers understand why a character acts destructively even when they disapprove', 'Show character through choices under pressure — what a character does when something costs them something reveals who they truly are more than description']
      },
      evaluate: { questions: [{ question: 'A character\'s "need" in the want/need/fear triangle refers to:', options: ['What the character literally needs to survive', 'The conscious goal driving the plot', 'What the character unconsciously requires for genuine emotional or psychological growth', 'The character\'s backstory'], correctIndex: 2, explanation: 'Need = the internal change the character must make. Want = external goal. The drama comes from the tension between want (what they think they need) and need (what they actually need).' }, { question: 'A "character wound" is:', options: ['Physical injury to the character', 'A defining past experience that shaped the character\'s beliefs, fears, and defensive behaviour patterns', 'The antagonist\'s attack on the protagonist', 'A weakness in the character that must be trained away'], correctIndex: 1, explanation: 'Character wound is the foundational trauma or formative experience that explains why the character thinks and behaves as they do — creates consistency and psychological depth.' }, { question: 'Showing character through choices under pressure is more effective than description because:', options: ['Description is not allowed in modern fiction', 'Actions under pressure reveal true values — what a character does when something costs them something is more authentic than what the narrator says about them', 'Readers skip descriptive passages', 'Action scenes generate more word count'], correctIndex: 1, explanation: '"Show don\'t tell" applied to character: telling "she was brave" is weaker than showing her doing something brave despite fear. Behaviour under pressure reveals character authentically.' }] }
    },
  },
  'Content Creation & YouTube': {
    'Niche & Audience Research': {
      understand: {
        theory: `# Niche & Audience Research for YouTube/Content\nContent that tries to speak to everyone speaks to no one. Niche clarity is the foundation of audience growth.\n\n## The Niche Equation\nPassion + Expertise + Audience Demand = Viable Content Niche\n\n## Niche Selection Framework\n1. **Passion test**: Can you talk about this for 2 years without burning out?\n2. **Expertise test**: Do you know or can you learn more than 90% of your target audience?\n3. **Market test**: Are people already searching for this content? (YouTube Search, Google Trends)\n4. **Competition test**: Is there room for a new creator? (sub-saturated niches are better)\n\n## Audience Research Methods\n**YouTube Search Autocomplete**: Type your topic → see what people search\n**vidIQ / TubeBuddy**: Keyword research tools — volume vs. competition\n**Comment Mining**: Read top channel comments — what do viewers ask, want, or complain about?\n**Reddit/Quora**: What questions does your target audience have in online communities?\n**Surveys**: Ask existing audience what they want more of\n\n## Creator-Market Fit\nLike Product-Market Fit, you need a match between:\n- Your content style and your audience's preference\n- Your posting frequency and platform algorithm\n- Your niche specificity and searchable volume`,
        examples: [{ title: 'Niche validation process', language: 'text', code: `NICHE VALIDATION: "Finance for Indian College Students"\n\nSTEP 1: PASSION + EXPERTISE CHECK\n• Genuinely interested in personal finance: Yes\n• Knows more than target audience: Yes (works in BFSI sector)\n• Can sustain for 2+ years: Yes\n\nSTEP 2: SEARCH DEMAND (vidIQ)\nKeyword: "How to invest in India college student"\n• Monthly searches: 18,000\n• Competition: Low-Medium\n→ VIABLE search demand ✓\n\nSTEP 3: COMPETITION ANALYSIS\nTop channels in this space:\n• Large channels (500K+): General finance — not India-specific for students\n• Medium channels: Complex language, not beginner-friendly\n• GAP: Beginner-friendly, India-specific, student-focused\n→ DIFFERENTIATION OPPORTUNITY ✓\n\nSTEP 4: CONTENT PILLAR PLAN\n1. SIP 101 (How to start investing with ₹500)\n2. Income tax for students filing first return\n3. CIBIL score — build it before you need it\n4. Credit card dos and don'ts for college students\n\nSUB-NICHE: Financial literacy for Indian 18-25 year olds\nTagline: "Finance advice your CA uncle should have given you"`, explanation: 'A validated niche has real search demand + a gap in existing content + your unique angle. The tagline crystallises the value proposition in one memorable sentence.' }],
        keyPoints: ['Niche down further than feels comfortable — "finance for Indian college students" beats "finance" every time for algorithm discoverability and community loyalty', 'Comment mining is the highest-value research activity — creators who read comments understand their audience better than those who only look at analytics', 'Content-market fit is visible in watch time and retention — 50%+ average view duration on 10-minute videos signals strong alignment between content and audience']
      },
      evaluate: { questions: [{ question: 'The niche validation equation combines:', options: ['Views + Subscribers + Revenue', 'Passion + Expertise + Audience Demand = Viable niche', 'Content quality + Posting frequency + SEO', 'Brand deals + AdSense + Merchandise'], correctIndex: 1, explanation: 'Passion sustains long-term creation. Expertise creates genuine value. Audience demand ensures people actually search for it. All three are required — two out of three creates problems.' }, { question: 'Comment mining for YouTube audience research means:', options: ['Buying comments to boost engagement', 'Reading comments on your channel and top competitor channels to discover viewer questions, pain points, and content requests', 'Removing negative comments', 'Using AI to generate comments'], correctIndex: 1, explanation: 'Comment mining: systematically read comments on your own and competitor videos to discover what your audience wants, struggles with, and asks — this directly informs content ideas.' }, { question: 'Why should new creators "niche down" rather than cover broad topics?', options: ['Broad topics are copyrighted', 'Specific niches face less competition, attract more dedicated audiences, and are better rewarded by YouTube\'s recommendation algorithm for relevant watch sessions', 'YouTube penalises broad channels', 'Narrow channels earn more from AdSense'], correctIndex: 1, explanation: 'Algorithm favours watch sessions where viewers watch multiple videos in sequence. Specific niches create viewers who binge all your content — signalling strong relevance to YouTube.' }] }
    },
    'Scripting & Storyboarding': {
      understand: {
        theory: `# Scripting & Storyboarding for Video Content\n## Why Script (Even If You Don't Read It)\nScripting forces clarity of thought before filming. Even creators who speak naturally on camera should have a structured script to avoid rambling.\n\n## AIDA Framework for Video Scripts\n- **A**ttention (Hook, 0-15 sec): Why should they keep watching?\n- **I**nterest (Setup, 15-60 sec): Frame the problem/promise\n- **D**esire (Body, 60% of video): Deliver the value\n- **A**ction (CTA, last 30 sec): What should they do next?\n\n## The Hook Formula (First 15 seconds)\nOptions:\n1. **Bold claim**: "Most people get this completely wrong..."\n2. **Counterintuitive statement**: "The best career advice is to stop following your passion"\n3. **Story**: "Six months ago, I was broke and unemployed. Here's what changed..."\n4. **Question**: "Why do 95% of startups fail in year one?"\n\n## Storyboarding\nVisual planning of shots before filming.\n- **Shot types**: Wide (context), medium (action), close-up (detail/emotion)\n- **B-roll**: Supplementary footage that illustrates what narrator is saying\n- **Transitions**: Match cut, J-cut, L-cut for professional feel\n\n## Video Structure Template\nHook (15s) → Problem setup (30s) → Promise/benefit (15s) → Body (80% of video) → CTA (30s)`,
        examples: [{ title: 'Hook writing for education video', language: 'text', code: `VIDEO TITLE: "Why Your Resume Gets Rejected in 6 Seconds"\n\nHOOK OPTIONS (pick strongest):\n\nOPTION A (Bold claim):\n"Your resume is being rejected in 6 seconds.\nNot because you're unqualified —\nbecause it fails a test you never knew existed.\nI'll show you exactly how recruiters screen\n100 resumes in one hour."\n\nOPTION B (Story):\n"I used to wonder why I got zero callbacks.\nMy GPA was 8.2. My internships were solid.\nThen a recruiter showed me how she screens resumes.\nI was horrified. And then I completely rewrote mine."\n\nOPTION C (Question):\n"If a recruiter spends 6 seconds on your resume,\nwhat do they actually see?\nI'll show you the exact eye-tracking research —\nand the 3 things that make them stop scrolling."\n\nBEST PRACTICE:\n• Test all 3 as different thumbnails/titles (A/B test)\n• Hook must match the thumbnail promise\n• Never mislead — retention drops and YouTube penalises\n• Deliver exactly what the hook promises, quickly`, explanation: 'Hooks are the highest-leverage writing in video creation. A great hook on a mediocre video outperforms a mediocre hook on a great video every time.' }],
        keyPoints: ['The first 30 seconds determine if viewers watch the rest — invest disproportionate time scripting the hook and setup', 'B-roll transforms a talking-head video into engaging content — plan B-roll shots while scripting (write "[SHOW: screen recording of resume]" in script)', 'Call to action (CTA) should ask for one specific action only — "like, subscribe, comment, and share" dilutes all of them. Pick the metric that matters most.']
      },
      evaluate: { questions: [{ question: 'AIDA in video scripting stands for:', options: ['Audio, Image, Design, Animation', 'Attention, Interest, Desire, Action — a framework for structuring persuasive video content', 'Audience, Intent, Data, Analytics', 'Algorithm, Impressions, Duration, Audience'], correctIndex: 1, explanation: 'AIDA: Hook grabs Attention; setup creates Interest; value delivery creates Desire; CTA prompts Action. This structure is used in advertising, video, and sales copy.' }, { question: 'B-roll in video production is:', options: ['The backup recording in case main footage fails', 'Supplementary footage that visually illustrates what the narrator is saying — adds visual interest beyond talking head', 'A second camera angle on the presenter', 'Background music'], correctIndex: 1, explanation: 'B-roll = cutaway footage. While narrator explains "opening a Zerodha account," B-roll shows the actual Zerodha interface. Transforms talking-head into professional, engaging content.' }, { question: 'Why should a CTA (Call to Action) ask for only one action?', options: ['YouTube limits CTAs to one per video', 'Multiple CTAs (like+subscribe+comment+share) dilute attention — people do nothing when asked to do everything at once', 'Multiple CTAs violate platform terms', 'Each action requires a different video'], correctIndex: 1, explanation: 'Paradox of choice: the more actions you request, the less likely viewers are to take any. Identify your ONE priority metric and ask for that specifically and clearly.' }] }
    },
  },
  'Photography Mastery': {
    'Camera Fundamentals (Exposure Triangle)': {
      understand: {
        theory: `# Camera Fundamentals — The Exposure Triangle\nThe Exposure Triangle consists of three interdependent settings that together determine the brightness and character of a photograph.\n\n## 1. Aperture (f-stop)\nThe opening in the lens that allows light through.\n- **f/1.4 (wide)**: More light; shallow depth of field (blurry background)\n- **f/16 (narrow)**: Less light; deep depth of field (everything sharp)\n- Lower f-number = wider aperture = more light = shallower DOF\n\nCreative use: Portrait photography uses f/1.8-2.8 for background blur (bokeh)\n\n## 2. Shutter Speed\nDuration the sensor is exposed to light.\n- **1/1000s (fast)**: Freezes motion; sharp action shots\n- **1/30s (slow)**: Motion blur; smooth water, light trails\n- Hand-holding minimum: 1/focal length (1/50mm lens = 1/50s minimum)\n\nCreative use: Long exposure (2-30 seconds) for silky waterfalls, star trails\n\n## 3. ISO\nSensor's sensitivity to light.\n- **ISO 100**: Clean, low noise; ideal outdoors\n- **ISO 3200+**: More sensitive; more digital noise/grain\n\n## Reciprocity: The Balance\nChanging one setting requires compensating with another:\n- Faster shutter → less light → open aperture or raise ISO\n- Narrower aperture → less light → slow shutter or raise ISO`,
        examples: [{ title: 'Exposure settings for common scenarios', language: 'text', code: `SCENARIO-BASED EXPOSURE SETTINGS:\n\n1. OUTDOOR PORTRAIT (sunny day)\n   Goal: Sharp subject, blurred background\n   • Aperture: f/2.0 (wide — creates bokeh)\n   • ISO: 100 (clean, bright light available)\n   • Shutter: 1/400s (sunny → need to reduce exposure)\n   • Tip: Position subject with sun behind/to side\n\n2. SPORTS PHOTOGRAPHY\n   Goal: Freeze fast motion\n   • Aperture: f/4 (some background blur)\n   • ISO: 1600 (indoor gym or evening)\n   • Shutter: 1/1000s (freeze motion)\n   • Tip: Use continuous autofocus (AI Servo/AF-C)\n\n3. NIGHT CITY SCENE (tripod)\n   Goal: Sharp, detailed city lights\n   • Aperture: f/8 (sharp, light starburst effect)\n   • ISO: 200 (low for clean image)\n   • Shutter: 10-30 seconds (long exposure)\n   • Tip: Use remote shutter release or 2-sec timer\n\n4. INDOOR AVAILABLE LIGHT\n   Goal: Natural portrait without flash\n   • Aperture: f/2.8 (wide for light)\n   • ISO: 3200 (accept some grain)\n   • Shutter: 1/100s (avoid camera shake)`, explanation: 'The "correct" exposure is always a creative choice — the same light can create different images depending on the story you want to tell.' }],
        keyPoints: ['The exposure triangle is a balance — changing one requires compensating with another to maintain correct exposure. Practice in Manual mode to internalise these relationships', 'Aperture controls depth of field — NOT just exposure. This is the primary creative tool for portrait photography (shallow DOF) vs. landscape (deep DOF)', 'ISO is the last resort — raise it only when aperture and shutter speed have been optimised. Digital noise from high ISO degrades image quality']
      },
      evaluate: { questions: [{ question: 'f/1.8 aperture compared to f/16 will produce:', options: ['Less light and more depth of field', 'More light and shallower depth of field (more background blur)', 'The same depth of field with less noise', 'Faster shutter speed automatically'], correctIndex: 1, explanation: 'Lower f-number = wider aperture = more light = shallower DOF. f/1.8 creates background blur (bokeh) ideal for portraits. f/16 keeps everything in focus — useful for landscapes.' }, { question: 'A shutter speed of 1/1000s compared to 1/30s will:', options: ['Create more motion blur', 'Freeze fast-moving subjects but let in less light', 'Let in more light', 'Increase depth of field'], correctIndex: 1, explanation: 'Fast shutter (1/1000s) = short exposure = freezes motion (sports, birds). Slow shutter (1/30s) = long exposure = motion blur (waterfalls, light trails). Fast shutter = less total light.' }, { question: 'High ISO (e.g., ISO 6400) is used when:', options: ['Shooting outdoors in bright sunlight', 'Photographing landscapes at dawn', 'Shooting in low light and fast shutter speed or small aperture is required, at the cost of increased digital noise', 'Maximum image quality is needed'], correctIndex: 2, explanation: 'High ISO amplifies sensor signal — enables shooting in low light but introduces noise/grain. Use ISO 100-400 for best quality; ISO 3200+ only when necessary for correct exposure.' }] }
    },
    'Composition Rules': {
      understand: {
        theory: `# Photography Composition\nComposition is how you arrange elements within the frame. Technical exposure matters, but composition determines visual impact.\n\n## Rule of Thirds\nDivide frame into 3×3 grid. Place key subjects and horizons on grid lines or at their intersections (power points) — not centred.\n\n## Leading Lines\nUse natural lines (roads, rivers, fences, paths, shadows) to draw the viewer's eye toward the subject.\n\n## Framing\nUse natural elements (archways, doorways, trees, windows) to frame the subject — adds depth and focus.\n\n## Depth & Layers\nForeground + midground + background creates three-dimensionality in a 2D image.\n- Low angle shot: emphasises foreground dramatically\n\n## Negative Space\nEmpty space around the subject. Gives the subject "room to breathe" and creates visual calm. Used extensively in minimalist and product photography.\n\n## Symmetry & Patterns\nReflections, architectural symmetry, repeating patterns create visual interest.\nBreaking a pattern (one different element in a grid) draws the eye.\n\n## Golden Ratio\nMore mathematically precise than rule of thirds — spiral composition that mirrors the Fibonacci sequence. Used in classic photography and art.`,
        examples: [{ title: 'Applying multiple composition techniques', language: 'text', code: `SCENE: Sunrise at a beach with a lone fisherman\n\nCOMPOSITION ANALYSIS:\n\nRULE OF THIRDS:\n• Horizon: Place at bottom 1/3 line (gives sky prominence)\n• Fisherman: Position on left vertical line\n• Not centre — creates visual tension and interest\n\nLEADING LINES:\n• Shoreline leads eye from bottom-right\n  toward the fisherman\n• Reflections create horizontal leading lines\n\nLAYERS:\n• Foreground: Wet sand reflections\n• Midground: Fisherman silhouette\n• Background: Coloured sunrise sky\n\nNEGATIVE SPACE:\n• Large open sky above creates solitude feeling\n• Matches emotional intent — isolation + peace\n\nCAMERA SETTINGS:\n• Golden hour: f/8, ISO 100, 1/200s\n• Expose for sky (fisherman becomes silhouette)\n  OR bracket and HDR merge both exposures\n\nSTORY TOLD:\nSolitary figure against vast natural world —\ncomposition choices CREATE the emotional meaning`, explanation: 'Composition is storytelling — every choice (where to place horizon, whether to include foreground, how much negative space) communicates something to the viewer.' }],
        keyPoints: ['Rule of thirds is a starting point, not a rule — break it intentionally for specific effects (centred symmetry can be powerful)', 'Leading lines are the most underused composition tool — they create visual flow and invite the eye into the image', 'The best composition often requires physically moving (lower, higher, left, right) before touching any camera settings — feet are the first zoom lens']
      },
      evaluate: { questions: [{ question: 'The Rule of Thirds in photography suggests:', options: ['Always crop images to 3:3 ratio', 'Dividing the frame into a 3×3 grid and placing key subjects on the grid lines or intersections rather than dead centre', 'Using three different light sources', 'Taking three photos of every subject'], correctIndex: 1, explanation: 'Rule of thirds: 9-grid placement of subjects off-centre creates visual tension and interest. The four intersection points are "power points" — most visually compelling positions.' }, { question: 'Negative space in photography is used to:', options: ['Represent emptiness in the subject\'s life', 'Create a dark exposure', 'Provide visual breathing room around the subject — adding calm, emphasis, and minimalist aesthetic', 'Fill the frame completely'], correctIndex: 2, explanation: 'Negative space is the empty area around the subject. It gives the subject visual prominence, communicates scale and isolation, and creates minimalist impact.' }, { question: 'Leading lines in composition serve to:', options: ['Indicate where the horizon should be', 'Naturally guide the viewer\'s eye through the image toward the main subject', 'Show the direction the subject is moving', 'Create symmetry in the frame'], correctIndex: 1, explanation: 'Leading lines (roads, rivers, fences, shadows) create visual pathways that draw the viewer\'s eye toward the subject. Extremely powerful for adding depth and directing attention.' }] }
    },
  },
  'Game Design & Development': {
    'Game Design Document (GDD)': {
      understand: {
        theory: `# Game Design Document (GDD)\nA Game Design Document is the blueprint for a game — the single source of truth for the entire development team.\n\n## Why GDDs Matter\n- Aligns designers, developers, artists, and audio teams\n- Prevents scope creep (adding features mid-development)\n- Documents decisions and rationale\n- Reference for QA testing\n\n## GDD Structure\n**1. Game Overview**\n- Title, Genre, Platform, Target Audience\n- Elevator pitch (2-sentence description)\n- Core experience statement: "The player will feel..."\n\n**2. Core Gameplay**\n- Core loop (the repeated action cycle)\n- Player goal (win condition)\n- Challenge/obstacles\n\n**3. Mechanics**\n- Movement, interaction, combat/puzzle systems\n- Controls (per platform)\n\n**4. Narrative**\n- Story synopsis\n- Characters and motivations\n- World setting\n\n**5. Level/Content Design**\n- Level list with difficulty curve\n- Environment descriptions\n\n**6. Art Direction**\n- Visual style reference\n- Colour palette\n\n**7. Audio Design**\n- Music tone, SFX list\n\n**8. Technical**\n- Engine (Unity/Unreal/Godot)\n- Monetisation (F2P/premium/ads)`,
        examples: [{ title: 'GDD elevator pitch examples', language: 'text', code: `GDD: CORE EXPERIENCE STATEMENTS\n\nExample 1: Puzzle Platformer\nTitle: "Shimmer"\nPitch: "A visually stunning puzzle platformer\nwhere you manipulate light and shadow\nto navigate a shattered world."\n\nCore Experience:\n"The player will feel clever and visually rewarded\nwhen they solve a puzzle by discovering the\nunexpected interaction between light mechanics."\n\nCore Loop:\n1. Enter room\n2. Observe light/shadow puzzle\n3. Experiment with light sources\n4. Discover solution\n5. Feel rewarded + advance\n\n---\nExample 2: Mobile Strategy\nTitle: "Bazaar Wars"\nPitch: "A fast-paced trade-and-battle strategy\ngame set in a fantasy Indian bazaar.\nBuild your stall empire and defend it."\n\nCore Experience:\n"The player will feel the satisfaction of a\ngrowing empire AND the excitement of\ndefending it against rivals."\n\nCore Loop:\n1. Buy resources cheaply (morning)\n2. Sell at peak price (afternoon)\n3. Invest profits in upgrades\n4. Defend from rival attack (evening)\n5. Grow stall → unlock new goods`, explanation: 'The core experience statement is the most important line in the GDD — every design decision is tested against it: "Does this make players feel [X]?"' }],
        keyPoints: ['GDD is a living document — update it as decisions change, but note what changed and why (version control)', 'The core loop (the repeated action cycle) must be fun by itself before building meta-game systems around it', 'Platform determines controls, session length, and monetisation — a PC core loop usually fails on mobile without complete redesign']
      },
      evaluate: { questions: [{ question: 'The "core loop" in a Game Design Document describes:', options: ['The tutorial level', 'The repeated cycle of actions a player takes in normal gameplay — must be engaging by itself', 'The monetisation model', 'The storyline narrative'], correctIndex: 1, explanation: 'Core loop = the fundamental repeated action cycle (e.g., explore → collect → fight → level up → repeat). It must be intrinsically rewarding — everything else builds on this foundation.' }, { question: 'Why is a "core experience statement" valuable in a GDD?', options: ['It summarises the budget', 'It provides a test for all design decisions — "Does this make players feel [X]?"', 'It is required by Apple App Store', 'It lists all game features'], correctIndex: 1, explanation: 'Core experience statement defines the emotional target. Every mechanic, art choice, and system is evaluated against it: "Does this create the feeling we want?" It prevents feature-driven (not experience-driven) design.' }, { question: 'Scope creep in game development refers to:', options: ['The game world being too small', 'Uncontrolled addition of features mid-development — causing delays, budget overruns, and often project failure', 'Player character being too powerful', 'Code performance issues'], correctIndex: 1, explanation: 'Scope creep is the #1 cause of indie game failures. Adding "just one more feature" mid-development exponentially increases complexity. GDD + strict scope control prevents this.' }] }
    },
  },
  'Music Theory & Production': {
    'Notes, Scales & Intervals': {
      understand: {
        theory: `# Notes, Scales & Intervals\nMusic theory provides the vocabulary and grammar for understanding and creating music.\n\n## The 12 Notes (Western Music)\nC, C#/Db, D, D#/Eb, E, F, F#/Gb, G, G#/Ab, A, A#/Bb, B\n(Then repeats — an octave higher)\n\n## Scales — The Building Blocks of Melody\n**Major scale (happy, bright)**:\nFormula: W W H W W W H (W = whole step, H = half step)\nC major: C D E F G A B C\n\n**Minor scale (sad, dark)**:\nFormula: W H W W H W W\nA minor: A B C D E F G A\nNote: A minor uses the same notes as C major — just starts differently (relative minor)\n\n**Pentatonic scale (used in pop/blues/rock)**:\n5-note scale; removes the "tension" notes; nearly any combination sounds good\nC major pentatonic: C D E G A\n\n## Intervals — Distance Between Notes\n| Interval | Semitones | Sound |\n|----------|-----------|-------|\n| Unison | 0 | Same note |\n| Minor 2nd | 1 | Tense/dissonant |\n| Major 3rd | 4 | Happy/bright |\n| Perfect 5th | 7 | Stable/powerful |\n| Octave | 12 | Same note, higher |`,
        examples: [{ title: 'Building scales in any key', language: 'text', code: `BUILDING A MAJOR SCALE FROM ANY ROOT NOTE:\n\nFormula: W W H W W W H\n(W = 2 semitones, H = 1 semitone)\n\nG MAJOR SCALE:\nG → A → B → C → D → E → F# → G\n  W    W    H    W    W    W    H\n\nCompare to keyboard:\nG  A  B  C  D  E  F# G\n|  |  |  |  |  |  |  |\nW  W  H  W  W  W  H\n\nNote: One sharp (F#) needed to maintain the formula\nKey signature of G major = 1 sharp (F#)\n\nPRACTICAL APPLICATION:\nC major pentatonic: C D E G A\n(Most beginner guitarists/producers start here)\n\nSCALE IN PRODUCTION:\n• Choose a scale for your track\n• All melody notes from this scale will "fit"\n• Chord roots from this scale create harmony\n• Trying notes outside = tension/dissonance\n  (use intentionally for effect, then resolve)`, explanation: 'The scale is the key (pun intended) to melodic composition. Once you know your scale, you have the palette — all notes within it work together harmoniously.' }],
        keyPoints: ['Every major key has a relative minor that shares the same notes — C major and A minor are the same notes, just starting from a different root', 'The pentatonic scale removes the two "tension" half-steps from the major scale — making it nearly impossible to hit a "wrong" note (why it\'s used in all folk and pop music worldwide)', 'Interval training (recognising distances by ear) is more valuable than memorising theory — enables real-time composition and ear-based music making']
      },
      evaluate: { questions: [{ question: 'The formula for building a major scale is:', options: ['H W W H W W W', 'W W H W W W H (Whole-Whole-Half-Whole-Whole-Whole-Half)', 'W H W W W H W', 'H H W W W W H'], correctIndex: 1, explanation: 'Major scale formula: W W H W W W H. Starting from any root note and applying this interval pattern gives you the major scale in that key.' }, { question: 'The C major pentatonic scale (C D E G A) differs from C major by:', options: ['Using only black keys', 'Removing the 4th (F) and 7th (B) notes — the two half-steps that create tension', 'Adding extra notes for richness', 'Using a different key signature'], correctIndex: 1, explanation: 'Pentatonic = 5 notes. Removes F and B from C major — the notes that create semitone tension intervals. Result: any note combination in the scale sounds consonant.' }, { question: 'A "relative minor" to a major key:', options: ['Is always a semitone lower', 'Is a completely different set of notes', 'Shares the same notes as the major key but starts on the 6th scale degree', 'Has the opposite scale formula'], correctIndex: 2, explanation: 'C major (C D E F G A B) → relative minor is A minor (A B C D E F G) — same 7 notes, different starting point. This is why they share the same key signature.' }] }
    },
  },
};
