export const DESIGN_CONTENT: Record<string, Record<string, any>> = {
  'UI/UX Design': {
    'Design Thinking': {
      understand: {
        theory: `# Design Thinking\nDesign thinking is a human-centred, iterative problem-solving process widely used in product and service design.\n\n## The Double Diamond Model\n**Diamond 1 — Problem (Discover + Define)**\n- **Discover**: User research — interviews, observations, surveys, analytics\n- **Define**: Synthesise findings → Problem statement, personas, journey maps\n\n**Diamond 2 — Solution (Develop + Deliver)**\n- **Develop**: Ideation (brainstorming, crazy 8s, analogous inspiration)\n- **Deliver**: Prototype → Test → Iterate → Launch\n\n## Key Tools\n**How Might We (HMW)**: Reframes problems as design opportunities\n"How might we help [USER] [ACHIEVE GOAL] so that [BENEFIT]?"\n\n**Affinity Mapping**: Cluster qualitative research insights into themes\n\n**Crazy 8s**: 8 ideas in 8 minutes — forces quantity over quality to break mental blocks\n\n## Design Thinking vs. Traditional Problem-Solving\n| Traditional | Design Thinking |\n|-------------|------------------|\n| Define solution first | Define problem first |\n| Expert-driven | User-driven |\n| Linear process | Iterative loops |\n| Avoid failure | Fail fast, learn fast |`,
        examples: [{ title: 'HMW statements from user research', language: 'text', code: `USER RESEARCH INSIGHT:\n"Students feel overwhelmed choosing a career path\nbecause there are too many options and no clear framework."\n\nHMW REFRAMES:\n❌ BAD HMW: "How might we build a dropdown menu?"\n   (too solution-specific — skips problem exploration)\n\n✓ GOOD HMWs:\n1. "How might we help students narrow career options\n   based on their unique strengths and interests?"\n2. "How might we make career exploration feel\n   exciting rather than anxiety-inducing?"\n3. "How might we connect students with people\n   who have the career they're considering?"\n4. "How might we help students take a career\n   decision step-by-step rather than all at once?"\n\nEach HMW opens a different design direction:\n#1 → Assessment tool\n#2 → Gamified exploration\n#3 → Mentorship matching\n#4 → Progressive decision framework`, explanation: 'HMW statements define the design space without constraining the solution. Good HMWs are broad enough to generate multiple solutions but narrow enough to provide direction.' }],
        keyPoints: ['Design thinking is most powerful at the beginning — investing in understanding users deeply prevents building the right thing the wrong way', 'Iteration is intentional — each prototype-test cycle is a learning investment. No prototype is a failure if you learn from it', 'Empathy is the foundation — designing for "users" in aggregate misses the nuance of individual human experiences and contexts']
      },
      evaluate: { questions: [{ question: 'The first diamond in the Double Diamond model focuses on:', options: ['Building the solution quickly', 'Problem finding — discovering real user needs before defining the problem to solve', 'Business requirements only', 'Technology constraints'], correctIndex: 1, explanation: 'First diamond = problem space (Discover + Define). Second diamond = solution space (Develop + Deliver). Many teams skip the first diamond and build solutions to assumed problems.' }, { question: '"How Might We" (HMW) statements are used to:', options: ['Write technical specifications', 'Reframe problems as design opportunities — opening the solution space without constraining it', 'Define user personas', 'Create wireframes'], correctIndex: 1, explanation: 'HMW transforms observations and insights into questions that invite creative solutions. They\'re neither too broad ("how might we end poverty") nor too narrow ("how might we add a button").' }, { question: 'The core principle that differentiates Design Thinking from traditional problem-solving is:', options: ['Using more technology', 'Being user-centred and iterative — defining problems from user research before generating solutions', 'Faster delivery timelines', 'Working alone rather than in teams'], correctIndex: 1, explanation: 'Design thinking starts with user needs (not assumptions) and iterates rapidly. Traditional engineering often defines the solution first, then builds, then tests.' }] }
    },
    'User Research Methods': {
      understand: {
        theory: `# User Research Methods\nUser research grounds design decisions in reality, replacing assumptions with evidence.\n\n## Research Methods by Type\n**Generative Research** (discovers problems/needs):\n- User interviews: 30-60 min; uncover motivations, mental models, pain points\n- Contextual inquiry: Observe users in their real environment\n- Diary studies: Users self-document over days/weeks (longitudinal)\n\n**Evaluative Research** (tests solutions):\n- Usability testing: Users attempt tasks on prototype/live product\n- A/B testing: Controlled experiment comparing two design variants\n- Cognitive walkthrough: Expert walks through product as new user would\n\n**Quantitative**:\n- Analytics (Google Analytics, Mixpanel): actual behaviour at scale\n- Surveys: Validate qualitative findings with statistical confidence\n\n## Jobs To Be Done (JTBD) Framework\n"When [SITUATION], I want [MOTIVATION], so I can [EXPECTED OUTCOME]"\nFocuses on the goal, not the feature — prevents building features nobody needs\n\n## Nielsen's 5-User Rule\nUsability testing with 5 users reveals ~85% of critical usability issues.\nRun multiple rounds of 5 rather than one large test.`,
        examples: [{ title: 'User interview question design', language: 'text', code: `INTERVIEW PLANNING: Career app feature discovery\nRESEARCH QUESTION: How do students decide on a career path?\n\nBAD INTERVIEW QUESTIONS (leading/closed):\n❌ "Do you like how our app shows career options?"\n❌ "Would you use a feature that sends daily reminders?"\n❌ "Do you find job searching stressful?"\n\nGOOD INTERVIEW QUESTIONS (open/exploratory):\n✓ "Walk me through the last time you thought about\n   your career path. What were you doing? What happened?"\n✓ "Tell me about a time you felt uncertain about your\n   career direction. What did you do?"\n✓ "What resources have you tried? What worked/didn't?"\n✓ "What does 'deciding on a career' mean to you?"\n\nFOLLOW-UP PROBES:\n• "Can you tell me more about that?"\n• "What did you do next?"\n• "How did that make you feel?"\n• "Why was that important to you?"`, explanation: 'Good interview questions are open-ended, concrete (past behaviour not hypotheticals), and non-leading. Probe for stories — specific past experiences reveal real behaviour, not idealized self-reports.' }],
        keyPoints: ['What users say they do ≠ what they actually do — observe behaviour (contextual inquiry, analytics) to catch the gap between stated and actual behaviour', 'Recruit research participants from your actual target users — insights from wrong users lead to wrong designs regardless of research quality', 'JTBD reframes user needs as progress-making goals — "people don\'t want a drill, they want a hole" — prevents feature-centric design']
      },
      evaluate: { questions: [{ question: 'Contextual inquiry is most valuable because:', options: ['It requires fewer participants than other methods', 'It observes users in their real work environment — captures actual behaviour, workarounds, and context that interviews miss', 'It is the cheapest research method', 'It provides quantitative data'], correctIndex: 1, explanation: 'People often can\'t accurately report their own behaviour in interviews. Contextual inquiry watches what they actually do — revealing undocumented workflows and pain points.' }, { question: 'Nielsen\'s guideline says 5 users in usability testing reveals:', options: ['100% of all usability issues', '50% of critical issues', '~85% of critical usability issues', 'Issues only for one user type'], correctIndex: 2, explanation: 'Nielsen\'s research: 5 users expose ~85% of usability problems. Additional users yield diminishing returns. Run 2-3 rounds of 5 to incrementally discover remaining issues.' }, { question: 'A/B testing in UX/product design is:', options: ['Testing two different products', 'A controlled experiment comparing two design variants with real users to determine which performs better on a metric', 'Testing with two separate research teams', 'Comparing two competitor products'], correctIndex: 1, explanation: 'A/B testing: random assignment to variant A or B; measure which version achieves higher conversion, engagement, or other metric. Requires sufficient traffic for statistical significance.' }] }
    },
    'Wireframing & Lo-Fi Prototypes': {
      understand: {
        theory: `# Wireframing & Lo-Fi Prototypes\nWireframes define structure and content layout before visual design — fastest way to explore and validate ideas.\n\n## Fidelity Levels\n**Lo-Fi (Sketches)**: Paper, rough wireframes\n- Purpose: Rapid ideation, explore multiple directions\n- Time: Minutes to make\n- Use when: Early concept stage, many unknowns\n\n**Mid-Fi (Greyscale wireframes)**:\n- Purpose: Information hierarchy, layout, user flows\n- Tools: Figma wireframe mode, Balsamiq\n- Use when: Validating structure before visual design\n\n**Hi-Fi (Pixel-perfect mockups)**:\n- Purpose: Visual design, developer handoff, stakeholder approval\n- Tools: Figma, Adobe XD\n- Use when: Late-stage, near-final designs\n\n## Wireframe Best Practices\n- Use greyscale — colour distracts from structure feedback\n- Represent real content (not lorem ipsum for key areas)\n- Show all states: empty state, loading, error, success\n- Annotate decisions and interactions\n- Use standard annotations: ← placeholder text, 🖼 image, ▶ video\n\n## Paper Prototyping\nPhysical paper cutouts acted out by a human "computer"\n- Reveals navigation and flow issues at zero cost\n- Most effective for testing complex workflows early`,
        examples: [{ title: 'Wireframe annotation example', language: 'text', code: `WIREFRAME ANNOTATIONS:\n\n[SCREEN: Course Dashboard]\n\n+----------------------------------+\n|  [LOGO]          [Search🔍] [👤] |\n+----------------------------------+\n|                                  |\n|  📚 Continue Learning            |\n|  ┌────────────────────────────┐  |\n|  │[▶ Course thumbnail]        │  |\n|  │ Course Title               │  |\n|  │ ████████░░ 65% complete    │  |\n|  │ [Continue →]              │  |\n|  └────────────────────────────┘  |\n|                                  |\n|  📋 Recommended For You         |\n|  [Card] [Card] [Card]            |\n+----------------------------------+\n|  🏠 Home  📚 Courses  👤 Profile |\n+----------------------------------+\n\nANNOTATIONS:\n1. Search: typeahead suggestions (max 5 results)\n2. Continue: always shows MOST RECENT course; never empty\n3. Progress bar: updates in real-time from Firestore\n4. Recommendations: personalised by completion + category\n5. Bottom nav: fixed position; active state = blue fill`, explanation: 'Wireframe annotations clarify intent and behaviour to developers and stakeholders — preventing misinterpretation and scope creep during handoff.' }],
        keyPoints: ['Test lo-fi wireframes with 5 users before moving to hi-fi — paper prototypes reveal fundamental flow issues before you invest hours in Figma', 'Greyscale forces focus on structure, not aesthetics — stakeholders won\'t debate button colours if everything is grey', 'Empty states, loading states, and error states are as important to wireframe as the happy path — they\'re often overlooked and cause poor user experience when encountered']
      },
      evaluate: { questions: [{ question: 'The primary reason to use greyscale in wireframes is:', options: ['Greyscale is faster to draw', 'Colour is too expensive at early stages', 'Greyscale forces feedback to focus on structure and hierarchy, not colour preferences', 'All wireframe tools only support greyscale'], correctIndex: 2, explanation: 'Colour triggers aesthetic opinions ("I don\'t like that shade of blue"). Greyscale keeps stakeholder feedback focused on structure, information hierarchy, and user flows — what wireframes are designed to validate.' }, { question: 'Paper prototyping is most useful:', options: ['For final developer handoff', 'At the earliest concept stage to test navigation flows and information architecture at zero cost', 'Only for mobile apps', 'For performance testing'], correctIndex: 1, explanation: 'Paper prototypes are fastest to make and change — a human acts as the "computer," advancing screens based on user taps/clicks. Reveals major flow issues before any digital work.' }, { question: 'Lo-fi wireframes should include:', options: ['Full visual design with brand colors', 'Realistic photography', 'All key states: empty state, loading, error, success — not just the happy path', 'Interactive animations'], correctIndex: 2, explanation: 'Edge cases and error states are frequently overlooked in wireframing, but users encounter them regularly. Missing these in wireframes means they\'re not planned before coding.' }] }
    },
    'Figma Deep Dive': {
      understand: {
        theory: `# Figma Deep Dive\nFigma is the industry-standard design tool for UI/UX — collaborative, browser-based, and deeply integrated with developer workflows.\n\n## Core Figma Concepts\n**Frames**: The container for designs — equivalent to artboards in other tools\n**Auto Layout**: CSS Flexbox-equivalent — elements stack, space, and wrap automatically\n**Components**: Reusable design elements; master component → instances update globally\n**Variants**: Multiple states/sizes of one component in a single component set\n**Design Tokens**: Colour, spacing, typography values applied as styles — enable design-dev consistency\n\n## Auto Layout Key Properties\n- **Direction**: Horizontal (row) or Vertical (column)\n- **Gap**: Space between items\n- **Padding**: Internal spacing (top/right/bottom/left)\n- **Alignment**: Start, centre, end, space-between\n- **Resizing**: Fixed, Hug (wraps content), Fill (stretches to parent)\n\n## Component Best Practices\n- Use `/` naming for organisation: `Button/Primary/Large`\n- Create variants for: size (sm/md/lg), state (default/hover/active/disabled)\n- Use boolean properties for show/hide elements\n- Detach component only when a specific instance truly needs unique treatment\n\n## Developer Handoff\n- **Inspect panel**: CSS values, dimensions, spacing\n- **Dev Mode**: Code snippets (CSS, React, SwiftUI)\n- **Status**: Mark frames as ready for development`,
        examples: [{ title: 'Button component with variants', language: 'text', code: `BUTTON COMPONENT STRUCTURE IN FIGMA:\n\nCOMPONENT: Button/Primary\nVARIANTS:\n  Size: Small | Medium | Large\n  State: Default | Hover | Active | Disabled | Loading\n\nAUTO LAYOUT SETTINGS (Medium):\n  Direction: Horizontal\n  Padding: 12px top/bottom, 20px left/right\n  Gap: 8px (between icon + text)\n  Alignment: Center\n  Resizing: Hug contents (width), Fixed (height: 40px)\n\nCOLOUR STYLES USED:\n  Background: --color-action-primary (brand-blue-500)\n  Text: --color-text-on-primary (white)\n  Hover: --color-action-hover (brand-blue-700)\n  Disabled: --color-neutral-300\n\nBOOLEAN PROPERTIES:\n  hasIcon: true/false\n  isLoading: true/false (shows spinner, hides text)\n\nDEVELOPER HANDOFF CSS (from Inspect panel):\ndisplay: flex;\nalign-items: center;\npadding: 12px 20px;\ngap: 8px;\nbackground: #2563EB;\nborder-radius: 8px;`, explanation: 'Well-structured components = less design maintenance and faster developer implementation. Naming, variants, and auto layout mirror real CSS structure.' }],
        keyPoints: ['Auto Layout is essential for responsive designs — components built with it adapt like real code. Build every component with Auto Layout from the start', 'Component variants must cover all realistic states — missing "disabled" or "loading" states forces developers to invent their own design during implementation', 'Use Figma Variables (not just Styles) for design tokens — they enable light/dark mode theming and cross-scope references in modern Figma']
      },
      evaluate: { questions: [{ question: 'Auto Layout in Figma is conceptually equivalent to:', options: ['CSS Grid', 'CSS position: absolute', 'CSS Flexbox — stacking, spacing, and alignment of elements in a row or column', 'HTML tables'], correctIndex: 2, explanation: 'Auto Layout mirrors Flexbox: direction (row/column), gap, padding, alignment, and sizing modes (hug/fill/fixed) all correspond to Flexbox CSS properties.' }, { question: 'Creating a Figma component variant for "disabled" state is important because:', options: ['It reduces the file size', 'It ensures the disabled state is designed and documented — preventing developers from making ad-hoc design decisions during implementation', 'Variants are required by Figma', 'It automatically generates code'], correctIndex: 1, explanation: 'Every state a user can encounter must be designed. Undesigned states get improvised during development — often inconsistently. Component variants prevent this.' }, { question: 'Figma Dev Mode provides developers with:', options: ['Automated QA testing', 'CSS/code snippets, exact dimensions and spacing, component metadata — enabling accurate implementation without guessing', 'Source code for backend APIs', 'Performance metrics'], correctIndex: 1, explanation: 'Dev Mode converts Figma designs into actionable code references — CSS values, React props suggestions, spacing, typography. Reduces developer interpretation errors.' }] }
    },
    'Design Systems': {
      understand: {
        theory: `# Design Systems\nA design system is a collection of reusable components, guidelines, and principles that enables teams to build consistent, scalable products efficiently.\n\n## Components of a Design System\n1. **Design Tokens**: Foundational values (colours, spacing, typography, shadows)\n   - Primitive: `brand-blue-500: #2563EB`\n   - Semantic: `color-action-primary: brand-blue-500`\n2. **Component Library**: Documented, accessible, coded UI components\n3. **Pattern Library**: Common UX patterns (forms, navigation, error handling)\n4. **Documentation**: Usage guidelines, do/don't examples, accessibility notes\n5. **Voice & Tone**: Writing style for UI copy\n\n## Design Token System\n**Layer 1 — Primitives** (all possible values)\n**Layer 2 — Semantic** (purpose-based mapping)\n**Layer 3 — Component** (component-specific override)\n\nBenefit: Change `brand-primary` → entire system updates\n\n## Famous Design Systems\n- **Material Design** (Google): Widely used; extensive component library\n- **Carbon** (IBM): Accessible, enterprise-focused\n- **Atlassian Design System**: Jira/Confluence products\n- **Ant Design**: Popular in China; large component library for enterprise\n- **Radix Primitives**: Headless, accessible components for custom styling`,
        examples: [{ title: 'Spacing scale in a design system', language: 'text', code: `SPACING SYSTEM (8px base grid):\n\nPRIMITIVE TOKENS:\nspace-1:  4px   (half-unit — use sparingly)\nspace-2:  8px   (base unit)\nspace-3:  12px\nspace-4:  16px  (default content spacing)\nspace-5:  20px\nspace-6:  24px  (section internal padding)\nspace-7:  32px\nspace-8:  40px\nspace-10: 48px  (section dividers)\nspace-12: 64px  (major section gaps)\n\nSEMANTIC TOKENS:\nspacing-component-gap:     space-2  (8px)\nspacing-section-padding:   space-6  (24px)\nspacing-page-margin:       space-8  (40px)\nspacing-card-padding:      space-6  (24px)\nspacing-inline-gap:        space-2  (8px)\n\nIN TAILWIND CSS:\ngap-2, p-6, mx-8 etc. map to this scale\n\nRULE: Only use values from the scale.\nNo "17px" or "22px" — use nearest scale value.\nThis creates visual rhythm and consistency.`, explanation: 'A spacing scale creates visual rhythm. All team members using the same scale means every component feels like it belongs in the same family.' }],
        keyPoints: ['Design tokens are the bridge between design and code — they eliminate the "we use #2563EB in Figma but developer used #2464EC" problem permanently', 'A design system is never finished — it requires ongoing governance, versioning, and a clear process for adding/deprecating components', 'Accessibility must be built into the system — WCAG-compliant colour contrasts, keyboard navigation, and ARIA attributes in every component from the start']
      },
      evaluate: { questions: [{ question: 'The primary benefit of semantic design tokens over primitive tokens is:', options: ['They use fewer colours', 'They provide purpose-based naming — enabling global theme changes and dark mode without touching individual components', 'They are required by Figma', 'They reduce the number of tokens needed'], correctIndex: 1, explanation: 'Primitive: blue-500 = #2563EB. Semantic: color-action-primary = blue-500. If you change the brand, only the semantic mapping changes — all components update automatically.' }, { question: 'A design system documentation should include:', options: ['Only code samples', 'Component code only', 'Usage guidelines, do/don\'t examples, accessibility notes, variants, and edge cases — enough for any team member to use correctly', 'Only visual design files'], correctIndex: 2, explanation: 'Documentation is what makes a component library a design system. Without usage guidelines and accessibility notes, components are misused even when they\'re well-designed.' }, { question: 'An 8px grid system means:', options: ['All elements must be exactly 8px tall', 'All spacing values should be multiples of 8px — creating consistent visual rhythm and aligning with common screen resolution grids', 'Grid columns are 8px wide', 'Icons must be 8×8px'], correctIndex: 1, explanation: '8px grid: spacing values are multiples of 8 (8, 16, 24, 32...). Creates visual consistency and aligns with common OS interface norms. 4px allowed for fine adjustments.' }] }
    },
  },
  'Figma Mastery': {
    'Frame & Component Basics': {
      understand: {
        theory: `# Figma Frames & Component Basics\n## Frames\nFrames are the primary container in Figma — they define a screen, a component, or a section. Unlike groups, frames can clip content, have independent auto layout, and act as scroll containers.\n\n**Frame vs Group**:\n- Group: Simple collection; inherits parent constraints\n- Frame: Independent container; has its own constraints, auto layout, clip content\n\n## Component System\n**Master component**: The original; defines properties, styles, variants\n**Instance**: A linked copy of the master; can be customised within limits\n**Detach**: Breaks the link — instance becomes a group (use sparingly)\n\n## Naming Conventions (Best Practice)\nUse `/` for categorisation:\n```\nButton/Primary/Large\nButton/Secondary/Small\nIcon/Arrow/Left\nInput/Text/Default\nInput/Text/Error\n```\nThis creates a menu hierarchy in the Assets panel.\n\n## Constraints & Responsiveness\nConstraints define how elements respond when frame is resized:\n- Left/Top: Fixed position from left/top edge\n- Right/Bottom: Maintains distance from right/bottom\n- Centre: Maintains centred position\n- Scale: Scales proportionally\n- Left & Right: Stretches horizontally`,
        examples: [{ title: 'Component organisation system', language: 'text', code: `FIGMA FILE STRUCTURE:\n\n📄 Design System (Main file)\n├── 🟣 Page: Foundations\n│   ├── Colour Styles\n│   ├── Typography Styles\n│   ├── Spacing Grid\n│   └── Shadow Styles\n├── 🟣 Page: Components\n│   ├── Atoms\n│   │   ├── Button/Primary/sm\n│   │   ├── Button/Primary/md\n│   │   ├── Button/Secondary/md\n│   │   ├── Input/Text/Default\n│   │   ├── Input/Text/Error\n│   │   └── Badge/Success\n│   ├── Molecules\n│   │   ├── FormField/Text\n│   │   ├── Card/Course\n│   │   └── NavItem/Active\n│   └── Organisms\n│       ├── Navbar\n│       ├── CourseCard\n│       └── Modal/Default\n├── 🟣 Page: Screens\n│   ├── Dashboard\n│   ├── Course Detail\n│   └── Settings\n└── 🟣 Page: Prototype (linked screens)`, explanation: 'A well-organised Figma file is as important as well-organised code. Consistent naming enables search, automation (Figma API), and fast onboarding for new designers.' }],
        keyPoints: ['Master component updates propagate to ALL instances instantly — this is the core value proposition of components in Figma', 'Detach component only when truly necessary — once detached, the instance no longer benefits from master updates', 'Use `/` naming hierarchy from the beginning — retrofitting naming conventions to a large design file is painful']
      },
      evaluate: { questions: [{ question: 'The key difference between a Figma Frame and a Group is:', options: ['Frames are for illustrations; groups for UI', 'Frames are independent containers with their own constraints, clipping, auto layout, and resizing behaviour; groups simply collect layers', 'Groups cannot contain images', 'Frames are always rectangles; groups can be any shape'], correctIndex: 1, explanation: 'Frames have independent properties: constraints, auto layout, clipping, scroll behaviour. Groups are simpler collections without these features. Use frames for UI screens and components.' }, { question: 'Editing a master component in Figma:', options: ['Only changes that specific instance', 'Updates all instances linked to that master automatically', 'Creates a new component', 'Has no effect on existing instances'], correctIndex: 1, explanation: 'Master component → all instances inherit changes. This is Figma\'s core productivity feature — change button style once → all 200 buttons in the file update instantly.' }, { question: 'The naming convention "Button/Primary/Large" in Figma creates:', options: ['A new page called Button', 'A three-level hierarchy in the Assets panel: Button → Primary → Large', 'A component group that cannot be edited', 'Only a stylistic choice with no functional impact'], correctIndex: 1, explanation: 'Figma uses `/` as a hierarchy separator. "Button/Primary/Large" creates a nested menu structure in Assets — making components findable at scale.' }] }
    },
  },
  'Brand Identity Design': {
    'Brand Strategy & Positioning': {
      understand: {
        theory: `# Brand Strategy & Positioning\nBrand strategy defines what a brand stands for, who it's for, and how it differs from competitors. Visual identity is the expression of this strategy — not the strategy itself.\n\n## Brand Strategy Framework\n1. **Purpose**: Why does the brand exist beyond profit? (Simon Sinek: "Start With Why")\n2. **Vision**: What future state does it seek to create?\n3. **Mission**: What does it do to get there?\n4. **Values**: Principles guiding all decisions\n5. **Positioning**: Where does it sit relative to competitors?\n\n## Positioning Statement Formula\n"For [TARGET AUDIENCE], [BRAND] is the [CATEGORY] that [KEY BENEFIT] because [REASON TO BELIEVE]"\n\nExample: "For ambitious Indian college students, CareerBoost is the career learning platform that gives you job-ready skills and industry mentorship because it combines AI-personalised learning with real expert guidance."\n\n## Brand Archetypes (Jung)\n12 universal archetypes map brand personality:\n- **Hero**: Nike, Under Armour — inspires, overcomes challenges\n- **Sage**: Google, TED — knowledge, truth, wisdom\n- **Rebel**: Harley-Davidson — breaks rules, disrupts\n- **Caregiver**: Johnson & Johnson — nurturing, protective\n- **Creator**: Apple, Adobe — imagination, innovation\n\n## Positioning Map\nPlot brand vs competitors on 2 axes (e.g., premium↔budget, specialist↔generalist) to identify white space`,
        examples: [{ title: 'Brand audit exercise', language: 'text', code: `BRAND AUDIT FRAMEWORK:\n\nCOMPANY: EdTech startup entering Indian market\n\n1. COMPETITIVE MAPPING\n   Premium ────────────────────── Budget\n   |  Coursera        Byju's       |\n   |      LinkedIn    NPTEL        |\n   General ──────────────── Specialist\n   \n   CareerBoost opportunity: Premium + Career-Specialist\n   (Job-ready skills + mentorship, not just content)\n\n2. BRAND PERSONALITY TRAITS (choose 3-5):\n   ✓ Ambitious — champions student potential\n   ✓ Expert — credible, rigorous, current\n   ✓ Human — warm, empathetic, accessible\n   ✗ Corporate — too formal for students\n   ✗ Disruptive — overclaimed in EdTech already\n\n3. BRAND ARCHETYPE: Mentor/Sage\n   (Knowledge + genuine care for student success)\n\n4. POSITIONING STATEMENT:\n   "For ambitious Indian students navigating early\n   career decisions, CareerBoost is the only platform\n   that combines AI-powered learning with real mentor\n   access — proven to accelerate career outcomes."`, explanation: 'Brand strategy before visual identity. If the strategy is unclear, any logo design is arbitrary — it won\'t communicate the right things to the right people.' }],
        keyPoints: ['Brand positioning is relative — you are always positioned relative to alternatives. The positioning map reveals white space that competitors haven\'t claimed', 'Brand archetypes provide a consistent personality framework — all communication, visual design, and copy should feel like the same "person" across all touchpoints', 'Logo is not brand — it\'s the symbol of the brand. A logo without a clear strategy behind it is just a decoration']
      },
      evaluate: { questions: [{ question: 'A brand positioning statement answers:', options: ['What colour the brand should use', 'Who the brand is for, what category it competes in, what benefit it provides, and why it\'s credible', 'Only the company mission statement', 'The brand\'s marketing budget allocation'], correctIndex: 1, explanation: 'Positioning statement: "For [audience], [brand] is the [category] that [key benefit] because [reason to believe]." It defines the competitive space and unique value offered.' }, { question: 'Brand archetypes help designers by:', options: ['Specifying exact fonts and colours', 'Providing a consistent personality framework that guides all visual and communication decisions to feel coherent', 'Eliminating the need for user research', 'Defining the pricing strategy'], correctIndex: 1, explanation: 'Archetypes (Hero, Sage, Creator, etc.) provide a personality model — every design decision can be checked against it: "Does this look/feel like our archetype?"' }, { question: 'The primary purpose of a competitive positioning map is:', options: ['To copy competitor designs', 'To visualise where the brand sits relative to competitors — identifying white space and differentiation opportunities', 'To determine competitor pricing', 'To track competitor marketing spend'], correctIndex: 1, explanation: 'Positioning map plots brands on 2-dimensional axes (e.g., price vs. quality). Shows where the market is crowded and where opportunities for differentiation exist.' }] }
    },
  },
};
