export const FINANCE_CONTENT: Record<string, Record<string, any>> = {
  'Investment Banking': {
    'Valuation Methods': {
      understand: {
        theory: `# Valuation Methods\nCorporate valuation is the cornerstone of investment banking. The "triangle of valuation" uses three methodologies that cross-check each other.\n\n## 1. DCF (Discounted Cash Flow)\n**Intrinsic value** based on projected future free cash flows discounted to present value.\n\nFormula: **Enterprise Value = Σ [FCF_t / (1+WACC)^t] + Terminal Value**\n\nTerminal Value (Gordon Growth): TV = FCF_(n+1) / (WACC − g)\n\n## 2. Comparable Company Analysis (Comps)\nValue a company based on trading multiples of similar public companies.\nCommon multiples: **EV/EBITDA** (most widely used), EV/Revenue, P/E, P/B\n\nProcess: Select peers → Calculate their multiples → Apply median/mean to target's metrics\n\n## 3. Precedent Transactions\nValue based on actual M&A deals for comparable companies.\nIncludes **control premium** (20-40% above market) — reflects value of control.\n\n## The Football Field Chart\nPresents all three valuation ranges side-by-side — shows value range, not a single number.`,
        examples: [{ title: 'EV/EBITDA multiple calculation', language: 'text', code: `SCENARIO: Value a SaaS company (EdTech)\n\nTarget metrics:\nRevenue: ₹120 Cr | EBITDA: ₹24 Cr | Net Debt: ₹10 Cr\n\nComparable EdTech companies (public):\n| Company | EV/EBITDA | EV/Revenue |\n|---------|-----------|------------|\n| Byju's  | 25x       | 6x         |\n| Unacad. | 22x       | 5x         |\n| Doubtnt | 28x       | 7x         |\n|---------|-----------|------------|\n| Median  | 25x       | 6x         |\n\nValuation:\nEV (EBITDA basis) = ₹24 Cr × 25 = ₹600 Cr\nEquity Value = EV − Net Debt = ₹600 − ₹10 = ₹590 Cr\n\nEV (Revenue basis) = ₹120 Cr × 6 = ₹720 Cr\nEquity Value = ₹720 − ₹10 = ₹710 Cr\n\nValuation range: ₹590 Cr − ₹710 Cr`, explanation: 'Multiple-based valuation is fast but depends on comparable selection. The art is choosing truly comparable companies.' }],
        keyPoints: ['DCF is theoretically rigorous but highly sensitive to WACC and terminal growth rate assumptions — small changes create large value swings', 'EV/EBITDA is the most commonly used multiple in M&A — removes distortions from capital structure and tax rates', 'Precedent transactions include a control premium; trading comps do not — precedent gives a higher valuation range typically']
      },
      evaluate: { questions: [{ question: 'What does WACC stand for and why is it used in DCF?', options: ['Weighted Average Capital Cost — used to calculate earnings per share', 'Weighted Average Cost of Capital — used as the discount rate to present-value future cash flows', 'Working Asset Capital Count — measures liquidity', 'Weighted Asset Calculation Component — for balance sheet'], correctIndex: 1, explanation: 'WACC reflects the blended cost of all capital (debt + equity). It is used to discount future FCFs because it represents the minimum return investors require.' }, { question: 'Why do precedent transaction multiples tend to be higher than trading comps?', options: ['Precedent deals are older and markets were higher', 'Transactions include a control premium (20-40%) that trading multiples do not', 'Precedent comps use higher EBITDA margins', 'Trading comps exclude synergies'], correctIndex: 1, explanation: 'M&A buyers pay a control premium above market price to gain strategic control. Trading multiples reflect minority stakes — no control premium.' }, { question: 'Terminal Value in DCF typically represents what % of total enterprise value?', options: ['10-20%', '30-50%', '60-80%', '99%+'], correctIndex: 2, explanation: 'Terminal value often represents 60-80% of DCF value — which is why assumptions about terminal growth rate and WACC have outsized impact on valuation.' }] }
    },
    'M&A Process': {
      understand: {
        theory: `# M&A Process\n## Buy-side vs. Sell-side\n**Buy-side**: PE/strategic acquirer seeking targets → originate, analyse, structure, execute\n**Sell-side**: Investment bank representing the seller → manage sale process, run auction, maximise price\n\n## Typical M&A Timeline\n**Phase 1 — Preparation (4-8 weeks)**\nSell-side: Prepare Information Memorandum (IM), build financial model, identify buyers\nBuy-side: Set investment criteria, identify targets, initiate approach\n\n**Phase 2 — Marketing (4-6 weeks)**\nSend teaser → NDAs signed → Send IM → Management presentations → First-round bids (non-binding LOI)\n\n**Phase 3 — Due Diligence (6-12 weeks)**\nVirtual data room access → Legal/financial/technical DD → Management Q&A\n\n**Phase 4 — Negotiation & Close (4-8 weeks)**\nFinal bids → Exclusivity → SPA/SHA negotiation → CCI approval (if needed) → Closing\n\n## Key Documents\n- **NDA**: Confidentiality before information sharing\n- **Teaser**: 2-page anonymous summary\n- **IM** (Information Memorandum / CIM): Full confidential document\n- **LOI/Term Sheet**: Non-binding outline of key terms\n- **SPA** (Share Purchase Agreement): Binding purchase contract`,
        examples: [{ title: 'Accretion/Dilution Analysis', language: 'text', code: `QUESTION: "Will this acquisition be accretive or dilutive to EPS?"\n\nAcquirer: EPS = ₹20, P/E = 25x, Shares = 100M\nTarget: Net Income = ₹200 Cr, Price = ₹2,500 Cr (100% stock deal)\n\nNew shares issued = Deal Value / Acquirer share price\n= ₹2,500 Cr / (₹20 × 25) = ₹2,500 / ₹500 = 5M shares\n\nCombined EPS:\nNumerator: (₹20 × 100M + ₹200 Cr) / ... \n\nSimple version:\nCost of acquisition (P/E paid) = 2,500 / 200 = 12.5x P/E\nAcquirer P/E = 25x\n\nRule: If target's P/E < Acquirer's P/E in a stock deal → ACCRETIVE\nHere: 12.5x < 25x → Accretive to EPS`, explanation: 'Accretion/dilution is an interview staple. If acquirer P/E > acquisition P/E (all-stock deal), it is accretive. Cash deals bypass this calculation.' }],
        keyPoints: ['LOI/Term Sheet establishes key terms (price, structure, exclusivity) — non-binding but sets negotiation anchor', 'Exclusivity period (typically 30-60 days) gives the buyer time for confirmatory DD without the seller talking to other bidders', 'A data room (now virtual — Intralinks, Datasite) contains all due diligence materials — access controlled by NDA and permission levels']
      },
      evaluate: { questions: [{ question: 'An Information Memorandum (IM) in M&A is:', options: ['A regulatory filing with SEBI', 'A confidential document prepared by the sell-side describing the target company to potential buyers', 'The binding purchase agreement', 'A due diligence report'], correctIndex: 1, explanation: 'The IM (also called CIM — Confidential Information Memorandum) is the detailed marketing document prepared by the sell-side banker for the target. Shared only under NDA.' }, { question: 'Exclusivity in M&A means:', options: ['The buyer has the only bid', 'The seller agrees to negotiate only with this buyer for a defined period (30-60 days)', 'The deal is fully signed', 'Regulatory approval is granted'], correctIndex: 1, explanation: 'Exclusivity (lock-up) stops the seller from talking to other bidders while the buyer completes confirmatory due diligence.' }, { question: 'Accretion/dilution analysis in M&A measures:', options: ['Whether the deal creates synergies', 'The impact of the acquisition on the acquirer\'s Earnings Per Share (EPS)', 'The target\'s revenue growth', 'Post-merger market share'], correctIndex: 1, explanation: 'Accretive = deal increases acquirer\'s EPS. Dilutive = EPS decreases. Shareholders dislike dilutive deals immediately.' }] }
    },
    'Capital Markets': {
      understand: {
        theory: `# Capital Markets\n## Primary vs. Secondary Markets\n**Primary**: New securities issued; proceeds go to issuer (IPO, FPO, QIP, bonds)\n**Secondary**: Existing securities traded between investors; issuer doesn't receive proceeds (BSE, NSE)\n\n## Equity Capital Markets (ECM)\n- **IPO**: First public offer; requires DRHP → SEBI review → RHP → Price band → Allotment\n- **FPO** (Follow-on Public Offer): Listed company issues additional shares\n- **QIP** (Qualified Institutional Placement): Fast track to institutional investors; no SEBI review required for listed companies\n- **Rights Issue**: Existing shareholders offered new shares proportionally\n\n## Debt Capital Markets (DCM)\n- **NCDs** (Non-Convertible Debentures): Fixed income; rated by CRISIL/ICRA\n- **ECBs** (External Commercial Borrowings): Foreign currency debt from overseas lenders\n- **Masala Bonds**: INR-denominated bonds issued in international markets\n- **Commercial Paper**: Short-term unsecured promissory notes; up to 1 year; for working capital\n\n## Credit Ratings\nAAA → AA → A → BBB (investment grade)\nBB → B → CCC → D (sub-investment / junk)\nRating determines borrowing cost — lower rating = higher yield required`,
        examples: [{ title: 'IPO book building process', language: 'text', code: `IPO BOOK BUILDING TIMELINE:\n\nT-90 days: DRHP filed with SEBI\nT-30 days: SEBI observations received\nT-7 days: RHP filed; price band announced (e.g., ₹180-₹200)\nT-3 days: Issue opens (3 days subscription window)\n\nCATEGORIES:\n• QIB (Qualified Institutional Buyers): 50% reserved\n• NII (Non-Institutional Investors, >₹2L): 15%\n• Retail (≤₹2L): 35%\n\nBID RESULTS:\n• QIB: subscribed 100×\n• NII: subscribed 80×\n• Retail: subscribed 15×\n\nALLOTMENT (for retail oversubscription):\nLottery for lots; minimum 1 lot guaranteed to all applicants\nif oversubscribed < certain level\n\nT+6 days: Listing on NSE/BSE`, explanation: 'Book building discovers market price within the band. High QIB subscription signals strong institutional demand — typically positive for listing performance.' }],
        keyPoints: ['QIP (Qualified Institutional Placement) is the fastest equity raising route for listed companies — can be completed in 2-3 weeks vs. 3-4 months for FPO', 'Credit ratings directly affect borrowing cost: AAA companies borrow at near-government rates; junk bonds may pay 5-10% above AAA', 'Green bonds and sustainability-linked bonds are fastest-growing segment — proceeds used for environmental/social projects with investor disclosure requirements']
      },
      evaluate: { questions: [{ question: 'In an IPO book building, the price band indicates:', options: ['The final offer price', 'The floor and cap within which bids are collected — final price discovered by demand', 'The range of broker fees', 'The SEBI-mandated price'], correctIndex: 1, explanation: 'Book building price discovery: company and bankers set a band; investors bid within it; the cut-off (final) price is where the issue is fully subscribed.' }, { question: 'QIP (Qualified Institutional Placement) is preferred over FPO when:', options: ['Company needs retail investor participation', 'Speed is critical — QIP can be completed in weeks without full SEBI review process', 'The company wants to maximise investor base', 'Retail investors should have priority'], correctIndex: 1, explanation: 'QIP is a fast-track instrument for listed companies to raise equity from institutional investors without the months-long public offer process.' }, { question: 'An investment-grade credit rating means:', options: ['The issuer will never default', 'Rating of BBB/Baa and above — considered low default risk; eligible for institutional investor portfolios', 'Rating above AA only', 'Any SEBI-approved rating'], correctIndex: 1, explanation: 'Investment grade = BBB/Baa3 and above (S&P/Moody\'s). Many institutional investors (insurance, pension funds) are mandated to hold only investment-grade debt.' }] }
    },
    'Financial Modelling': {
      understand: {
        theory: `# Financial Modelling\nFinancial models are quantitative tools for decision-making. The "3-statement model" links the Income Statement, Balance Sheet, and Cash Flow Statement.\n\n## 3-Statement Model Structure\n**Income Statement** → drives Net Income\n**Balance Sheet** → cumulative snapshot; balance requires:\nAssets = Liabilities + Equity (always)\n**Cash Flow Statement** → reconciles net income to actual cash movement\n\n**Key links:**\n- Net Income → Retained Earnings (Balance Sheet)\n- D&A (IS) → added back in Operating Cash Flow\n- CapEx → Property/Equipment (Balance Sheet)\n- Changes in Working Capital → Operating Cash Flow\n\n## DCF Model\nStep 1: Project Revenue → EBITDA → EBIT → NOPAT\nStep 2: Calculate Free Cash Flow = NOPAT + D&A − CapEx − ΔNWC\nStep 3: Discount FCFs at WACC\nStep 4: Calculate Terminal Value\nStep 5: Sum to Enterprise Value; subtract net debt for Equity Value\n\n## LBO (Leveraged Buyout) Model\n- PE firm acquires company with high debt (typically 60-70% debt)\n- Target: 20%+ IRR over 5-year hold\n- Returns from: EBITDA growth, multiple expansion, debt paydown`,
        examples: [{ title: 'Working Capital modelling', language: 'text', code: `WORKING CAPITAL = Current Assets − Current Liabilities\n= (Receivables + Inventory) − Payables\n\nDRIVERS:\nDays Sales Outstanding (DSO) = Receivables / Revenue × 365\nDays Inventory Outstanding (DIO) = Inventory / COGS × 365\nDays Payables Outstanding (DPO) = Payables / COGS × 365\n\nCash Conversion Cycle = DSO + DIO − DPO\n\nEXAMPLE:\nRevenue = ₹1,200 Cr; COGS = ₹720 Cr\nDSO = 45 days → Receivables = ₹1,200 × 45/365 = ₹148 Cr\nDIO = 30 days → Inventory  = ₹720 × 30/365  = ₹59 Cr\nDPO = 60 days → Payables   = ₹720 × 60/365  = ₹118 Cr\n\nWorking Capital = 148 + 59 − 118 = ₹89 Cr\nCash Conversion Cycle = 45 + 30 − 60 = 15 days`, explanation: 'Working capital consumes cash as companies grow. A DSO increase (customers paying slower) increases working capital — a cash drag even in profitable companies.' }],
        keyPoints: ['3-statement models must "close" — the balance sheet balances with the cash balance as the plug. A model that doesn\'t balance has an error', 'Sensitivity analysis and scenario analysis are essential — present a base case + bull/bear cases; never rely on one set of assumptions', 'In LBO models, IRR is driven by 3 factors: entry multiple, exit multiple, and EBITDA growth. Debt paydown amplifies equity returns (leverage effect)']
      },
      evaluate: { questions: [{ question: 'In a 3-statement model, the linking item from Net Income to the Balance Sheet is:', options: ['EBITDA', 'Retained Earnings — Net Income increases Retained Earnings on the balance sheet', 'Working Capital', 'Cash from Operations'], correctIndex: 1, explanation: 'Net Income flows to Retained Earnings in Shareholders\' Equity. Dividends reduce Retained Earnings further.' }, { question: 'Free Cash Flow = NOPAT + D&A − CapEx − ΔNWC. Why is D&A added back?', options: ['Depreciation increases cash', 'D&A is a non-cash charge deducted from operating profit but does not actually use cash', 'D&A reduces taxes', 'D&A is a balance sheet item'], correctIndex: 1, explanation: 'D&A reduces accounting profit but is non-cash. Adding it back converts from accrual profit to cash generation.' }, { question: 'In an LBO, returns are primarily driven by:', options: ['Revenue growth only', 'EBITDA growth, multiple expansion (exit vs. entry), and debt paydown amplifying equity returns', 'Minimising CapEx', 'Dividend distributions during the hold period'], correctIndex: 1, explanation: 'LBO return (IRR) = EBITDA growth × exit multiple expansion × leverage effect (debt paydown). PE firms target ≥20% IRR over 5 years.' }] }
    },
    'Financial Statement Analysis': {
      understand: {
        theory: `# Financial Statement Analysis\nAnalysing financial statements reveals operational efficiency, financial health, and profitability trends. Analyse 3-5 years of data; compare to industry peers.\n\n## Profitability Ratios\n- **Gross Margin** = Gross Profit / Revenue — pricing power and production efficiency\n- **EBITDA Margin** = EBITDA / Revenue — operating efficiency (before financing, tax, non-cash)\n- **Net Margin** = Net Profit / Revenue — bottom-line profitability\n- **ROE** = Net Income / Shareholders' Equity — return generated for equity investors\n- **ROCE** = EBIT / Capital Employed — overall capital efficiency\n\n## DuPont Analysis (ROE decomposition)\nROE = Net Margin × Asset Turnover × Financial Leverage\n= (Net Income/Revenue) × (Revenue/Assets) × (Assets/Equity)\n\n## Liquidity Ratios\n- **Current Ratio** = Current Assets / Current Liabilities (>1.5 is healthy)\n- **Quick Ratio** = (CA − Inventory) / CL (>1.0 removes inventory illiquidity)\n- **Cash Ratio** = Cash / CL (most conservative)\n\n## Leverage Ratios\n- **Debt/Equity** = Total Debt / Equity (>2 is high leverage)\n- **Interest Coverage** = EBIT / Interest Expense (>3x is healthy)\n- **Net Debt/EBITDA** = Net Debt / EBITDA (>4x is stretched in most industries)`,
        examples: [{ title: 'DuPont ROE analysis', language: 'text', code: `COMPANY COMPARISON: Infosys vs TCS (hypothetical)\n\n          Net Margin  × Asset Turnover × Leverage = ROE\nInfosys:    22%       ×     0.83       ×  1.2     = 21.9%\nTCS:        21%       ×     0.90       ×  1.1     = 20.8%\n\nANALYSIS:\n• Infosys: Higher margin but lower turnover\n  → More premium services but assets less efficiently used\n• TCS: Slightly lower margin, better asset utilisation\n  → Volume efficiency\n\nBoth have low leverage (conservative balance sheets)\n\nROE improvement strategies:\n• Increase margins (pricing power, cost efficiency)\n• Improve asset utilisation (reduce idle assets)\n• Increase leverage (within safe limits)\n• Share buybacks (reduce equity denominator)`, explanation: 'DuPont breaks ROE into 3 drivers — allows you to identify whether ROE is driven by profitability, efficiency, or leverage (good or risky?).' }],
        keyPoints: ['DuPont analysis reveals the SOURCE of ROE — high ROE from leverage is riskier than high ROE from profit margins or asset efficiency', 'Quality of earnings analysis: Is revenue cash-backed? (check receivables) Is profit repeatable? (exclude one-time items)', 'Working capital management: improving receivables collection (DSO) and extending payables (DPO) generates cash without profit impact']
      },
      evaluate: { questions: [{ question: 'DuPont analysis decomposes ROE into:', options: ['Revenue × EBITDA × Cash Flow', 'Net Margin × Asset Turnover × Financial Leverage', 'Gross Margin × Operating Margin × Net Margin', 'Revenue × Net Income × Equity'], correctIndex: 1, explanation: 'DuPont: ROE = (Net Income/Revenue) × (Revenue/Assets) × (Assets/Equity). Reveals whether ROE is driven by profitability, efficiency, or leverage.' }, { question: 'Quick Ratio excludes inventory because:', options: ['Inventory is irrelevant to short-term obligations', 'Inventory is the least liquid current asset — may take time to sell and convert to cash', 'Inventory is a fixed asset', 'Inventory is already in the current ratio'], correctIndex: 1, explanation: 'Quick ratio = (Current Assets − Inventory) / Current Liabilities. Inventory may be hard to liquidate quickly — quick ratio is a stricter liquidity test.' }, { question: 'An Interest Coverage Ratio of 1.2x means:', options: ['The company is very profitable', 'EBIT barely covers interest — only 20% buffer; highly vulnerable to earnings decline', 'The company has good debt management', 'The company can take on 1.2× more debt safely'], correctIndex: 1, explanation: 'ICR = EBIT / Interest Expense. 1.2x means EBIT is barely 120% of interest — a 20% EBIT decline means interest is uncovered.' }] }
    },
    'Risk Management': {
      understand: {
        theory: `# Risk Management\n## Types of Financial Risk\n- **Market Risk**: Losses from changes in market prices (equities, rates, FX, commodities)\n- **Credit Risk**: Counterparty defaults on obligation\n- **Liquidity Risk**: Cannot meet obligations when due at reasonable cost\n- **Operational Risk**: Failures in processes, people, systems (includes fraud, cyber)\n- **Concentration Risk**: Over-exposure to a single name/sector/geography\n\n## Risk Measurement\n- **VaR (Value at Risk)**: Maximum expected loss over a period at a confidence level\n  E.g., "1-day 99% VaR = ₹10 Cr" → only 1% chance of losing >₹10 Cr in one day\n- **Expected Shortfall (CVaR)**: Average loss beyond the VaR threshold\n- **Beta**: Sensitivity of a portfolio/stock to market movements (β=1 moves with market)\n- **Duration**: Bond price sensitivity to interest rate changes\n\n## Hedging Instruments\n- **Futures**: Exchange-traded; standardised; daily marked-to-market\n- **Forwards**: OTC; customised; no daily settlement; credit risk\n- **Options**: Right (not obligation) to buy/call or sell/put at strike price; premium paid\n- **Swaps**: Exchange cash flow streams (interest rate swap: fixed ↔ floating)`,
        examples: [{ title: 'FX hedging for an export company', language: 'text', code: `SCENARIO:\nIT company will receive USD 5M in 90 days\nCurrent USD/INR spot: 84\nExpected receipt: ₹42 Cr\n\nRISK: USD weakens; receipt drops to ₹40 Cr (INR 80/USD)\n\nHEDGING OPTIONS:\n\n1. FORWARD CONTRACT (bank):\n   Lock in rate: 84.50 (includes forward premium)\n   Guaranteed receipt: ₹42.25 Cr regardless of spot\n   Pros: Certainty; Cons: No upside if USD strengthens\n\n2. USD PUT OPTION (NSE):\n   Buy right to sell USD at 84 in 90 days; pay option premium\n   If USD falls to 80: exercise put → receive ₹42 Cr\n   If USD rises to 88: let option lapse → receive ₹44 Cr\n   Pros: Downside protected + upside retained\n   Cons: Premium cost (~1-2% of notional)`, explanation: 'Forwards eliminate FX uncertainty. Options preserve upside at the cost of a premium. The choice depends on risk appetite and cash flow predictability.' }],
        keyPoints: ['VaR is widely used but has limitations — it doesn\'t tell you HOW MUCH you lose beyond the threshold. Use CVaR/Expected Shortfall together', 'Hedging reduces risk but can also reduce profits if the risk event doesn\'t materialise — CFOs must balance certainty vs. opportunity cost', 'SEBI mandates risk disclosure for mutual funds; RBI mandates ALM (Asset-Liability Management) for banks — regulatory risk management is mandatory']
      },
      evaluate: { questions: [{ question: '1-day 99% VaR of ₹10 Crore means:', options: ['The portfolio will lose ₹10 Cr today', 'There is a 99% chance of losing more than ₹10 Cr', 'There is a 1% chance of losing MORE than ₹10 Cr in one day', 'The maximum possible loss is ₹10 Cr'], correctIndex: 2, explanation: '99% VaR: only 1% of days will see losses exceed ₹10 Cr. On 99 out of 100 days, losses will be ₹10 Cr or less.' }, { question: 'An interest rate swap allows a company to:', options: ['Eliminate all interest rate risk permanently', 'Exchange fixed rate payments for floating rate (or vice versa) with a counterparty', 'Borrow at lower rates from the central bank', 'Swap debt for equity'], correctIndex: 1, explanation: 'In a fixed-to-floating swap, one party pays fixed rate and receives LIBOR/SOFR. Used to match interest rate exposure to underlying business.' }, { question: 'Beta = 1.5 for a stock means:', options: ['The stock returns 50% more than the market always', 'The stock moves 1.5× the market return on average — higher systematic risk', 'The stock is 50% more profitable', 'The stock has 1.5× the dividend yield'], correctIndex: 1, explanation: 'Beta measures systematic (market) risk. β=1.5 means if the market rises/falls 10%, the stock typically rises/falls 15%.' }] }
    },
    'Personal Finance': {
      understand: {
        theory: `# Personal Finance\n## The Personal Finance Framework\n**Income → Budget → Save → Invest → Protect → Plan**\n\n## Budgeting — 50/30/20 Rule\n- **50%** — Needs (rent, utilities, food, transport)\n- **30%** — Wants (dining, entertainment, travel)\n- **20%** — Savings + Debt repayment\n\n## Investment Vehicles (India)\n| Product | Risk | Returns | Horizon |\n|---------|------|---------|--------|\n| FD (Fixed Deposit) | Low | 6-7% | 1-5 yr |\n| PPF (Public Provident Fund) | Nil | ~7.1% | 15 yr |\n| ELSS Mutual Funds | Medium-High | 12-15% hist. | 3+ yr |\n| Index Funds (Nifty 50) | Medium | 12% hist. | 7+ yr |\n| Direct Equity | High | Variable | 5+ yr |\n| Real Estate | Medium | 8-10% | 10+ yr |\n\n## Emergency Fund\n3-6 months of essential expenses in liquid instruments (liquid mutual fund or high-interest savings account). Build this BEFORE investing.\n\n## Insurance (Protection)\n- **Term Life Insurance**: High cover (25-30× annual income) at low cost; pure risk cover\n- **Health Insurance**: ₹10-25L family floater; critical at young age when premiums are low`,
        examples: [{ title: 'Compounding — the 8th wonder of the world', language: 'text', code: `POWER OF COMPOUNDING:\n\nInvest ₹10,000/month starting age 22 (SIP in index fund)\nAssumed return: 12% per annum\n\nAt age 45 (23 years):\nTotal invested:  ₹27,60,000 (₹27.6 Lakhs)\nCorpus value:   ₹1,84,00,000 (₹1.84 Crores!)\n\nStart at age 32 instead:\nTotal invested:  ₹15,60,000 (₹15.6 Lakhs)\nCorpus at 45:   ₹60,90,000 (₹60.9 Lakhs)\n\nDIFFERENCE: Starting 10 years earlier = 3× more corpus\nwith only 1.77× more investment\n\nRule of 72: Years to double = 72 / interest rate\nAt 12%: doubles every 6 years\nAt 6%:  doubles every 12 years`, explanation: 'Time in market beats timing the market. Starting SIPs even with small amounts at age 22 dramatically outperforms starting at 32.' }],
        keyPoints: ['Emergency fund first — investing without a liquid buffer forces selling investments at the worst times (during market crashes)', 'Term insurance is dramatically cheaper than endowment/ULIP policies for the same cover amount — buy pure term + invest the difference', 'Tax efficiency: ELSS gives 80C deduction; PPF returns are tax-free; LTCG on equity >₹1L taxed at 10% — location of investments matters']
      },
      evaluate: { questions: [{ question: 'In the 50/30/20 budgeting rule, the 20% should go to:', options: ['Rent and utilities', 'Dining and travel', 'Savings and debt repayment', 'Taxes'], correctIndex: 2, explanation: 'The 50/30/20 rule: 50% needs, 30% wants, 20% savings/debt repayment. The savings component builds long-term wealth.' }, { question: 'Why is term insurance recommended over endowment policies?', options: ['Term insurance pays out more in all cases', 'Term insurance provides high pure risk cover at much lower premiums — invest the premium savings separately', 'Endowment policies are illegal', 'Term insurance is tax-free always'], correctIndex: 1, explanation: 'Endowment mixes insurance + investment poorly. Term insurance is pure protection at low cost. Invest the saved premiums separately for better returns.' }, { question: 'Rule of 72 states:', options: ['Save 72% of income', 'Invest in 72 different assets', 'Years to double money = 72 ÷ annual interest rate', 'Keep 72 months of expenses in savings'], correctIndex: 2, explanation: 'Rule of 72: at 12% return, money doubles in 72/12 = 6 years. A quick mental shortcut for compound interest.' }] }
    },
    'Wealth Management': {
      understand: {
        theory: `# Wealth Management\n## What is Wealth Management?\nWealth management is a comprehensive advisory service combining investment management, financial planning, tax optimisation, estate planning, and risk management for HNI/UHNI clients.\n\n## Asset Allocation\nThe most important wealth management decision — determines 90%+ of portfolio returns over time.\n\n**Strategic Asset Allocation (SAA)**: Long-term target weights\n**Tactical Asset Allocation (TAA)**: Short-term deviations based on market views\n\nSample allocation (35-year-old, moderate risk):\n- Domestic equity: 45%\n- International equity: 15%\n- Debt (bonds/FDs): 25%\n- Real estate/REITs: 10%\n- Gold/commodities: 5%\n\n## Private Banking Services for HNIs\n- PMS (Portfolio Management Services): SEBI-regulated; min. ₹50 Lakhs; direct stock ownership\n- AIF (Alternative Investment Fund): PE, VC, hedge funds; min. ₹1 Crore\n- Structured Products: Capital protection with equity-linked returns\n- Family Office: Multi-generational wealth management with dedicated team`,
        examples: [{ title: 'Goal-based financial planning', language: 'text', code: `CLIENT: Age 35, married, 2 children\nGoals:\n1. Child 1 education (age 18, 8 years): ₹60 Lakhs (today's value)\n2. Child 2 education (age 18, 12 years): ₹60 Lakhs\n3. Retirement (age 60, 25 years): ₹5 Crore corpus (today's value)\n\nFUTURE VALUES (6% inflation):\nChild 1: ₹60L × (1.06)^8 = ₹95.6L\nChild 2: ₹60L × (1.06)^12 = ₹1.2 Cr\nRetirement: ₹5 Cr × (1.06)^25 = ₹21.4 Cr\n\nMONTHLY SIP NEEDED (at 12% equity returns):\nChild 1 fund: ~₹55,000/month\nChild 2 fund: ~₹25,000/month\nRetirement fund: ~₹60,000/month\n\nSTRATEGY:\n• Child education: Balanced fund (reduce equity near goal)\n• Retirement: Aggressive equity now; shift to debt after 50`, explanation: 'Goal-based planning creates separate mental accounts for each goal — each with appropriate risk level and review period.' }],
        keyPoints: ['Asset allocation is the primary determinant of long-term returns — security selection and market timing have far less impact (Brinson et al. study)', 'Rebalancing annually maintains target allocation — forces disciplined selling of over-performing assets and buying under-performing ones', 'Estate planning in India: nomination for all financial instruments + Will (registered preferred) + consideration of HUF structure for tax efficiency']
      },
      evaluate: { questions: [{ question: 'Strategic Asset Allocation (SAA) is:', options: ['Daily trading decisions based on market conditions', 'Long-term target portfolio weights based on risk tolerance, goals, and investment horizon', 'Only for institutional investors', 'The allocation within equity between large/mid/small cap'], correctIndex: 1, explanation: 'SAA sets long-term target weights that align with the client\'s risk tolerance and goals. Tactical AA deviates short-term based on market views.' }, { question: 'PMS (Portfolio Management Services) in India requires a minimum investment of:', options: ['₹5 Lakhs', '₹50 Lakhs', '₹1 Crore', '₹10 Crores'], correctIndex: 1, explanation: 'SEBI mandates a minimum investment of ₹50 Lakhs for Portfolio Management Services. PMS offers direct stock ownership vs. mutual fund pools.' }, { question: 'The primary purpose of annual portfolio rebalancing is:', options: ['To maximise returns by chasing winners', 'To restore target asset allocation that drifts due to varying returns across asset classes', 'To minimise taxes', 'To reduce the number of holdings'], correctIndex: 1, explanation: 'Rebalancing restores target weights. It forces selling outperforming assets (high valuation) and buying underperforming ones (low valuation) — disciplined and counter-cyclical.' }] }
    },
  },
};
