export const LAW_CONTENT: Record<string, Record<string, any>> = {
  'Contract Law': {
    'Formation of Contracts': {
      understand: {
        theory: `# Formation of Contracts\nA valid contract requires **4 essential elements**:\n1. **Offer** — a definite proposal to contract on specific terms\n2. **Acceptance** — unconditional agreement to all terms of the offer (mirror image rule)\n3. **Consideration** — something of value exchanged by each party ("bargained-for exchange")\n4. **Capacity + Legality** — parties must be competent; purpose must be legal\n\n## Key Rules\n**Offer vs. Invitation to Treat**\nPrices in catalogues, advertisements, and shop windows are generally *invitations to treat* — not offers. The customer's act of ordering is the offer.\n\n**Acceptance Rules**\n- Must be communicated to the offeror\n- **Postal Rule**: acceptance takes effect when letter is posted (not received) — in India governed by Section 4 of Indian Contract Act 1872\n- Silence is not acceptance\n- Counter-offer kills the original offer\n\n**Consideration**\n- Must be sufficient (has some value in law) but need not be adequate (can be nominal)\n- Past consideration is no consideration\n- Existing duty rule: doing what you are already legally obliged to do is not consideration`,
        examples: [{ title: 'Counter-offer scenario', language: 'text', code: `Timeline:\nDay 1 - A offers to sell a plot to B for ₹50L\nDay 2 - B replies: "I'll buy it for ₹45L"\n          → This is a COUNTER-OFFER (not acceptance)\n          → A's original offer is TERMINATED\nDay 3 - B says "Actually, I'll pay ₹50L"\n          → This is a NEW offer by B, not acceptance of A's offer\n          → A is under no obligation to accept\n\nLegal principle: Hyde v Wrench (1840) — counter-offer\ndestroys the original offer; it cannot be revived.`, explanation: 'Counter-offers end the original offer. This is why commercial negotiations often use "subject to contract" language to preserve options.' }],
        keyPoints: ['Advertisements are generally invitations to treat, not offers — the shop/seller can refuse to sell (Pharmaceutical Society v Boots)', 'Consideration must move from the promisee (the person receiving the promise must give something in return)', 'In India: Indian Contract Act 1872, Section 2(a)-(h) defines offer, acceptance, promise, consideration, agreement, and contract']
      },
      evaluate: { questions: [{ question: 'A price tag on a product in a shop is legally classified as:', options: ['An offer', 'An invitation to treat', 'A binding contract', 'A guarantee'], correctIndex: 1, explanation: 'Price displays are invitations to treat (Pharmaceutical Society v Boots). The customer makes an offer at the counter; the seller accepts or refuses.' }, { question: 'Past consideration is:', options: ['Valuable consideration from the past that still counts', 'Not valid consideration — past acts cannot be bargained for now', 'Only valid if both parties agree', 'Valid in Indian courts only'], correctIndex: 1, explanation: 'Consideration must be given in exchange for the promise — a past act already done cannot constitute future consideration.' }, { question: 'What effect does a counter-offer have on the original offer?', options: ['Suspends it temporarily', 'Terminates the original offer completely', 'Modifies it automatically', 'Has no effect'], correctIndex: 1, explanation: 'A counter-offer rejects and terminates the original offer (Hyde v Wrench 1840). The original cannot be revived without a new offer from the original offeror.' }] }
    },
    'Breach & Remedies': {
      understand: {
        theory: `# Breach of Contract & Remedies\n## Types of Breach\n- **Actual breach**: Party fails to perform when performance is due\n- **Anticipatory breach**: Party repudiates contract before performance is due (Hochster v De La Tour)\n- **Material breach**: Goes to the root of the contract — innocent party can terminate + claim damages\n- **Minor/partial breach**: Does not go to root — only damages (not termination)\n\n## Remedies\n### Damages\n- **Expectation damages**: Put claimant in position as if contract performed (loss of bargain)\n- **Reliance damages**: Reimburse wasted expenditure in reliance on the contract\n- **Consequential damages**: Must satisfy *Hadley v Baxendale* test — losses must be within reasonable contemplation of parties at time of contract\n- **Liquidated damages**: Pre-agreed damages clause — enforceable if genuine estimate of loss\n- **Penalty clause**: Designed to punish, not compensate — void in common law\n\n### Equitable Remedies (court discretion)\n- **Specific Performance**: Order to actually perform (rare; for unique goods/property)\n- **Injunction**: Order to stop or compel an act`,
        examples: [{ title: 'Remoteness of damage — Hadley v Baxendale test', language: 'text', code: `FACTS:\nMill owner sends broken crankshaft to repairer.\nDue to carrier's delay, mill is idle longer.\nMill owner claims lost profits as damages.\n\nTEST (2 limbs):\n1. Arising naturally from breach (foreseeable to any person)\n2. In contemplation of BOTH parties at time of contract\n\nRULING:\nCarrier did NOT know the mill would stop without this\nspecific crankshaft → lost profits NOT in contemplation\n→ Not recoverable\n\nPRACTICAL LESSON:\nDisclose unusual/high-stakes circumstances to the other\nparty at contract formation — or they cannot be liable\nfor that loss.`, explanation: 'Hadley v Baxendale (1854) is the foundational remoteness test. Tell the other party about special circumstances at formation — or you cannot recover for them.' }],
        keyPoints: ['Anticipatory breach allows the innocent party to sue immediately — they need not wait for the breach date (Hochster v De La Tour)', 'Mitigation: the innocent party has a duty to mitigate losses — cannot claim damages for losses that could reasonably have been avoided', 'Specific performance is only granted for unique items (land, art) — courts cannot supervise ongoing performance obligations']
      },
      evaluate: { questions: [{ question: 'Anticipatory breach occurs when:', options: ['A party performs partially', 'A party repudiates the contract before the performance date arrives', 'Both parties breach simultaneously', 'A third party interferes with the contract'], correctIndex: 1, explanation: 'Anticipatory breach allows the innocent party to treat the contract as terminated immediately and claim damages without waiting for the performance date.' }, { question: 'The Hadley v Baxendale rule governs:', options: ['Acceptance of contracts', 'Which losses are too remote to be recoverable as damages', 'Formation of consideration', 'Termination rights'], correctIndex: 1, explanation: 'Hadley v Baxendale: recoverable damages are those arising naturally from the breach OR in the contemplation of both parties at contract formation.' }, { question: 'A penalty clause (as opposed to liquidated damages) is:', options: ['Valid and enforceable', 'Void — courts will not enforce punitive damages', 'Only valid in commercial contracts', 'Permitted in Indian law'], correctIndex: 1, explanation: 'Penalty clauses designed to punish rather than estimate genuine loss are void in common law. Liquidated damages clauses (genuine pre-estimates) are enforceable.' }] }
    },
    'Terms & Conditions': {
      understand: {
        theory: `# Contract Terms & Their Classification\n## Types of Terms\n**Conditions** — fundamental terms; breach entitles innocent party to terminate AND claim damages\n**Warranties** — less important terms; breach only entitles damages (not termination)\n**Innominate terms** — classified by consequences of breach (Hong Kong Fir Shipping Co v Kawasaki)\n\n## Implied Terms\n- **By statute**: e.g., Sale of Goods Act — goods must be of satisfactory quality\n- **By fact**: necessary to give effect to party intentions (*The Moorcock* test — business efficacy)\n- **By law**: automatically imported into certain contract types\n\n## Exclusion Clauses\nCan a party exclude liability? Requirements:\n1. **Incorporation**: Must be incorporated into the contract (notice before agreement; not after)\n2. **Construction**: Must cover the type of loss claimed (interpreted *contra proferentem* against the party relying on it)\n3. **Statutory control**: Unfair Contract Terms Act 1977 (UK) / Consumer Protection Act 2019 (India) — exclusions of negligence liability for personal injury are VOID`,
        examples: [{ title: 'Exclusion clause — reasonable notice test', language: 'text', code: `SCENARIO:\nHotel posts sign at reception: "Not liable for loss of\nguest property" — AFTER guests check in.\n\nLEGAL ANALYSIS:\n✗ Not incorporated — notice must come BEFORE contract\n  formation (Olley v Marlborough Court [1949])\n\nCONTRAST:\nTicket bought at parking gate says on back:\n"No liability for damage to vehicles"\n→ Incorporation depends on reasonableness of notice;\n  unusual/onerous terms require specific attention\n  (Interfoto Picture Library v Stiletto)\n\nBEST PRACTICE FOR BUSINESSES:\n• Exclusions in signed contract = clearly incorporated\n• Tick-box + bold text in T&Cs = good evidence of notice`, explanation: 'Exclusion clauses must be incorporated before the contract is made. Post-contract notices have no effect.' }],
        keyPoints: ['Condition breach → terminate + damages. Warranty breach → damages only. Innominate term → depends on severity of consequences', 'Exclusion clauses are interpreted contra proferentem — any ambiguity is construed against the party seeking to rely on it', 'In consumer contracts, the test is reasonableness and fairness — unfair terms are not enforceable against consumers']
      },
      evaluate: { questions: [{ question: 'What is the difference between a condition and a warranty?', options: ['No legal difference', 'Conditions are fundamental — breach allows termination; warranties are minor — breach only gives damages', 'Warranties are conditions in consumer contracts', 'Conditions can only be breached intentionally'], correctIndex: 1, explanation: 'Condition breach = right to terminate + damages. Warranty breach = damages only. The classification matters enormously in contract disputes.' }, { question: 'Contra proferentem rule means:', options: ['Ambiguous exclusion clauses are interpreted against the party relying on them', 'All exclusion clauses are void', 'Exclusion clauses must be in Latin', 'Ambiguity favours the seller'], correctIndex: 0, explanation: 'Contra proferentem: ambiguity in a contract term is construed against the drafter/the party seeking to benefit from it.' }, { question: 'An exclusion clause on a sign put up after the customer has already booked is:', options: ['Fully effective', 'Not incorporated into the contract — notice came too late', 'Valid if highlighted clearly', 'Valid only if the customer saw it'], correctIndex: 1, explanation: 'For an exclusion clause to be valid, reasonable notice must be given BEFORE or AT the time of contracting (Olley v Marlborough Court).' }] }
    },
    'Misrepresentation & Mistake': {
      understand: {
        theory: `# Misrepresentation & Mistake\n## Misrepresentation\nA false statement of fact (not opinion or future intention) that induces the other party to enter the contract.\n\n**Types:**\n- **Fraudulent**: Knowingly false or recklessly careless — damages in tort + rescission\n- **Negligent**: Without reasonable grounds for belief — Misrepresentation Act 1967 (or Section 17-18 ICA)\n- **Innocent**: Genuinely believed true — rescission only (no damages)\n\n**Remedies:**\n- Rescission (set contract aside — puts parties back to pre-contract position)\n- Damages (only for fraudulent and negligent misrep.)\n\n## Mistake\nNot every mistake vitiates a contract. English law is strict.\n\n**Common Mistake**: Both parties share the same wrong belief\n- res extincta (subject matter never existed) → void\n- mistake as to quality → generally does NOT void (Bell v Lever Bros)\n\n**Mutual Mistake**: Parties are at cross-purposes — court looks for objective agreement\n\n**Unilateral Mistake**: One party mistaken; other knows → may be void for fraud`,
        examples: [{ title: 'Fraudulent vs. Innocent Misrepresentation', language: 'text', code: `SCENARIO:\nA sells B a car, saying "100% accident-free"\n\nCASE 1 — FRAUDULENT:\nA knows the car was in 3 accidents\n→ B can rescind contract AND claim full damages in deceit\n→ Derry v Peek (1889): fraud = statement made knowing it\n   is false, or recklessly without caring if true or false\n\nCASE 2 — NEGLIGENT:\nA believes it's accident-free but never checked\n→ B can rescind + claim damages\n→ S.2(1) Misrepresentation Act 1967 reverses burden:\n   A must prove reasonable grounds for belief\n\nCASE 3 — INNOCENT:\nA genuinely believed + had good reasons\n→ B can rescind only (no damages)`, explanation: 'The type of misrepresentation determines remedies. Burden of proof under Misrepresentation Act 1967 s.2(1) shifts to the misrepresentor.' }],
        keyPoints: ['Misrepresentation must be of FACT — not opinion (Bissett v Wilkinson) or future intention, unless made without intent to fulfil', 'Rescission is lost if: affirmation, lapse of time, third party rights intervene, or restitution is impossible', 'In India: Section 17 (fraud), Section 18 (misrepresentation), Section 20 (mistake) of the Indian Contract Act 1872']
      },
      evaluate: { questions: [{ question: 'Which type of misrepresentation allows the innocent party to claim both rescission AND damages?', options: ['Innocent only', 'Fraudulent and negligent', 'All three types', 'Only fraudulent'], correctIndex: 1, explanation: 'Innocent misrepresentation: rescission only. Fraudulent and negligent: rescission + damages.' }, { question: 'A statement of opinion (e.g. "This is a great investment") is:', options: ['Always fraudulent misrepresentation', 'Not a misrepresentation of fact unless the speaker had no genuine belief in it', 'Always actionable', 'Treated as a condition of the contract'], correctIndex: 1, explanation: 'Pure opinions are not statements of fact. But if the speaker does not genuinely hold the opinion, it can be fraudulent misrepresentation.' }, { question: 'Res extincta in the context of common mistake means:', options: ['The contract price was wrong', 'The subject matter did not exist at contract formation — contract is void', 'The contract was signed by the wrong person', 'The goods were of poor quality'], correctIndex: 1, explanation: 'If the subject matter of the contract never existed or had already perished at formation (res extincta), the contract is void for common mistake.' }] }
    },
    'Indian Contract Act 1872': {
      understand: {
        theory: `# Indian Contract Act 1872 — Key Provisions\nThe ICA is the primary statute governing contracts in India. It codifies common law principles with Indian-specific provisions.\n\n## Definitions (Section 2)\n- **Proposal/Offer** (s.2a): When one person signifies willingness to do or abstain\n- **Acceptance** (s.2b): When the person to whom the proposal is made signifies assent\n- **Promise** (s.2b): Accepted proposal\n- **Agreement** (s.2e): Every promise + every set of promises forming consideration\n- **Contract** (s.2h): An agreement enforceable by law\n\n## Void, Voidable, and Void Agreements\n- **Void agreement** (s.2g): Not enforceable by law from the beginning\n- **Voidable contract** (s.2i): Enforceable at the option of one party (e.g., coercion)\n- **Void contract** (s.2j): Valid when made but ceases to be enforceable (frustration)\n\n## Free Consent (s.14)\nConsent is free unless caused by: coercion (s.15), undue influence (s.16), fraud (s.17), misrepresentation (s.18), or mistake (s.20-22)\n\n## Specific Relief Act, 1963\nSpecific performance, injunctions, rectification — statutory remedies in India`,
        examples: [{ title: 'Coercion vs. Undue Influence under ICA', language: 'text', code: `COERCION (Section 15):\nCommitting or threatening to commit any act forbidden by IPC,\nor unlawful detaining property to obtain consent.\n\nExample: A threatens B with physical harm unless B signs\nthe property transfer → Voidable at B's option\n\nUNDUE INFLUENCE (Section 16):\nDominating the will of another to obtain unfair advantage.\nPresumption: Parent-child, guardian-ward, doctor-patient,\nadvocate-client, spiritual adviser-disciple\n\nExample: A doctor convinces a very ill, dependent patient to\nbequeath all property to the doctor → Presumed undue influence\n→ Burden shifts to doctor to prove transaction was fair\n\nKEY DIFFERENCE:\nCoercion = physical/criminal force\nUndue Influence = psychological/positional dominance`, explanation: 'Free consent is foundational to Indian contract law. Either vitiating factor makes the contract voidable — not automatically void.' }],
        keyPoints: ['Under ICA, a minor\'s agreement is void ab initio (absolutely void) — not merely voidable. No ratification upon majority (Mohori Bibee v Dharmodas Ghosh 1903)', 'Consideration may be past, present, or future under Indian law (s.2d) — unlike English law which requires present/future consideration', 'Section 73 ICA: compensation for loss or damage naturally arising from breach; remote/indirect consequences excluded']
      },
      evaluate: { questions: [{ question: 'Under the Indian Contract Act, a minor\'s agreement is:', options: ['Valid with parental consent', 'Voidable at the minor\'s option', 'Void ab initio — absolutely void from the beginning', 'Valid until the minor turns 18'], correctIndex: 2, explanation: 'Mohori Bibee v Dharmodas Ghosh (1903): a minor\'s contract is void ab initio. A minor cannot ratify it upon reaching majority.' }, { question: 'Free consent under Section 14 ICA is vitiated by how many factors?', options: ['3', '4', '5', '6'], correctIndex: 2, explanation: 'Five vitiating factors: coercion (s.15), undue influence (s.16), fraud (s.17), misrepresentation (s.18), mistake (s.20-22).' }, { question: 'An agreement without consideration is generally:', options: ['Valid in Indian law', 'Void — unless it falls under exceptions in Section 25', 'Voidable', 'A criminal offence'], correctIndex: 1, explanation: 'Section 25 ICA: agreement without consideration is void, with narrow exceptions (love and affection, past voluntary service, time-barred debt).' }] }
    },
    'Digital Contracts & E-Commerce Law': {
      understand: {
        theory: `# Digital Contracts & E-Commerce Law in India\n## Information Technology Act, 2000 (IT Act)\n- Section 10A: Contracts concluded through electronic means are valid\n- Electronic records and digital signatures have legal validity\n- **Electronic signature** (s.2(ta)): Encompasses Aadhaar-based eSign, DSC\n- **Digital signature** (DSC): More secure; uses asymmetric cryptography\n\n## Click-Wrap vs. Browse-Wrap Agreements\n- **Click-wrap**: User actively checks "I Agree" — generally enforceable\n- **Browse-wrap**: T&Cs accessible via link; user implicitly agrees by using the service — weaker enforceability\n\n## Consumer Protection (E-Commerce) Rules, 2020\n- Mandatory disclosures: seller info, return policy, delivery terms, price breakdown\n- No dark patterns, deceptive reviews, or misleading advertisements\n- Grievance Officer must be appointed\n- Return/refund must be processed within 7 days\n\n## Data Protection\n- **DPDP Act 2023** (Digital Personal Data Protection Act): Consent-based data processing, data principal rights, significant penalties for breaches`,
        examples: [{ title: 'E-contract formation timeline', language: 'text', code: `SCENARIO: User buys a SaaS subscription online\n\nStep 1: Website displays pricing + features (Invitation to Treat)\nStep 2: User clicks "Subscribe Now" (Offer by user)\nStep 3: User reviews T&Cs → clicks "I Agree" + "Pay" (Acceptance)\nStep 4: Payment gateway processes → Success email sent\n→ Contract formed at Step 3/4 when payment accepted\n\nIT Act s.12: Contract formed when acceptance is received\nby the proposer (at the server/system)\n\nLEGAL REQUIREMENTS:\n✓ T&Cs must be accessible and legible\n✓ Clear opt-in (not pre-checked boxes for auto-renewal)\n✓ Order confirmation must be sent immediately\n✓ Cancellation must be as easy as subscription`, explanation: 'The IT Act 2000 and Consumer Protection Rules 2020 govern e-contracts in India. Auto-renewal without clear disclosure is a common compliance failure.' }],
        keyPoints: ['Section 10A IT Act validates e-contracts — no requirement for physical signatures if IT Act requirements are met', 'DPDP Act 2023 requires explicit consent for personal data processing — implied consent or bundled consent is insufficient', 'Dark patterns (hidden unsubscribe, forced continuity, roach motel) violate Consumer Protection Act 2019 and CCPA guidelines']
      },
      evaluate: { questions: [{ question: 'Section 10A of the IT Act 2000 provides:', options: ['Criminal penalties for data breaches', 'Legal validity of contracts formed through electronic means', 'Rules for cybercrime investigation', 'Standards for digital signatures only'], correctIndex: 1, explanation: 'Section 10A: "Where in a contract formation, the communication of proposals, the revisions of proposals, acceptance and revocation are expressed in electronic form...such contracts shall not be deemed to be unenforceable..."' }, { question: 'A Browse-wrap agreement is:', options: ['Always legally binding', 'Weaker than click-wrap — user must be shown and acknowledge terms for strong enforceability', 'Prohibited under Indian law', 'Equivalent to a handwritten signature'], correctIndex: 1, explanation: 'Browse-wrap (T&Cs linked on a webpage) has weaker enforceability. Click-wrap (active "I Accept" click) is significantly stronger.' }, { question: 'Under Consumer Protection (E-Commerce) Rules 2020, return/refund must be processed within:', options: ['3 days', '7 days', '15 days', '30 days'], correctIndex: 1, explanation: 'Rule 6(4): E-commerce entities must process returns and refunds within 7 days after the product is returned.' }] }
    },
    'Arbitration & Dispute Resolution': {
      understand: {
        theory: `# Arbitration & Dispute Resolution\n## ADR Methods\n1. **Negotiation** — direct party-to-party; no third party; most flexible\n2. **Mediation** — neutral third party (mediator) facilitates settlement; non-binding\n3. **Arbitration** — neutral third party (arbitrator) decides; binding; like private court\n4. **Conciliation** — like mediation but conciliator can propose solutions\n5. **Lok Adalat** — statutory ADR in India; compromised/settled disputes; decree is final\n\n## Arbitration & Conciliation Act, 1996 (India)\n- Domestic and international commercial arbitration\n- **Arbitral tribunal**: 1 or 3 arbitrators\n- **Arbitral award**: Final and binding; enforceable like a court decree\n- **Section 34**: Award can be set aside only on limited grounds (incapacity, improper notice, fraud, public policy)\n- **Seat vs. Venue**: Seat determines governing law of arbitration; venue is physical location\n\n## Arbitration Clause (Model)\n> "All disputes arising out of or in connection with this agreement shall be finally settled under the Arbitration and Conciliation Act, 1996. The arbitral tribunal shall consist of a sole arbitrator mutually appointed. Seat of arbitration: New Delhi. Language: English."`,
        examples: [{ title: 'When to choose arbitration vs. litigation', language: 'text', code: `ARBITRATION ADVANTAGES:\n✓ Confidential — no public court records\n✓ Faster — typically 12-18 months vs 5-10 years in Indian courts\n✓ Expert arbitrators (technical/commercial disputes)\n✓ International enforceability (New York Convention — 170 countries)\n✓ Finality — limited grounds to appeal (s.34)\n\nARBITRATION DISADVANTAGES:\n✗ No appeal on merits — stuck with wrong decision\n✗ Expensive — arbitrator fees + institutional fees\n✗ No precedent value — cannot rely on past awards\n✗ Limited discovery/evidence tools vs. court\n\nCHOOSE ARBITRATION FOR:\n• High-value commercial contracts\n• International parties (enforcement via New York Convention)\n• Technical disputes (construction, engineering, IP)`, explanation: 'Arbitration is not always better than litigation — for small claims or where precedent matters, court may be preferable.' }],
        keyPoints: ['India is a signatory to the New York Convention — foreign arbitral awards are enforceable in Indian courts (and vice versa)', 'Section 11 ACA: If parties cannot agree on arbitrator, the High Court/Supreme Court appoints one', 'SEBI, NCLT, RERA — many Indian regulatory tribunals are specialist ADR bodies with faster resolution than civil courts']
      },
      evaluate: { questions: [{ question: 'The key difference between mediation and arbitration is:', options: ['Cost', 'Arbitration produces a binding decision; mediation facilitates a voluntary settlement', 'Number of parties', 'Government involvement'], correctIndex: 1, explanation: 'Mediation is a facilitated negotiation — the mediator has no power to impose a decision. Arbitration produces a binding award like a judgment.' }, { question: 'Under Section 34 ACA, an arbitral award can be set aside when:', options: ['Any party disagrees with the reasoning', 'On very limited grounds: incapacity, improper notice, fraud, or contravention of public policy', 'The award is unfair in the court\'s opinion', 'One arbitrator dissented'], correctIndex: 1, explanation: 'Section 34 grounds are narrow — you cannot appeal arbitration on merits. This finality is both the strength and risk of arbitration.' }, { question: 'The New York Convention (1958) is significant for arbitration because:', options: ['It sets arbitration fees globally', 'Foreign arbitral awards signed under it are enforceable in 170+ member countries', 'It created the ICC Arbitration Centre', 'It mandates arbitration for trade disputes'], correctIndex: 1, explanation: 'The New York Convention enables international commercial arbitral awards to be recognised and enforced in 170+ signatory countries.' }] }
    },
    'Corporate & Securities Law Basics': {
      understand: {
        theory: `# Corporate & Securities Law Basics\n## Company Formation (Companies Act 2013)\n**Types of companies:**\n- **Private Limited (Pvt Ltd)**: 2-200 shareholders; restricted transfer; min. 2 directors\n- **Public Limited (Ltd)**: 7+ shareholders; freely transferable shares; min. 3 directors\n- **OPC (One Person Company)**: Single shareholder + nominee; for solo entrepreneurs\n- **LLP (Limited Liability Partnership)**: Partnership + limited liability; governed by LLP Act 2008\n\n**Incorporation process**: MCA21 portal → Name reservation (RUN) → SPICe+ form → PAN/TAN → COI (Certificate of Incorporation)\n\n## Securities Law — SEBI Act 1992\n- **SEBI** (Securities and Exchange Board of India): Regulates capital markets\n- **Insider Trading** (PIT Regulations 2015): Trading on UPSI (Unpublished Price Sensitive Information) is prohibited\n- **Takeover Code** (SAST Regulations 2011): 25%+ acquisition triggers mandatory open offer\n- **IPO Process**: DRHP → SEBI review → Red Herring Prospectus → Roadshow → Allotment`,
        examples: [{ title: 'Choosing the right business structure', language: 'text', code: `STARTUP COMPARISON:\n\n| Feature | OPC | Pvt Ltd | LLP |\n|---------|-----|---------|-----|\n| Min. members | 1 | 2 | 2 |\n| Min. directors | 1 | 2 | 2 designated partners |\n| VC investment | ✗ | ✓ | Limited |\n| Compliance | Moderate | High | Low |\n| Tax rate | 22%+surcharge | 22%+surcharge | 30% (partners) |\n| Liability | Limited | Limited | Limited |\n\nRECOMMENDATION:\n• Solo founder, not seeking VC → OPC\n• Co-founders, seeking VC/ESOP → Pvt Ltd (most common)\n• Service partnerships, professional firms → LLP`, explanation: 'Pvt Ltd is the standard choice for venture-backed startups in India — ESOP, convertible notes, and institutional investment all require it.' }],
        keyPoints: ['A Pvt Ltd company is a separate legal entity — can own property, sue, and be sued independently of its shareholders', 'Insider trading in India is governed by SEBI (PIT) Regulations 2015 — trading on UPSI is a civil and criminal offence', 'Directors owe fiduciary duties to the company: duty of care, duty of loyalty, duty to act within powers (Companies Act 2013, s.166)']
      },
      evaluate: { questions: [{ question: 'The minimum number of shareholders to form a Private Limited Company in India is:', options: ['1', '2', '7', '50'], correctIndex: 1, explanation: 'A Pvt Ltd requires minimum 2 and maximum 200 shareholders. A single-person company uses OPC structure.' }, { question: 'Insider trading refers to:', options: ['Company insiders sitting on competitor boards', 'Trading securities on the basis of UPSI (Unpublished Price Sensitive Information)', 'Insider employee stock option grants', 'Large block trades by institutions'], correctIndex: 1, explanation: 'SEBI PIT Regulations 2015: trading on UPSI (material non-public information) is prohibited insider trading — civil and criminal consequences.' }, { question: 'Under SEBI\'s Takeover Code, an acquirer must make an open offer when they cross:', options: ['15% shareholding', '25% shareholding in a listed company', '51% shareholding', '75% shareholding'], correctIndex: 1, explanation: 'SEBI (SAST) Regulations 2011: acquiring 25%+ voting rights triggers a mandatory open offer to buy at least 26% more from public shareholders.' }] }
    },
  },

  'Corporate Law': {
    'Company Formation & Structure': {
      understand: {
        theory: `# Company Formation & Structure\n## Doctrine of Separate Legal Personality\nA company is a person in law, distinct from its members. Landmark case: **Salomon v Salomon & Co Ltd [1897]** — even a sole trader could incorporate; company's debts are not the trader's debts.\n\n## Lifting/Piercing the Corporate Veil\nCourts will disregard the separate personality in limited circumstances:\n- **Fraud/Sham**: Company used as façade for fraud\n- **Agency**: Company acting as agent for its controller\n- **Enemy alien**: Wartime — foreign control\n- **Statutory lifting**: Tax laws, group liability provisions\n\n## Share Capital\n- **Authorised capital**: Maximum a company can issue\n- **Issued capital**: Actually issued to shareholders\n- **Paid-up capital**: Amount actually paid on issued shares\n- **Calls in arrears**: Called-up but unpaid amount\n\n## Memorandum & Articles of Association\n- **MoA**: Objects clause, liability clause, capital clause — external constitution\n- **AoA**: Internal management rules — can be altered by special resolution`,
        examples: [{ title: 'Salomon principle in practice', language: 'text', code: `SALOMON v SALOMON [1897]:\nMr. Salomon incorporated his boot business.\nHe held 20,001 of 20,007 shares.\nCompany borrowed from him (secured debenture).\nCompany went insolvent. Unsecured creditors claimed his\ndebenture should yield to their claims — "he IS the company"\n\nHOUSE OF LORDS: Company is a separate legal person.\nHis debenture ranks ahead of unsecured creditors.\n\nModern Application:\nStartup founder: Personal assets PROTECTED from company debts\n(assuming proper corporate formalities maintained)\n\nEXCEPTION: Veil pierced in VTB Capital plc v Nutritek [2013]\nonly for "creatures" of the same controller acting in fraud`, explanation: 'Salomon established the fundamental principle of limited liability. The corporate form ONLY protects if proper records, accounts, and shareholder meetings are maintained.' }],
        keyPoints: ['Salomon principle: company is separate from its members — foundational to corporate law and the basis of limited liability', 'Veil lifting is exceptional — courts are very reluctant. The company must be used as a deliberate sham to commit fraud', 'In India: Companies Act 2013 introduced OPC, harmonised corporate governance with global standards, created NCLT (National Company Law Tribunal)']
      },
      evaluate: { questions: [{ question: 'The Salomon case established the principle that:', options: ['Shareholders are liable for company debts', 'A company is a separate legal person from its members', 'Creditors have first claim over shareholders', 'Small companies cannot incorporate'], correctIndex: 1, explanation: 'Salomon v Salomon [1897] held that a company has separate legal personality — it can enter contracts, own property, and incur debts independently of its members.' }, { question: 'Piercing the corporate veil means:', options: ['Issuing new share capital', 'Courts disregard the company\'s separate personality to hold members/directors personally liable', 'Auditing the company\'s accounts', 'Dissolving the company'], correctIndex: 1, explanation: 'Veil piercing makes the person behind the company personally liable — only in exceptional circumstances like fraud or sham.' }, { question: 'The Memorandum of Association defines:', options: ['Internal management rules only', 'The company\'s external constitution: objects, liability, and capital — its relationship with the outside world', 'Director remuneration', 'Shareholder voting procedures'], correctIndex: 1, explanation: 'MoA governs the company\'s external relationship. AoA governs internal management. Together they form the constitution of the company.' }] }
    },
    'Directors\' Duties': {
      understand: {
        theory: `# Directors' Duties\n## Statutory Duties — Companies Act 2013 (India), s.166\n1. **Act in accordance with AoA** — within powers\n2. **Promote success** — act in good faith for benefit of company\n3. **Exercise independent judgment** — don't fetter discretion\n4. **Exercise reasonable care, skill, and diligence** — objective minimum + subjective expertise\n5. **Avoid conflicts of interest** — don't profit from position without disclosure\n6. **Not accept benefits from third parties**\n7. **Declare interest in transactions** — statutory disclosure\n\n## Business Judgment Rule\nCourts will not second-guess genuine business decisions if:\n- Director was informed\n- Acted in good faith\n- Rationally believed it was in company's interest\n\n## Wrongful Trading vs. Fraudulent Trading\n- **Wrongful trading**: Director continued trading knowing insolvent with no reasonable prospect of avoiding liquidation — personal liability for company debts\n- **Fraudulent trading**: Deliberate fraud — criminal offence`,
        examples: [{ title: 'Conflict of interest in practice', language: 'text', code: `SCENARIO:\nDirector of TechCo (software company) is also a 40%\nshareholder of DesignLtd (a design agency).\n\nTechCo is considering outsourcing its UI/UX to DesignLtd.\n\nLEGAL OBLIGATIONS:\n1. Director MUST declare conflict at Board meeting (s.184 CA2013)\n2. Director cannot vote on the resolution (unless AoA permits)\n3. Board approves the contract independently\n\nIF NOT DISCLOSED:\n• Contract voidable by the company\n• Director must account for any profit made\n• Possible removal from board\n• Civil liability to company\n\nBEST PRACTICE:\n• Conflict register maintained by Company Secretary\n• Annual declaration of interests (Form MBP-1 in India)`, explanation: 'Conflicts of interest must be proactively disclosed — not just avoided. The duty is to declare and recuse, not simply to decline related opportunities.' }],
        keyPoints: ['Directors owe duties to the COMPANY — not directly to individual shareholders, creditors (except near insolvency), or employees', 'The business judgment rule protects reasonable, informed decisions even if they turn out wrong — it is not a guarantee of success', 'Shadow directors (those whose instructions the board follows) owe the same duties as formal directors']
      },
      evaluate: { questions: [{ question: 'Directors\' duties under the Companies Act are owed to:', options: ['Individual shareholders', 'The company as a whole (and creditors when near insolvency)', 'Employees first', 'The government'], correctIndex: 1, explanation: 'Directors primarily owe duties to the company. They owe duties to creditors only when the company is insolvent or near insolvency.' }, { question: 'The Business Judgment Rule protects directors who:', options: ['Always make profitable decisions', 'Make informed, good-faith decisions rationally believed to be in the company\'s interest', 'Consult all shareholders before deciding', 'Avoid all risky decisions'], correctIndex: 1, explanation: 'Courts defer to genuine business decisions. They examine process (was it informed and in good faith?) not outcome (did it work?).' }, { question: 'Wrongful trading arises when a director:', options: ['Commits fraud', 'Continues trading knowing the company cannot avoid insolvent liquidation, without minimising losses', 'Conflicts of interest', 'Fails to file accounts'], correctIndex: 1, explanation: 'Wrongful trading (s.214 Insolvency Act UK / s.339 CA 2013 India analogue) imposes personal liability for increasing the deficiency when the director knew insolvency was inevitable.' }] }
    },
    'Shareholder Rights': {
      understand: {
        theory: `# Shareholder Rights\n## Shareholders' Meetings\n- **AGM** (Annual General Meeting): mandatory; accounts, director appointments, dividends\n- **EGM/EOGM** (Extraordinary General Meeting): specific resolutions\n- **Ordinary Resolution**: 50%+ votes (simple majority)\n- **Special Resolution**: 75%+ votes — used for major changes (AoA alteration, name change, winding up)\n\n## Shareholder Remedies\n**Derivative action** (s.245 CA 2013): Shareholder sues on behalf of company for wrongs done to the company\n**Unfair prejudice petition** (s.241-242 CA 2013): Shareholder's interests unfairly harmed — court can order share buyout, injunction, or management change\n**Just and equitable winding up** (s.271): Relationship has broken down irreparably\n\n## Minority Shareholder Protection\n- Rule in Foss v Harbottle: Company, not individual shareholder, is proper plaintiff for wrongs to company\n- Exceptions: Fraud on minority, ultra vires acts, violation of special majorities\n\n## Pre-emption Rights\nExisting shareholders have the right of first refusal on new share issuances (s.62 CA 2013) — protects against dilution`,
        examples: [{ title: 'Unfair prejudice vs. derivative action', language: 'text', code: `TWO-SHAREHOLDER COMPANY:\nA (60%) and B (40%) co-founded TechCo\nA is also MD (Managing Director)\n\nSCENARIO 1 — Derivative Action appropriate:\nA causes TechCo to pay excessive management fees to\nA's personal company → Fraud on TechCo\nB files derivative action on behalf of TechCo against A\n\nSCENARIO 2 — Unfair Prejudice appropriate:\nA excludes B from management despite understanding that\nboth founders would participate in running the business\n→ Legitimate expectation of participation\nB petitions under s.241 → Court orders A to buy B's\nshares at fair value\n\nKEY DISTINCTION:\nDerivative → wrong to the COMPANY\nUnfair prejudice → wrong to the SHAREHOLDER`, explanation: 'Choosing the right remedy matters. Unfair prejudice is the most commonly used shareholders\' remedy in India and the UK.' }],
        keyPoints: ['Minority shareholders cannot be oppressed even when they lost the vote — s.241-242 CA 2013 (India) provides oppression/mismanagement remedies', 'Pre-emption rights protect existing shareholders from dilution when new shares are issued — can be waived by special resolution', 'Annual accounts must be filed with ROC (Registrar of Companies) within 60 days of AGM — failure is a criminal offence for directors']
      },
      evaluate: { questions: [{ question: 'A special resolution requires what percentage of votes?', options: ['50%', '66.67%', '75%', '100%'], correctIndex: 2, explanation: 'Special resolutions require 75% of votes cast. They are required for major changes: AoA amendments, buyback, name change, voluntary winding up.' }, { question: 'The rule in Foss v Harbottle states:', options: ['Shareholders can always sue for wrongs to the company', 'The company is the proper plaintiff for wrongs done to it — not individual shareholders', 'Majority always controls minority', 'Directors cannot be sued by shareholders'], correctIndex: 1, explanation: 'Foss v Harbottle: where a wrong is done to the company, the company must bring the action. Shareholders\' derivative actions are the exception.' }, { question: 'Pre-emption rights protect shareholders against:', options: ['Directors committing fraud', 'Share value dilution when new shares are issued to outside parties', 'Hostile takeovers', 'Excessive dividends'], correctIndex: 1, explanation: 'Pre-emption rights give existing shareholders first refusal on new share issues at the same price — preventing ownership dilution without consent.' }] }
    },
    'Mergers, Acquisitions & Restructuring': {
      understand: {
        theory: `# Mergers, Acquisitions & Restructuring\n## Types of M&A\n- **Merger/Amalgamation**: Two companies combine into one (absorbing entity or new entity)\n- **Acquisition/Takeover**: One company buys another's shares or assets\n- **Demerger**: Division of a company into two or more entities\n- **Slump sale**: Transfer of entire business undertaking as a going concern for a lump sum\n\n## Legal Framework in India\n- **Section 230-234, Companies Act 2013**: Compromise/arrangements/mergers — NCLT approval\n- **SEBI SAST Regulations 2011**: Public company takeover — mandatory open offer at 25%+\n- **Competition Act 2002 (CCI)**: Mandatory notification for combinations above threshold (Combined assets > ₹1,500 Cr or turnover > ₹4,500 Cr)\n- **FEMA**: Foreign acquisitions — automatic/government approval route\n\n## Takeover Defences\n- **Poison pill** (shareholder rights plan): Allows shareholders to buy new shares cheaply, diluting acquirer\n- **White knight**: Inviting a friendly acquirer\n- **Crown jewel defence**: Selling the most attractive asset to make the company less attractive\n- **Staggered board**: Directors serve overlapping terms — cannot all be replaced at once`,
        examples: [{ title: 'Due diligence in an acquisition', language: 'text', code: `ACQUISITION DUE DILIGENCE CHECKLIST:\n\nLEGAL:\n□ Incorporation docs, MoA, AoA, board resolutions\n□ Material contracts review (change of control clauses)\n□ IP ownership (patents, trademarks, copyrights)\n□ Litigation, claims, pending regulatory actions\n□ Employment agreements, ESOPs, PF/ESIC compliance\n\nFINANCIAL:\n□ Audited financials (3-5 years)\n□ Tax returns, pending tax assessments\n□ Debt instruments, security interests\n□ Related-party transactions\n\nOPERATIONAL:\n□ Key employee retention risk\n□ Customer contracts (minimum commitment, SLA)\n□ Technology / data room review\n\nRED FLAGS:\n• Change-of-control clauses in key customer contracts\n• Undisclosed litigation or regulatory notices\n• Unexplained related-party transactions`, explanation: 'Legal due diligence is not just about finding problems — it identifies negotiating points for price adjustments (indemnities, warranties in the SPA).' }],
        keyPoints: ['NCLT approval is mandatory for mergers in India — applies to both domestic and cross-border mergers (s.234 CA 2013)', 'CCI must be notified for combinations above the threshold — gun-jumping (consummating before clearance) attracts penalties of up to 1% of combined assets/turnover', 'Warranties and indemnities in a Share Purchase Agreement (SPA) allocate risk between buyer and seller for undisclosed liabilities']
      },
      evaluate: { questions: [{ question: 'CCI approval in India is required for a merger when:', options: ['Any two companies merge', 'The combined assets exceed ₹1,500 Crore or combined turnover exceeds ₹4,500 Crore', 'There are more than 100 employees', 'The target company is listed'], correctIndex: 1, explanation: 'Competition Act 2002: combinations above the threshold (₹1,500 Cr assets or ₹4,500 Cr turnover) require prior CCI approval.' }, { question: 'A "poison pill" takeover defence involves:', options: ['Selling the company\'s best asset', 'Allowing existing shareholders to buy new shares at a discount, diluting the hostile acquirer', 'Inviting a friendly bidder', 'Buying back shares'], correctIndex: 1, explanation: 'A shareholder rights plan (poison pill) triggers a massive dilution of the acquirer\'s stake if they exceed a threshold without board approval.' }, { question: 'A slump sale involves:', options: ['Selling only one product line', 'Transferring the entire business as a going concern for a lump sum (no individual asset values)', 'A distressed asset fire sale', 'Selling shares to the public'], correctIndex: 1, explanation: 'Slump sale: the whole business undertaking is sold without assigning individual values to assets/liabilities — common in restructurings.' }] }
    },
    'Employment & Labour Law': {
      understand: {
        theory: `# Employment & Labour Law in India\n## Key Legislation\n- **Industrial Disputes Act 1947**: Strikes, lockouts, retrenchment, closure\n- **Contract Labour Act 1970**: Regulation of contractors and contract workers\n- **Shops & Establishments Act**: State-specific; governs working hours, leave, holidays\n- **Code on Wages 2019**: Consolidates minimum wages, payment of wages, bonus, equal remuneration\n- **Industrial Relations Code 2020**: Consolidates Trade Unions Act, Industrial Employment Act, IDA\n\n## Employment Contract Essentials\n- Offer letter + appointment letter = contract\n- Key clauses: Compensation (CTC structure), notice period, confidentiality, non-compete, IP assignment, governing law\n- Non-compete clauses: Enforceable during employment; post-employment restrictions are generally void in India under s.27 ICA (restraint of trade)\n\n## Retrenchment\n- IDA 1947 Chapter VB: Companies with 100+ workmen need prior government permission for retrenchment\n- Retrenchment compensation: 15 days' average wages per completed year of service\n- "Last in, first out" principle unless different selection criteria agreed`,
        examples: [{ title: 'Non-compete clause enforceability in India', language: 'text', code: `COMMON CLAUSE:\n"Employee shall not, for 2 years after employment ends,\nwork for any competitor in the same industry."\n\nLEGAL POSITION (India):\n• Section 27, ICA 1872: Agreement in restraint of trade is void\n• Post-employment non-competes are generally NOT enforceable\n• Exception: Reasonable geographic/time limits + protection of\n  genuine business interests (trade secrets, customer lists)\n\nCOMPARISON:\n• UK: Reasonable post-employment restrictions ARE enforceable\n• USA: Varies by state (California = not enforceable; Texas = enforceable with limits)\n\nWhat IS enforceable in India:\n✓ Non-disclosure/confidentiality (trade secrets)\n✓ Non-solicitation of clients (with time limits)\n✓ IP assignment — inventions during employment belong to employer`, explanation: 'Indian courts consistently hold wide post-employment non-competes void. Protect trade secrets and client relationships through confidentiality and non-solicitation clauses instead.' }],
        keyPoints: ['Post-employment non-compete clauses are generally void in India under Section 27 ICA — use confidentiality and non-solicitation instead', 'Retrenchment of 100+ employees requires 3 months\' notice and government approval under Industrial Disputes Act 1947', 'The 4 Labour Codes (2019-2020) consolidate 29 central labour laws — implementation is state-by-state and still ongoing']
      },
      evaluate: { questions: [{ question: 'Post-employment non-compete clauses in India are generally:', options: ['Fully enforceable with no limitations', 'Void under Section 27 of the Indian Contract Act 1872 as restraints of trade', 'Valid for up to 1 year', 'Only invalid in IT industry'], correctIndex: 1, explanation: 'Section 27 ICA makes all agreements in restraint of trade void. Indian courts consistently strike down post-employment non-competes.' }, { question: 'Retrenchment compensation under IDA 1947 is:', options: ['1 month salary per year of service', '15 days\' average pay per completed year of service', '3 months\' notice pay', 'No compensation required'], correctIndex: 1, explanation: 'IDA 1947 s.25F: 15 days\' average pay for every completed year of continuous service — in addition to notice period pay.' }, { question: 'Industrial Relations Code 2020 consolidates which of these Acts?', options: ['Only Trade Unions Act', 'Trade Unions Act, Industrial Employment (Standing Orders) Act, and Industrial Disputes Act', 'Factories Act and Contract Labour Act', 'Maternity Benefit Act and ESIC Act'], correctIndex: 1, explanation: 'The IR Code 2020 consolidates: Trade Unions Act 1926, Industrial Employment (Standing Orders) Act 1946, and Industrial Disputes Act 1947.' }] }
    },
    'Intellectual Property in Business': {
      understand: {
        theory: `# Intellectual Property in Business\n## IP Types & Duration\n| Type | What It Protects | Duration |\n|------|-----------------|----------|\n| Patent | Inventions (novel, non-obvious, industrially applicable) | 20 years from filing |\n| Copyright | Original creative expression (automatic, no registration) | 60 years after author's death |\n| Trademark | Brand identifiers (marks, logos) | 10 years, renewable indefinitely |\n| Trade Secret | Confidential business information | As long as kept secret |\n| Design | Ornamental/visual features of products | 10 years + 5 extension |\n\n## IP Strategy for Startups\n1. **Identify IP**: Software, algorithms, branding, unique processes\n2. **Protect**: File provisional patent (12-month priority), register TM early\n3. **Own it**: IP assignment agreements with all founders/employees/contractors\n4. **Enforce it**: Monitor infringement; use cease-and-desist first\n5. **Monetise**: License (royalties), cross-license, joint ventures\n\n## IP Assignment in Employment\nIndia: Patents Act 1970 — inventions made by employees in the course of employment belong to employer only if explicitly in the contract.\nBest practice: All employment + contractor agreements must include explicit IP assignment clause.`,
        examples: [{ title: 'Trademark registration process (India)', language: 'text', code: `TRADEMARK REGISTRATION — INDIA:\n\n1. Search: IP India trademark database (public)\n   → Check no conflicting marks in same class\n\n2. File Application: TMO (Trademarks Registry)\n   → Specify class (Nice Classification 1-45)\n   → Online via IP India portal: ~₹4,500 (individual)\n\n3. Examination: Examination report within 1 month\n   → Objections must be replied to within 30 days\n\n4. Publication: Trade Marks Journal\n   → 4-month opposition window\n\n5. Registration: Certificate issued\n   → Valid 10 years; renewals thereafter\n\nPRO TIP: Use ™ immediately on filing (not yet registered)\nUse ® only after registration (criminal offence if used before)`, explanation: 'File trademarks in multiple classes if you operate across categories. "CareerBoost" as a brand should be registered in Class 41 (education) and Class 42 (tech services).' }],
        keyPoints: ['IP assignment clauses in employment/contractor agreements are essential — without them, the developer/designer may own the IP they created', 'File trademark before launch — registering after competitors pick similar marks creates expensive disputes', 'Trade secrets require active protection (NDAs, access controls, employee training) — unlike patents, they have no registration protection but can last indefinitely']
      },
      evaluate: { questions: [{ question: 'Copyright in India lasts for:', options: ['10 years from creation', '20 years from registration', '60 years after the author\'s death', 'Perpetually'], correctIndex: 2, explanation: 'Copyright Act 1957 (India): literary, dramatic, musical, artistic works — 60 years post-mortem auctoris (after author\'s death).' }, { question: 'A startup founder should file an IP assignment agreement with:', options: ['Only external investors', 'All co-founders, employees who create IP, and contractors', 'The company\'s chartered accountant', 'The Registrar of Companies only'], correctIndex: 1, explanation: 'Without explicit assignment, IP creators (co-founders, employees, freelancers) may own what they created. Assignment agreements transfer ownership to the company.' }, { question: '® symbol can legally be used:', options: ['As soon as the trademark application is filed', 'Only after the trademark is formally registered', 'Only by large corporations', 'After 1 year of use in trade'], correctIndex: 1, explanation: '® is reserved for registered trademarks. Using ® before registration is a criminal offence under the Trade Marks Act 1999. Use ™ during the application period.' }] }
    },
    'Tax Law': {
      understand: {
        theory: `# Tax Law — Fundamentals\n## Indian Tax Structure\n**Direct Taxes** (Central Government)\n- Income Tax Act 1961: Individuals, HUF, firms, companies, AOP/BOI\n- Corporate Tax: 22% (domestic companies); 15% (new manufacturing companies under s.115BAB)\n\n**Indirect Taxes**\n- **GST** (Goods & Services Tax, 2017): Destination-based consumption tax. Rates: 0%, 5%, 12%, 18%, 28%\n  - CGST + SGST (intrastate), IGST (interstate), UTGST\n- **Customs Duty**: Imports/exports\n\n## GST — Input Tax Credit (ITC)\nRegistered dealers can claim credit for GST paid on inputs against GST collected on outputs:\n\nGST payable = GST on output − GST on input (ITC)\n\n## Transfer Pricing\nArm's length principle: Related party transactions must be priced as if between independent parties. Deviation = deemed income, penalties.\n\n## Tax Evasion vs. Avoidance vs. Planning\n- **Evasion**: Illegal concealment of income\n- **Avoidance**: Legal but aggressive — GAAR (General Anti-Avoidance Rule) may be invoked\n- **Planning**: Legitimate use of provisions (DTAA, 80C deductions)`,
        examples: [{ title: 'GST calculation for a service business', language: 'text', code: `SCENARIO: Software services company (Delhi → Mumbai, B2B)\n\nInvoice raised by Company A (Delhi) to Client B (Mumbai):\nService value: ₹10,00,000\nApplicable GST: 18% IGST (interstate B2B)\nGST amount: ₹1,80,000\nTotal invoice: ₹11,80,000\n\nCompany A's GST liability:\nIGST on output:  ₹1,80,000\nITC on inputs:\n  - Cloud hosting (AWS): ₹9,000 IGST\n  - Office rent:         ₹18,000 CGST+SGST (ineligible for office rent — blocked credit)\n  - Software tools:      ₹5,400 IGST\n\nNet GST payable: ₹1,80,000 − ₹14,400 = ₹1,65,600\n\nFiling: GSTR-1 (outward supplies) by 11th of next month\n        GSTR-3B (self-assessed return) by 20th`, explanation: 'Office rent GST is a blocked credit (Section 17(5) CGST Act). Always verify ITC eligibility before claiming.' }],
        keyPoints: ['GST is destination-based — it goes to the state where consumption happens (via SGST/IGST settlement)', 'Transfer pricing documentation is mandatory for international related-party transactions exceeding ₹1 Crore — non-compliance attracts 2% penalty on transaction value', 'DTAA (Double Taxation Avoidance Agreements) prevents the same income from being taxed twice — India has DTAAs with 95+ countries']
      },
      evaluate: { questions: [{ question: 'Input Tax Credit (ITC) under GST allows:', options: ['Claiming refund of all taxes paid', 'Setting off GST paid on purchases against GST collected on sales', 'Reducing income tax liability', 'Claiming exemption from GST'], correctIndex: 1, explanation: 'ITC is the mechanism to avoid cascading taxation. GST paid on business purchases can be set off against GST liability on sales.' }, { question: 'IGST is applicable when:', options: ['Both parties are in the same state', 'The transaction is interstate (supplier and recipient in different states)', 'The product is exempt from GST', 'Exports are involved only'], correctIndex: 1, explanation: 'IGST (Integrated GST) applies to interstate transactions and imports. Intrastate transactions attract CGST + SGST.' }, { question: 'What is the arm\'s length principle in transfer pricing?', options: ['Pricing based on length of relationship with the party', 'Related party transactions must be priced as if conducted between independent parties at market rates', 'Transactions within arm\'s reach of headquarters only', 'Pricing that cannot be challenged by tax authorities'], correctIndex: 1, explanation: 'Transfer pricing rules require that transactions between related entities (group companies) reflect market prices — preventing profit shifting to low-tax jurisdictions.' }] }
    },
    'Constitutional Law': {
      understand: {
        theory: `# Constitutional Law of India\n## Structure of the Constitution\n- Adopted: 26 January 1950\n- Longest written constitution: Originally 395 articles, 8 schedules + 22 parts\n- Federal with unitary bias: States have autonomy but Centre can take over (President's Rule)\n\n## Fundamental Rights (Part III, Art. 12-35)\n1. **Right to Equality** (14-18): Equal protection, no discrimination\n2. **Right to Freedom** (19-22): Speech, expression, assembly, movement, profession\n3. **Right against Exploitation** (23-24): No trafficking, child labour\n4. **Right to Freedom of Religion** (25-28): Practice, profess, propagate\n5. **Cultural & Educational Rights** (29-30): Minority protection\n6. **Right to Constitutional Remedies** (32): "Heart and soul" of the Constitution (Ambedkar)\n\n## Doctrine of Basic Structure (Kesavananda Bharati 1973)\nParliament can amend the Constitution (Art. 368) but cannot destroy its basic structure.\nBasic structure includes: supremacy of Constitution, separation of powers, judicial review, federalism, secularism, free and fair elections.\n\n## Writs (Art. 32, High Court Art. 226)\n- **Habeas Corpus**: Produce the body — against illegal detention\n- **Mandamus**: Compel a public authority to perform duty\n- **Certiorari**: Quash an illegal order of inferior court/tribunal\n- **Prohibition**: Stop inferior court from exceeding jurisdiction\n- **Quo Warranto**: Challenge a person's right to hold public office`,
        examples: [{ title: 'Right to Freedom of Speech — limitations test', language: 'text', code: `Article 19(1)(a): Right to Freedom of Speech and Expression\n\nArticle 19(2): State can impose "reasonable restrictions" for:\n• Sovereignty and integrity of India\n• Security of the State\n• Friendly relations with foreign states\n• Public order\n• Decency and morality\n• Contempt of court\n• Defamation\n• Incitement to offence\n\nTEST: Is the restriction "reasonable"?\n→ Proportionality test (K.S. Puttaswamy v Union of India 2017)\n→ Legitimate aim + Rational nexus + Proportionate means\n\nEXAMPLE:\nInternet shutdown order in Kashmir challenged\n→ Court (Anuradha Bhasin 2020): Not absolute; must be\n  limited in area, duration; subject to judicial review`, explanation: 'Fundamental rights are not absolute — Article 19(2) permits reasonable restrictions. Courts apply proportionality review to test "reasonableness".' }],
        keyPoints: ['Basic Structure doctrine limits Parliament\'s amending power — fundamental rights, secularism, judicial review cannot be destroyed even by constitutional amendment', 'Right to Privacy is a fundamental right (K.S. Puttaswamy v Union of India 2017) — has implications for Aadhaar, surveillance, and DPDP Act', 'Article 32 (Supreme Court) and Article 226 (High Courts) give citizens direct access to courts for enforcement of fundamental rights — without going through lower courts']
      },
      evaluate: { questions: [{ question: 'The Basic Structure doctrine was established by:', options: ['Minerva Mills case 1980', 'Kesavananda Bharati v State of Kerala 1973', 'Maneka Gandhi v Union of India 1978', 'Golak Nath v State of Punjab 1967'], correctIndex: 1, explanation: 'Kesavananda Bharati (1973, 13-judge bench): Parliament has unlimited amendment power EXCEPT it cannot destroy the basic structure of the Constitution.' }, { question: 'A writ of Habeas Corpus is issued to:', options: ['Compel performance of a public duty', 'Challenge holding of public office', 'Produce a detained person before court to examine legality of detention', 'Stop an inferior court from exceeding jurisdiction'], correctIndex: 2, explanation: 'Habeas Corpus (Latin: "have the body") requires the detaining authority to bring the person before court. The court then examines if the detention is lawful.' }, { question: 'Article 32 is described as the "heart and soul" of the Constitution by Ambedkar because:', options: ['It is the longest article', 'It provides the constitutional remedy to enforce fundamental rights — making them meaningful, not just declarations', 'It created the Supreme Court', 'It defines fundamental duties'], correctIndex: 1, explanation: 'Without Article 32, fundamental rights would be hollow declarations. It gives every citizen the right to directly approach the Supreme Court for enforcement.' }] }
    },
  },
};
