export const MEDICINE_CONTENT: Record<string, Record<string, any>> = {
  'Medical Terminology': {
    'Greek & Latin Roots': {
      understand: {
        theory: `# Greek & Latin Roots in Medical Language\nMedical terminology is built from Greek and Latin roots. Understanding roots allows you to decode unfamiliar terms.\n\n## Core Body Part Roots\n| Root | Meaning | Example |\n|------|---------|----------|\n| cardi(o) | heart | cardiomegaly (enlarged heart) |\n| hepat(o) | liver | hepatitis (liver inflammation) |\n| nephr(o)/ren(o) | kidney | nephrology, renal failure |\n| pulmon(o)/pneum(o) | lung | pulmonology, pneumonia |\n| gastr(o) | stomach | gastritis, gastrectomy |\n| arthr(o) | joint | arthritis, arthroscopy |\n| derm(a)/cutane | skin | dermatology, subcutaneous |\n| oste(o) | bone | osteoporosis, osteotomy |\n| neur(o) | nerve | neurology, neuropathy |\n| haem/hemat(o) | blood | haematology, haematoma |\n\n## Directional Roots\n- **ante/pre**: before (antenatal = before birth)\n- **post**: after (postoperative)\n- **intra**: within (intravenous)\n- **extra/exo**: outside (extracellular)\n- **inter**: between (intercostal = between ribs)\n- **peri**: around (pericardium = sac around heart)\n\n## Process/Condition Roots\n- **-algia**: pain (neuralgia, myalgia)\n- **-emia**: blood condition (anaemia, septicaemia)\n- **-osis**: condition/process (fibrosis, necrosis)\n- **-itis**: inflammation (arthritis, colitis)\n- **-ectomy**: surgical removal (appendectomy)\n- **-plasty**: surgical repair (rhinoplasty)`,
        examples: [{ title: 'Decoding complex medical terms from roots', language: 'text', code: `TERM: "electroencephalography"\n  electro = electrical\n  encephalo = brain\n  graphy = process of recording\n  → Recording electrical activity of the brain (EEG)\n\nTERM: "cholecystectomy"\n  chole = bile\n  cysto = bladder/sac\n  ectomy = surgical removal\n  → Surgical removal of the gallbladder\n\nTERM: "haematological malignancy"\n  haemato = blood\n  logical = study of\n  malignancy = cancerous\n  → Blood cancer (leukaemia, lymphoma)\n\nTERM: "subcutaneous haematoma"\n  sub = under\n  cutane = skin\n  ous = pertaining to\n  haemato = blood\n  oma = mass/collection\n  → Blood collection under the skin (bruise)`, explanation: 'Any medical term can be decoded by identifying roots. This is more valuable than memorising 10,000 individual terms — learn the building blocks instead.' }],
        keyPoints: ['The most commonly tested roots: cardio (heart), hepato (liver), nephro (kidney), pneumo (lung), neuro (nerve), haemo (blood), arthro (joint)', 'The same root in different contexts: hepato-megaly (enlarged liver), hepat-itis (inflamed liver), hepat-ectomy (removed liver) — suffix changes meaning completely', 'Greek and Latin are used interchangeably in medicine: kidney = nephro (Greek) = reno (Latin) — both appear in clinical terms']
      },
      evaluate: { questions: [{ question: 'The root "nephro-" refers to:', options: ['Heart', 'Liver', 'Kidney', 'Lung'], correctIndex: 2, explanation: '"Nephro" comes from Greek "nephros" = kidney. Examples: nephrology (study of kidneys), nephrectomy (kidney removal), nephrotic syndrome.' }, { question: 'What does "cholecystectomy" mean?', options: ['Inflammation of the bile duct', 'Surgical removal of the gallbladder', 'X-ray of the gallbladder', 'Study of bile production'], correctIndex: 1, explanation: 'Chole = bile, cysto = sac/bladder, ectomy = surgical removal. Cholecystectomy = removal of the gallbladder. The most common abdominal surgery worldwide.' }, { question: 'The suffix "-megaly" means:', options: ['Removal of', 'Inflammation of', 'Abnormal enlargement of', 'Study of'], correctIndex: 2, explanation: '-megaly = enlargement. Cardiomegaly = enlarged heart; hepatomegaly = enlarged liver; splenomegaly = enlarged spleen.' }] }
    },
    'Prefixes & Suffixes': {
      understand: {
        theory: `# Medical Prefixes & Suffixes\n## Essential Prefixes\n| Prefix | Meaning | Example |\n|--------|---------|----------|\n| a-/an- | without/absence | anaemia (no iron), apnoea (no breathing) |\n| brady- | slow | bradycardia (slow heart rate <60bpm) |\n| tachy- | fast | tachycardia (fast heart rate >100bpm) |\n| hyper- | above/excess | hypertension, hyperthyroidism |\n| hypo- | below/deficiency | hypoglycaemia, hypothyroidism |\n| dys- | abnormal/difficult | dyspnoea (difficult breathing) |\n| poly- | many/excess | polyuria (excess urination) |\n| micro- | small | microcephaly (small head) |\n| macro- | large | macrocytic anaemia |\n| bi- | two | bilateral (both sides) |\n\n## Essential Suffixes\n| Suffix | Meaning | Example |\n|--------|---------|----------|\n| -itis | inflammation | appendicitis, meningitis |\n| -oma | tumour/mass | carcinoma, haematoma |\n| -ectomy | surgical removal | tonsillectomy |\n| -otomy/-tomy | surgical incision | tracheotomy, laparotomy |\n| -oscopy | visual examination | colonoscopy, bronchoscopy |\n| -graphy | imaging/recording | angiography, mammography |\n| -ology | study of | cardiology, haematology |\n| -plasty | surgical repair/reconstruction | rhinoplasty, angioplasty |\n| -rrhaphy | surgical suturing | haemorrhage repair |\n| -stomy | creating an opening | colostomy, ileostomy |`,
        examples: [{ title: 'Common clinical terms decoded', language: 'text', code: `CLINICAL TERMS:\n\n"Dyspnoea" (Breathing difficulty):\n  dys = abnormal/difficult\n  pnoea = breathing\n  → Difficulty breathing = cardinal respiratory symptom\n\n"Hypoglycaemia" (Low blood sugar):\n  hypo = below normal\n  glyc = sugar/glucose\n  aemia = blood condition\n  → Below normal blood glucose (<4 mmol/L)\n\n"Polyuria" (Excess urination):\n  poly = many/excess\n  uria = urine condition\n  → Excessive urination — symptom of diabetes\n\n"Tachyarrhythmia":\n  tachy = fast\n  arrhythmia = irregular rhythm\n  → Fast, irregular heart rhythm\n\n"Cholecystitis":\n  chole/cysto = gallbladder\n  itis = inflammation\n  → Inflamed gallbladder (often from gallstones)`, explanation: 'In clinical practice, diagnoses are described using these terms precisely. "The patient presented with dyspnoea and tachycardia" conveys exact symptoms instantly to any clinician.' }],
        keyPoints: ['-itis = inflammation (NOT infection necessarily) — pneumonitis can be inflammatory without infection; -itis always implies an acute inflammatory process', 'Hyper vs hypo are frequently confused clinically — hyperthyroidism (excess) vs hypothyroidism (deficiency) have opposite presentations and treatments', 'Diagnostic suffixes follow function: -oscopy (look inside), -graphy (image it), -gram (the image produced). Colonoscopy uses a colonoscope to produce a cologram.']
      },
      evaluate: { questions: [{ question: 'Bradycardia means:', options: ['Abnormal heart rhythm', 'Heart rate faster than 100 bpm', 'Heart rate slower than 60 bpm', 'Irregular heartbeat'], correctIndex: 2, explanation: 'Brady = slow; cardia = heart. Bradycardia is defined as heart rate < 60 bpm. Can be normal in athletes; pathological if causing symptoms (dizziness, syncope).' }, { question: 'A "tracheotomy" involves:', options: ['Removal of the trachea', 'Surgical incision into the trachea', 'Visual examination of the trachea', 'Inflammation of the trachea'], correctIndex: 1, explanation: '-otomy = surgical incision (cutting into but not removing). Tracheotomy cuts into the trachea to create an airway. Contrast with -ectomy (removal).' }, { question: 'The suffix -oscopy means:', options: ['Surgical removal', 'Imaging by X-ray', 'Visual examination using a scope', 'Measurement of'], correctIndex: 2, explanation: '-oscopy = visual examination using a scope. Colonoscopy = examining the colon; bronchoscopy = examining airways; laparoscopy = examining the abdomen.' }] }
    },
    'Body Systems Terminology': {
      understand: {
        theory: `# Body Systems Medical Terminology\nEach body system has its own prefix root. Learning these enables rapid understanding of any system-specific diagnosis.\n\n## Cardiovascular System\n- **Angio-**: blood vessel (angioplasty, angiogram)\n- **Phlebo-/Veno-**: vein (phlebotomy = blood draw, venous thrombosis)\n- **Arterio-**: artery (arteriosclerosis = hardened arteries)\n- Key terms: Ischaemia (insufficient blood supply), infarction (tissue death from ischaemia)\n\n## Respiratory System\n- **Broncho-**: bronchus (bronchitis, bronchospasm)\n- **Pleur-**: pleura (pleuritis, pleural effusion)\n- **Rhin-**: nose (rhinitis = hay fever)\n- Key terms: Dyspnoea (breathlessness), tachypnoea (fast breathing), orthopnoea (breathless lying flat — heart failure)\n\n## Gastrointestinal System\n- **Entero-**: intestine (gastroenteritis)\n- **Hepato-**: liver (hepatocellular carcinoma)\n- **Cholangio-**: bile duct (cholangitis)\n- Key terms: Dysphagia (difficulty swallowing), nausea, emesis (vomiting), haematemesis (vomiting blood)\n\n## Neurological System\n- **Encephalo-**: brain (encephalitis, encephalopathy)\n- **Mening-**: meninges (meningitis)\n- **Myelo-**: spinal cord/bone marrow (myeloma, myelopathy)\n- Key terms: Aphasia (speech loss), dysarthria (slurred speech), ataxia (coordination problems)`,
        examples: [{ title: 'Cardiovascular emergency terminology', language: 'text', code: `ACUTE MI (HEART ATTACK) TERMINOLOGY:\n\n"Acute ST-elevation myocardial infarction (STEMI)\nwith cardiogenic shock requiring emergent\npercutaneous coronary intervention (PCI)"\n\nBREAKDOWN:\n• Acute = sudden onset\n• ST-elevation = ECG finding (elevated ST segment)\n• Myocardial = myo (muscle) + cardial (heart)\n• Infarction = tissue death from blocked blood supply\n• Cardiogenic = originating from heart (shock caused by heart)\n• Shock = circulatory failure\n• Percutaneous = through the skin\n• Coronary = crown-shaped vessels supplying heart\n• Intervention = procedure to open blocked artery\n\nIn everyday language:\n"A sudden heart attack with heart failure\nrequiring an emergency procedure to unblock\nthe coronary artery"`, explanation: 'Medical jargon carries exact meaning — "STEMI" tells the cardiologist exactly what ECG finding and treatment pathway is needed without ambiguity.' }],
        keyPoints: ['Ischaemia (Greek: "holding back blood") means inadequate blood supply; infarction means tissue death from ischaemia — angina = ischaemia without infarction', 'System-specific roots are combined: broncho (airway) + pneumo (lung) = bronchopneumonia (infection of airways and lung parenchyma)', 'Laterality terminology: unilateral (one side), bilateral (both sides), ipsilateral (same side as reference), contralateral (opposite side) — critical for surgical documentation']
      },
      evaluate: { questions: [{ question: 'Haematemesis means:', options: ['Blood in urine', 'Vomiting blood', 'Coughing up blood', 'Blood in stool'], correctIndex: 1, explanation: 'Haemato = blood; emesis = vomiting. Haematemesis = vomiting blood — suggests upper GI bleeding (oesophageal varices, peptic ulcer). Haematuria = blood in urine; haemoptysis = blood from lungs.' }, { question: 'Aphasia refers to:', options: ['Difficulty swallowing', 'Slurred speech', 'Loss of ability to produce or understand language (speech disorder from brain damage)', 'Muscle weakness'], correctIndex: 2, explanation: 'Aphasia (a = without, phasia = speech) = language disorder from brain damage (stroke, trauma). Dysarthria = slurred speech from motor problem. Aphasia = language impairment.' }, { question: 'Pleural effusion means:', options: ['Collapsed lung', 'Lung infection', 'Fluid accumulation in the pleural space (around the lung)', 'Inflamed lung tissue'], correctIndex: 2, explanation: 'Pleura = the membrane lining the lung; effusion = fluid collection. Pleural effusion = fluid between the two pleural layers — causes breathlessness and dullness on percussion.' }] }
    },
    'Clinical Documentation': {
      understand: {
        theory: `# Clinical Documentation Standards\nAccurate, timely clinical documentation is a legal and ethical requirement. It is also essential for continuity of care.\n\n## SOAP Note Format\n- **S** (Subjective): Patient's own words — chief complaint, history\n- **O** (Objective): Measurable data — vitals, examination, labs, imaging\n- **A** (Assessment): Clinical diagnosis and differential diagnoses\n- **P** (Plan): Investigations, treatment, referrals, patient education\n\n## OLDCARTS — History of Present Illness\n- **O**nset, **L**ocation, **D**uration, **C**haracter\n- **A**lleviating/Aggravating factors, **R**adiation, **T**iming, **S**everity\n\n## Common Abbreviations\n| Abbreviation | Meaning |\n|-------------|----------|\n| PRN | As needed (pro re nata) |\n| TDS/TID | Three times daily |\n| BD/BID | Twice daily |\n| STAT | Immediately |\n| NPO/NBM | Nil by mouth |\n| Hx | History |\n| Dx | Diagnosis |\n| Rx | Treatment/prescription |\n| SOB | Shortness of breath |\n| PMH | Past medical history |`,
        examples: [{ title: 'SOAP note for chest pain', language: 'text', code: `S: 52M, sudden onset chest pain 3/10 to 8/10 at rest × 2hr.\n   Crushing, substernal, radiates to left arm.\n   Diaphoresis+, nausea+. No relief with antacids.\n   PMH: T2DM, HTN. Smoker 20pk-yr. FHx: Father had MI at 55.\n\nO: BP 158/96 | HR 108 | RR 22 | SpO2 95% RA | Temp 37.1\n   ECG: ST elevation in II, III, aVF (inferior)\n   Troponin I pending | CXR: no pneumothorax\n   Exam: Diaphoretic, mild respiratory distress, S4 gallop\n\nA: 1. Inferior STEMI — primary diagnosis\n   2. Unstable angina — less likely given ECG changes\n   3. Aortic dissection — ruled out by clinical picture\n\nP: • STEMI protocol activated — Cath Lab on standby\n   • Aspirin 300mg PO + Clopidogrel 600mg loading\n   • IV access × 2, O2 if SpO2 <94%\n   • IV morphine 2mg for pain PRN\n   • Cardiology consult STAT\n   • Repeat troponin at 3hr, repeat ECG in 30 min`, explanation: 'SOAP notes are concise but complete. Every clinician taking over care can immediately understand the presentation, diagnosis, and plan.' }],
        keyPoints: ['SOAP documentation is the universal format — any clinician worldwide can parse it instantly without confusion', 'Abbreviations require care: "QD" vs "QID" vs "BD" — a single character difference changes frequency from once daily to four times daily', 'Legal requirement: notes must be dated, timed, and signed. Late entries must be clearly marked. Never alter or white-out records.']
      },
      evaluate: { questions: [{ question: 'In SOAP documentation, "Assessment" means:', options: ['Patient vital signs', 'Your clinical diagnosis and differential diagnoses', 'Treatment plan', 'Patient reported symptoms'], correctIndex: 1, explanation: 'Assessment = clinical judgment — diagnosis (primary and differentials). Distinguishes the clinician\'s interpretation from raw data (Objective).' }, { question: 'PRN in a prescription means:', options: ['Immediately', 'Three times daily', 'As needed (only when required)', 'By mouth'], correctIndex: 2, explanation: 'PRN = pro re nata (Latin: as the thing is needed). A PRN medication is only given when needed (e.g., pain relief PRN = give when patient has pain).' }, { question: 'The "O" in OLDCARTS stands for:', options: ['Objective findings', 'Onset — when the symptom started', 'Observations by examination', 'Oral medications'], correctIndex: 1, explanation: 'OLDCARTS history framework: Onset = when it started. This is the first question in characterising any symptom for clinical diagnosis.' }] }
    },
  },
  'Clinical Research & Trials': {
    'Research Design (RCT/Cohort)': {
      understand: {
        theory: `# Clinical Research Study Designs\nChoosing the right study design determines the quality of evidence your research generates.\n\n## Hierarchy of Evidence\nSystematic Reviews/Meta-analyses > RCTs > Cohort Studies > Case-Control > Cross-sectional > Case Reports\n\n## Randomised Controlled Trial (RCT)\n**Gold standard** for evaluating interventions.\n- Participants randomly allocated to intervention or control group\n- Minimises confounding bias\n- **Blinding**: Single-blind (patient unaware) or Double-blind (patient + researcher unaware)\n- **Placebo**: Control group receives inert treatment\n- **Intention-to-treat analysis**: All enrolled patients analysed regardless of protocol completion\n\n## Cohort Study\n- Follow a group of people over time\n- Measures who develops the outcome (incidence)\n- Good for rare exposures, multiple outcomes\n- Prospective (follow forward) or Retrospective (historical records)\n- Cannot prove causation; shows association\n\n## Case-Control Study\n- Start with cases (have disease) vs. controls (don't)\n- Look back for exposure differences\n- Good for rare diseases\n- Measures Odds Ratio (OR) — not risk directly\n\n## Key Biases\n- **Selection bias**: Sampling not representative\n- **Information/Recall bias**: Inaccurate past exposure reporting\n- **Confounding**: Third variable explains apparent relationship`,
        examples: [{ title: 'RCT design for a new drug trial', language: 'text', code: `PHASE 3 RCT DESIGN:\nResearch question: Does Drug X reduce 30-day mortality\nin septic shock compared to standard care?\n\nDESIGN ELEMENTS:\n• Population: ICU patients with septic shock\n• Intervention: Drug X 10mg/kg IV q8h × 7 days\n• Comparator: Matched placebo IV q8h × 7 days\n• Outcome: All-cause 30-day mortality\n• Randomisation: 1:1, computer-generated\n• Blinding: Double-blind (patient + ICU team + assessor)\n• Sample size: N=820 (80% power, α=0.05, 15% relative risk reduction)\n\nSTATISTICS:\n• Primary analysis: Intention-to-treat (ITT)\n• Log-rank test for time-to-event; Cox hazard ratio\n• Pre-specified subgroups: age >65, SOFA score >11\n\nEXPECTED OUTPUT:\n"Drug X reduced 30-day mortality from 35% to 27%\n(RR 0.77, 95%CI 0.64-0.93, p=0.006)"`, explanation: 'RCT design requires pre-specification of all elements before data collection begins — prevents bias from changing analysis after seeing results (HARKing).' }],
        keyPoints: ['RCTs prove causation; observational studies (cohort, case-control) show association — this distinction is critical when interpreting evidence', 'Intention-to-treat (ITT) analysis is the most conservative and preferred primary analysis — includes all randomised patients even if they didn\'t complete the protocol', 'Sample size calculation is essential before starting: insufficient power = false negative (miss a real effect); must pre-specify significance level (α) and power (1-β)']
      },
      evaluate: { questions: [{ question: 'The gold standard study design for evaluating a new medical intervention is:', options: ['Case-control study', 'Cohort study', 'Randomised Controlled Trial (RCT)', 'Case report series'], correctIndex: 2, explanation: 'RCT is gold standard because randomisation minimises confounding, allowing attribution of any outcome difference to the intervention itself.' }, { question: 'Double-blind RCT means:', options: ['Two separate RCTs are conducted', 'Neither the patient nor the researcher/assessor knows which group is intervention vs control', 'Two different drugs are compared', 'The study has two primary outcomes'], correctIndex: 1, explanation: 'Double-blind: both participant and assessor are unaware of group allocation — prevents performance bias (participants behaving differently) and detection bias (assessors scoring differently).' }, { question: 'Intention-to-treat (ITT) analysis in RCTs:', options: ['Excludes patients who did not comply with treatment', 'Analyses only patients who completed the protocol', 'Analyses all randomised patients in their assigned group regardless of protocol adherence', 'Analyses only the most severe cases'], correctIndex: 2, explanation: 'ITT preserves the benefits of randomisation. Excluding non-completers (per-protocol analysis) can introduce selection bias — those who drop out may differ systematically.' }] }
    },
    'GCP Guidelines': {
      understand: {
        theory: `# Good Clinical Practice (GCP) Guidelines\nGCP is an international ethical and scientific quality standard for designing, conducting, recording, and reporting clinical trials.\n\n## ICH E6 GCP Core Principles\n1. Clinical trials should be conducted in accordance with the Declaration of Helsinki\n2. Benefits and risks must be assessed before trial initiation\n3. Subject rights, safety, and wellbeing take priority over science and society\n4. Available nonclinical and clinical information must support the proposed trial\n5. Trials must be scientifically sound with a clear, detailed protocol\n6. Trials must be conducted according to the protocol\n7. Medical decisions must involve a qualified physician\n8. Each subject must provide freely given informed consent\n9. All information must be recorded, handled, and stored to permit accurate reporting\n10. Confidentiality of subjects must be protected\n\n## Key GCP Roles\n- **Principal Investigator (PI)**: Physician responsible for trial at site; signs off on all medical decisions\n- **Sponsor**: Organisation funding/initiating the trial; ensures GCP compliance\n- **IRB/IEC** (Ethics Committee): Independent review body — approves protocol; monitors ongoing safety\n- **CRA** (Clinical Research Associate): Sponsor's monitor who visits sites to verify data accuracy\n- **Data Safety Monitoring Board (DSMB)**: Independent committee; reviews unblinded safety data; can stop trial early`,
        examples: [{ title: 'Informed consent process in clinical trials', language: 'text', code: `INFORMED CONSENT REQUIREMENTS (GCP):\n\nELEMENTS OF VALID CONSENT:\n✓ Purpose of the research explained\n✓ Procedures described (including experimental)\n✓ Reasonably foreseeable risks/discomforts\n✓ Anticipated benefits\n✓ Alternative treatments available\n✓ Confidentiality protections\n✓ Compensation for injury (if applicable)\n✓ Contact information for questions\n✓ Voluntary participation — right to withdraw\n\nPROCESS REQUIREMENTS:\n• Sufficient time to consider (no coercion)\n• Language subject understands\n• Capacity to consent (or LAR for incapacitated)\n• Signed dated consent form retained\n• Re-consent required if protocol changed\n\nWHEN CONSENT IS PROBLEMATIC:\n• Emergency research (waiver of consent possible with IRB approval)\n• Paediatric trials: parental consent + child assent (age ≥7)\n• Cognitive impairment: Legally Authorised Representative (LAR)`, explanation: 'Informed consent is a process, not just a form. The conversation and subject understanding matter — a signature without understanding is not valid GCP consent.' }],
        keyPoints: ['GCP is not optional — violations result in trial invalidation, regulatory action, and in severe cases, criminal prosecution', 'Protocol deviations must be documented and reported to IRB — deviations that affect subject safety require immediate reporting', 'The Declaration of Helsinki (World Medical Association, 1964) is the ethical foundation for all clinical research — GCP operationalises its principles']
      },
      evaluate: { questions: [{ question: 'Under GCP, the most critical priority in a clinical trial is:', options: ['Scientific validity of results', 'Regulatory approval timeline', 'Subject rights, safety, and wellbeing above science and society', 'Sponsor financial interests'], correctIndex: 2, explanation: 'GCP Principle 3: The rights, safety, and well-being of trial subjects must prevail over the interests of science and society. This is non-negotiable.' }, { question: 'The role of an IRB/IEC in clinical trials is:', options: ['Conduct the trial on behalf of the sponsor', 'Independently review and approve protocols, monitor ongoing safety, and protect subject rights', 'Analyse the statistical results', 'Fund the research'], correctIndex: 1, explanation: 'IRB (Institutional Review Board) / IEC (Independent Ethics Committee) provides independent ethical oversight. Must approve protocol before trial begins; monitors for emerging safety concerns.' }, { question: 'Informed consent in a clinical trial requires:', options: ['Verbal agreement only from the patient', 'Signature on any form within 24 hours of enrolment', 'Voluntary, documented agreement after adequate explanation in a language the subject understands', 'Physician decision without patient input for patient benefit'], correctIndex: 2, explanation: 'GCP Principle 8: Informed consent must be freely given, fully informed, and documented. It is a process — not just a form. Subject must understand what they are agreeing to.' }] }
    },
  },
  'Public Health & Epidemiology': {
    'Epidemiological Methods': {
      understand: {
        theory: `# Epidemiological Methods\nEpidemiology is the study of the distribution and determinants of disease in populations, and the application of this study to disease control.\n\n## Key Measures\n**Prevalence** = Existing cases / Population × 100\nProportion of population with condition AT a point in time\n\n**Incidence Rate** = New cases / Population at risk × Time period\nRate at which new cases develop\n\n**Mortality Rate** = Deaths / Population × 100,000\n\n**Case Fatality Rate (CFR)** = Deaths / Confirmed cases × 100\nSeverity of disease in those who are infected\n\n## Association Measures\n**Relative Risk (RR)**: Incidence in exposed / Incidence in unexposed\n- RR=1: no association; RR>1: increased risk; RR<1: protective\n- Used in cohort studies\n\n**Odds Ratio (OR)**: Odds of exposure in cases / Odds in controls\n- Used in case-control studies\n- Approximates RR for rare diseases\n\n**Attributable Risk**: Incidence in exposed − Incidence in unexposed\nProportion of disease attributable to the exposure\n\n## Screening Criteria (Wilson & Jungner)\n1. Important health problem\n2. Effective treatment available\n3. Test sensitive and specific\n4. Cost-effective\n5. Natural history understood`,
        examples: [{ title: 'Calculating disease measures in an outbreak', language: 'text', code: `FOOD POISONING OUTBREAK SCENARIO:\n\nSchool picnic: 200 attended\n• 80 ate the potato salad (exposed)\n• 120 did NOT eat potato salad (unexposed)\n• 60 of the 80 who ate salad became ill\n• 20 of the 120 who didn't eat salad became ill\n\nCALCULATIONS:\n\nAttack Rate (exposed)   = 60/80  = 75%\nAttack Rate (unexposed) = 20/120 = 16.7%\n\nRelative Risk = 75% / 16.7% = 4.5\nInterpretation: Those who ate potato salad were\n4.5× more likely to become ill\n\nAttributable Risk = 75% - 16.7% = 58.3%\n58.3% of illness was attributable to the potato salad\n\nOdds Ratio = (60×100) / (20×20) = 6000/400 = 15\n(Note: OR overestimates RR when outcome is common)\n\nCONCLUSION: Potato salad is the vehicle of infection`, explanation: 'Epidemiological calculations quantify both the strength of association and the proportion of disease attributable to the exposure — guides public health action.' }],
        keyPoints: ['Relative Risk (cohort) and Odds Ratio (case-control) both measure association strength — OR approximates RR only for rare diseases (<10% prevalence)', 'Sensitivity = proportion of true positives identified by test; Specificity = proportion of true negatives. High sensitivity = fewer missed cases; high specificity = fewer false alarms', 'P-value < 0.05 means ≤5% chance results are due to chance — conventional but arbitrary threshold. Confidence intervals provide more information than p-values alone']
      },
      evaluate: { questions: [{ question: 'Incidence rate measures:', options: ['Proportion of population with disease at one time point', 'New cases occurring in a population over a defined time period', 'Proportion who die from a disease', 'Years of healthy life lost to disease'], correctIndex: 1, explanation: 'Incidence = new cases per unit time. Prevalence = all existing cases. High incidence + long duration = high prevalence (chronic diseases have high prevalence despite decreasing incidence).' }, { question: 'A Relative Risk (RR) of 3.0 means:', options: ['The disease is 3 times more common in the general population', 'Exposed individuals have 3 times the risk of developing disease compared to unexposed', 'The treatment reduces risk by 3 times', 'There is a 3% chance of false positive'], correctIndex: 1, explanation: 'RR = Incidence in exposed / Incidence in unexposed. RR=3.0 means exposed have 3× the risk of unexposed. RR=1 means no difference; RR<1 means protective.' }, { question: 'Case Fatality Rate (CFR) measures:', options: ['Deaths per 100,000 population', 'Proportion of infected persons who die from the disease', 'Proportion of population that contracts the disease', 'Years of life lost to the disease'], correctIndex: 1, explanation: 'CFR = Deaths / Confirmed cases × 100. Measures disease severity in those infected. COVID-19 CFR varied from 0.1-3% depending on age, healthcare access, and variant.' }] }
    },
    'Social Determinants of Health': {
      understand: {
        theory: `# Social Determinants of Health (SDOH)\nThe conditions in which people are born, grow, live, work, and age — shaped by the distribution of money, power, and resources at global, national, and local levels.\n\n## The SDOH Framework\n**Economic stability**: Income, employment, food security, housing stability\n**Education**: Literacy, language, early childhood education, vocational training\n**Social/community context**: Social cohesion, discrimination, incarceration\n**Health and healthcare**: Access to care, health literacy, insurance\n**Neighbourhood/built environment**: Housing quality, access to healthy food, crime, environmental conditions\n\n## Evidence for SDOH Impact\n- A person living in poverty has a 10-year lower life expectancy than a wealthy counterpart\n- Education: Each year of schooling associated with 1-2% lower mortality\n- Employment: Unemployment associated with 63% higher mortality\n- Housing: Homelessness associated with life expectancy of 47-48 years\n\n## India Context\n- **Caste-based discrimination**: Dalits have significantly worse health outcomes across all indicators\n- **Gender**: India's girl child malnutrition and maternal mortality driven by SDOH\n- **Rural-urban divide**: Rural India has 3× higher infant mortality than urban\n- **PMJAY/Ayushman Bharat**: Addresses financial access — but not upstream SDOH`,
        examples: [{ title: 'SDOH impact on TB outcomes in India', language: 'text', code: `TUBERCULOSIS IN INDIA — SDOH ANALYSIS:\n\nIndia accounts for 26% of global TB burden (2.1M new cases/year)\n\nBIOLOGICAL FACTOR:\n• M. tuberculosis infection\n\nBUT WHY IS TB CONCENTRATED IN POOR COMMUNITIES?\n\nSDOH FACTORS:\n                         Rich      Poor\nHousehold crowding:      Low       High (1 room/8 people)\nNutrition status:        Good      Underweight → immunosuppressed\nAir quality:             Clean     Indoor smoke (biomass cooking)\nHealthcare access:       Private   Limited (DOTS compliance issues)\nHIV co-infection:        Lower     Higher (PWID, urban slums)\nDiabetes:                Treated   Uncontrolled (SDOH effect)\n\nRESULT: Poor communities face MULTIPLICATIVE risk:\nCrowded + malnourished + undiagnosed DM + limited care\n= dramatically higher TB incidence AND worse outcomes\n\nINTERVENTION BEYOND ANTIBIOTICS:\n• Food supplementation for TB patients (NIKSHAY Poshan Yojana)\n• Social support for treatment completion\n• Addressing indoor air pollution`, explanation: 'TB is a social disease as much as a biological one. Antibiotics cure it, but SDOH explains why it concentrates in marginalised populations.' }],
        keyPoints: ['SDOH explain up to 80% of health outcomes — more than healthcare itself. Addressing only biology without addressing poverty is insufficient', 'Health inequity = systematic, avoidable differences in health between social groups — it is not random, it is caused by unfair social conditions', 'India\'s high out-of-pocket health expenditure (58%) itself is a major SDOH — medical costs push 63 million Indians into poverty annually']
      },
      evaluate: { questions: [{ question: 'Social Determinants of Health primarily refers to:', options: ['Genetic factors that determine disease risk', 'The conditions in which people are born, grow, live, work, and age — shaped by social and economic structures', 'Personal lifestyle choices only', 'The quality of healthcare facilities'], correctIndex: 1, explanation: 'SDOH are the upstream conditions (income, education, housing, environment) that shape health before any clinical encounter. The Commission on SDOH (WHO) identified these as primary health drivers.' }, { question: 'Why does India have higher TB rates in urban slums?', options: ['Different TB strain variant in slums', 'Better TB testing in slums', 'Convergence of SDOH: crowding, malnutrition, indoor air pollution, limited healthcare access — all amplify transmission and worsen outcomes', 'Climate factors in cities'], correctIndex: 2, explanation: 'TB in Indian slums is driven by converging SDOH: household crowding increases transmission; malnutrition impairs immunity; indoor smoke from cooking damages lungs; limited access to diagnosis and treatment prolongs infectious period.' }, { question: 'Health inequity differs from health inequality because:', options: ['Inequity is biological; inequality is social', 'Inequity is the same as inequality', 'Inequity refers specifically to systematic, avoidable, unjust differences in health — inequality is any difference (including natural variation)', 'Inequity is only measurable in rich countries'], correctIndex: 2, explanation: 'Inequality = any measurable difference. Inequity = systematic, avoidable, unjust differences. Dalit vs upper caste health outcomes are inequitable — they are caused by discrimination, not biology.' }] }
    },
  },
  'Pharmacology Basics': {
    'Pharmacokinetics (ADME)': {
      understand: {
        theory: `# Pharmacokinetics — ADME\nPharmacokinetics = what the body does to the drug. ADME describes the four processes.\n\n## A — Absorption\nDrug movement from administration site to bloodstream.\n- **Oral bioavailability**: % of dose reaching systemic circulation unchanged\n- **First-pass metabolism**: Liver metabolises drug before reaching systemic circulation → reduces oral bioavailability\n- **Factors**: Route (IV > IM > subcutaneous > oral), formulation, food, pH\n\n## D — Distribution\nDrug spread from blood to tissues.\n- **Volume of Distribution (Vd)**: Apparent volume in which drug distributes\n  - Vd = Drug dose / Plasma concentration\n  - High Vd (>60L): drug concentrates in tissues (e.g., chloroquine Vd = 200-800L)\n  - Low Vd (<10L): drug stays in plasma (e.g., heparin)\n- **Protein binding**: Only unbound drug is active; highly protein-bound drugs have long duration\n\n## M — Metabolism\nChemical transformation, primarily by liver CYP450 enzymes.\n- **Prodrug**: Inactive form metabolised to active drug (codeine → morphine)\n- **Enzyme induction**: Rifampicin induces CYP450 → reduces plasma levels of other drugs\n- **Enzyme inhibition**: Ketoconazole inhibits CYP3A4 → increases levels of many drugs\n\n## E — Excretion\nPrimarily renal (urine) or biliary (faeces).\n- **Half-life (t½)**: Time for plasma concentration to halve\n- **Steady state**: Reached after ~5 half-lives of repeated dosing\n- Renal impairment → dose reduction for renally-cleared drugs`,
        examples: [{ title: 'First-pass metabolism effect', language: 'text', code: `FIRST-PASS METABOLISM EXAMPLE:\n\nDrug: Glyceryl Trinitrate (GTN) for angina\n\nORAL ADMINISTRATION:\n• Dose: 10mg orally\n• First-pass metabolism: ~98% destroyed by liver\n• Bioavailability: ~2%\n• Systemic drug reaching heart: 0.2mg\n→ INSUFFICIENT for therapeutic effect\n\nSUBLINGUAL ADMINISTRATION:\n• Dose: 0.5mg under tongue\n• Absorbed directly into systemic circulation\n• Bypasses liver entirely\n• Bioavailability: ~80%\n→ THERAPEUTIC effect in 2-5 minutes\n\nOTHER BYPASS ROUTES:\n• Transdermal (GTN patches): bypasses first-pass\n• IV: 100% bioavailability always\n• Inhalation: bypasses GI tract (rapid onset)\n\nCLINICAL RULE:\nDrugs with high first-pass effect CANNOT be given orally\nwithout dose adjustment or alternative route`, explanation: 'First-pass effect explains why some drugs require different routes — understanding this prevents under-dosing (or toxicity when routes are switched).' }],
        keyPoints: ['Bioavailability of IV injection = 100% always (direct systemic entry). All other routes are less than 100% due to absorption barriers and first-pass metabolism', 'Half-life determines dosing frequency: drugs with short half-life need frequent dosing; drugs with long half-life (amiodarone t½ = 40-55 days) have prolonged effects after stopping', 'Renal impairment reduces excretion — renally-cleared drugs (aminoglycosides, lithium, metformin) require dose reduction or monitoring to prevent accumulation and toxicity']
      },
      evaluate: { questions: [{ question: 'First-pass metabolism occurs:', options: ['In the kidney before drug is excreted', 'When drug is metabolised in the liver before reaching systemic circulation (after oral administration)', 'At the receptor site', 'During intravenous administration'], correctIndex: 1, explanation: 'First-pass: after oral absorption, drug passes through portal circulation to liver before entering systemic circulation. Liver metabolises significant fractions — reduces bioavailability of many drugs.' }, { question: 'Volume of distribution (Vd) indicates:', options: ['The volume of blood in the body', 'The rate of drug elimination', 'The apparent volume in which a drug distributes — high Vd means extensive tissue distribution', 'The dose needed to treat the patient'], correctIndex: 2, explanation: 'High Vd means drug distributes widely into tissues (low plasma concentration for given dose). Low Vd means drug stays in plasma. Important for calculating loading doses.' }, { question: 'Steady state drug concentration is reached after approximately:', options: ['1 half-life', '2 half-lives', '5 half-lives', '10 half-lives'], correctIndex: 2, explanation: 'Steady state = when drug in = drug out. Reached after ~5 half-lives of regular dosing. Warfarin (t½ = 36-42h) takes about 5-7 days to reach steady state.' }] }
    },
    'Drug-Receptor Interactions': {
      understand: {
        theory: `# Drug-Receptor Interactions\nMost drug effects result from interaction with specific receptor proteins. Understanding receptor pharmacology explains drug mechanisms, dose-response, and side effects.\n\n## Types of Drug-Receptor Interactions\n**Full Agonist**: Binds receptor + produces maximum response (e.g., adrenaline at β1 receptors)\n**Partial Agonist**: Binds + produces submaximal response even at full receptor occupancy (e.g., buprenorphine at opioid receptors)\n**Competitive Antagonist**: Binds receptor without activating it; blocks agonist; effect reversible with higher agonist dose (e.g., naloxone at opioid receptors)\n**Non-competitive Antagonist**: Irreversibly blocks receptor; cannot be overcome by more agonist (e.g., aspirin — irreversibly inhibits COX)\n\n## Key Pharmacodynamic Concepts\n**Affinity**: How strongly drug binds to receptor\n**Efficacy/Intrinsic activity**: Ability to produce response after binding\n**Potency**: Dose needed to produce 50% maximal effect (ED50 — lower dose = more potent)\n**Therapeutic Index (TI)** = LD50 / ED50\n- High TI = wide safety margin (penicillin TI = very high)\n- Narrow TI = toxic dose close to effective dose (digoxin, warfarin, lithium)\n\n## Receptor Types\n- **G-protein coupled receptors**: β-blockers, opioids, muscarinic (most drug targets)\n- **Ion channels**: Benzodiazepines (GABA-A), local anaesthetics (Na channels)\n- **Nuclear receptors**: Steroids, thyroid hormone\n- **Enzyme receptors**: Insulin (tyrosine kinase)`,
        examples: [{ title: 'Agonist vs antagonist — clinical scenario', language: 'text', code: `CLINICAL SCENARIO: Opioid Toxicity\n\nPATIENT: Found unresponsive after heroin overdose\nPresentation: Unconscious, not breathing, pinpoint pupils\n\nHEROIN → MORPHINE:\n• Full opioid agonist at μ (mu) opioid receptors\n• Effect: Analgesia, euphoria, respiratory depression\n\nTREATMENT: NALOXONE (NARCAN)\n• Competitive antagonist at μ receptors\n• Displaces morphine from receptor\n• Reverses respiratory depression within 2 minutes\n• Dose: 0.4-2mg IV/IM/intranasal\n\nIMPORTANT PHARMACOKINETICS:\n• Heroin half-life: short (minutes)\n• Morphine half-life: 2-3 hours\n• Naloxone half-life: 30-90 minutes\n\nCLINICAL PROBLEM:\nNaloxone wears off BEFORE morphine\n→ Patient may re-narcotise after initial reversal\n→ MUST observe for 4-6 hours and may need repeat doses`, explanation: 'Competitive antagonist (naloxone) reversal of full agonist (morphine) is a life-saving clinical application of receptor pharmacology.' }],
        keyPoints: ['Narrow Therapeutic Index (NTI) drugs — digoxin, warfarin, lithium, phenytoin, aminoglycosides — require blood level monitoring because toxic dose is close to therapeutic dose', 'Partial agonists are useful in opioid addiction (buprenorphine) — provide some opioid effect reducing withdrawal while ceiling effect limits overdose risk', 'Aspirin irreversibly inhibits COX-1 in platelets. Since platelets have no nucleus, they cannot make new COX — effect lasts the platelet lifespan (7-10 days) regardless of aspirin\'s short half-life']
      },
      evaluate: { questions: [{ question: 'A competitive antagonist differs from a non-competitive antagonist because:', options: ['Competitive antagonists are more toxic', 'The effect of a competitive antagonist can be overcome by increasing the agonist dose; non-competitive antagonists cannot', 'Non-competitive antagonists work faster', 'They act on different receptors'], correctIndex: 1, explanation: 'Competitive: reversible binding — can be displaced with more agonist. Non-competitive (e.g., aspirin on COX): irreversible binding — more agonist cannot restore response regardless of concentration.' }, { question: 'Therapeutic Index (TI) of a drug is:', options: ['The number of indications the drug has', 'LD50 / ED50 — the ratio of lethal to effective dose; high TI = safe; narrow TI = dangerous', 'The interval between doses', 'The number of interactions the drug has'], correctIndex: 1, explanation: 'High TI = large margin between effective dose and dangerous dose (e.g., penicillin). Narrow TI = toxic dose close to therapeutic dose (e.g., digoxin, warfarin, lithium) — require careful monitoring.' }, { question: 'Why does aspirin\'s antiplatelet effect last 7-10 days despite its short plasma half-life of 20 minutes?', options: ['Aspirin accumulates in platelets', 'Aspirin irreversibly inhibits COX-1 — platelets cannot regenerate the enzyme since they have no nucleus; effect lasts platelet lifespan', 'Aspirin is stored in fat tissue', 'The drug converts to an active metabolite with longer half-life'], correctIndex: 1, explanation: 'Aspirin covalently (irreversibly) acetylates COX-1. Platelets are anucleate — cannot synthesise new protein. Antiplatelet effect persists until new platelets are made (7-10 day platelet lifespan).' }] }
    },
  },
  'Mental Health & Psychology': {
    'Psychological Theories': {
      understand: {
        theory: `# Major Psychological Theories\nPsychological theories provide frameworks for understanding human behaviour, thought, and emotion.\n\n## Psychoanalytic Theory (Freud)\n- **Unconscious mind** drives much of behaviour\n- **Id** (instinctual drives) vs **Ego** (reality principle) vs **Superego** (morality)\n- **Defence mechanisms**: Repression, projection, rationalisation, denial\n- Influence: Therapy (free association, dream analysis); developmental stages\n\n## Behaviourism (Watson, Skinner)\n- Psychology = observable behaviour; ignore internal states\n- **Classical conditioning** (Pavlov): Neutral stimulus paired with unconditioned → conditioned response\n- **Operant conditioning** (Skinner): Behaviour shaped by consequences (reinforcement/punishment)\n- Application: Behaviour therapy, phobia treatment (systematic desensitisation)\n\n## Cognitive Theory (Beck, Ellis)\n- Thoughts (cognitions) mediate between events and emotions\n- **Cognitive triad** (depression): Negative view of self + world + future\n- **Automatic negative thoughts** → emotional distress\n- Application: CBT (Cognitive Behavioural Therapy) — most evidence-based psychotherapy\n\n## Humanistic Psychology (Maslow, Rogers)\n- Focus on growth, self-actualisation, unconditional positive regard\n- **Maslow's hierarchy**: Physiological → Safety → Love → Esteem → Self-actualisation\n- Application: Person-centred therapy`,
        examples: [{ title: 'Cognitive model of depression — Beck', language: 'text', code: `BECK'S COGNITIVE MODEL OF DEPRESSION:\n\nTRIGGERING EVENT:\nJob rejection\n\nAUTOMATIC NEGATIVE THOUGHTS:\n• "I'm completely worthless"\n• "I always fail at everything"\n• "Nobody will ever want to hire me"\n\nCOGNITIVE DISTORTIONS:\n• All-or-nothing thinking: "always/never"\n• Overgeneralisation: one failure = total failure\n• Mind reading: assuming others think negatively\n• Catastrophising: "nobody will ever hire me"\n\nEMOTIONAL RESPONSE:\n• Depression, hopelessness, worthlessness\n\nBEHAVIOURIOAL RESPONSE:\n• Withdrawal, not applying for jobs\n\nCBT INTERVENTION:\n1. Identify automatic thought\n2. Challenge: What's the evidence for/against?\n3. Reframe: "One rejection doesn't define my worth"\n4. Behavioural activation: Continue applying despite feelings`, explanation: 'Beck\'s cognitive model makes the link between thoughts and mood explicit. CBT teaches patients to identify, challenge, and reframe distorted thinking patterns.' }],
        keyPoints: ['CBT (Cognitive Behavioural Therapy) is the most evidence-based psychological treatment — effective for depression, anxiety, OCD, PTSD, eating disorders', 'Maslow\'s hierarchy is descriptive, not prescriptive — research shows humans often pursue higher needs even when lower ones are unmet', 'Psychoanalytic concepts (unconscious, defence mechanisms, transference) remain clinically relevant even though the full theory is not evidence-based']
      },
      evaluate: { questions: [{ question: 'Operant conditioning (Skinner) shapes behaviour through:', options: ['Pairing neutral stimuli with natural responses', 'Consequences — reinforcement increases behaviour; punishment decreases it', 'Changing thought patterns', 'Unconscious drives and defence mechanisms'], correctIndex: 1, explanation: 'Operant conditioning: behaviour is shaped by its consequences. Positive reinforcement (reward) increases behaviour; punishment decreases it. Used in behaviour therapy, habit formation.' }, { question: 'Beck\'s Cognitive Triad in depression consists of:', options: ['Id, Ego, and Superego', 'Negative views of self, world, and the future', 'Stimulus, response, and reinforcement', 'Physiological, social, and psychological needs'], correctIndex: 1, explanation: 'Beck\'s triad: "I am worthless, the world is unfair, the future is hopeless." These automatic negative cognitions maintain depressive mood — target of CBT.' }, { question: 'Classical conditioning (Pavlov) involves:', options: ['Learning through consequences', 'Pairing a neutral stimulus with an unconditioned stimulus until the neutral stimulus alone produces the response', 'Unconscious processing of trauma', 'Cognitive reappraisal of events'], correctIndex: 1, explanation: 'Classical conditioning: bell (neutral) paired with food (unconditioned) → dog salivates to bell alone (conditioned). In clinical practice: phobias often develop through classical conditioning of fear.' }] }
    },
    'DSM-5 Diagnostic Criteria': {
      understand: {
        theory: `# DSM-5 Diagnostic Framework\nThe Diagnostic and Statistical Manual of Mental Disorders, 5th Edition (DSM-5) is the standard classification system for psychiatric diagnosis in most countries.\n\n## Key Structural Features of DSM-5\n- **Polythetic criteria**: Must meet X of Y criteria (not all required)\n- **Duration thresholds**: Symptoms must persist for minimum periods\n- **Functional impairment**: Symptoms must cause distress or impair functioning\n- **Rule-out clauses**: Not attributable to substances, medical conditions, or better explained by another disorder\n\n## Major Depressive Disorder (MDD) — DSM-5\n5+ symptoms for ≥2 weeks; at least one = depressed mood OR anhedonia:\n1. Depressed mood most of the day\n2. Loss of interest/pleasure (anhedonia)\n3. Weight/appetite change\n4. Sleep disturbance (insomnia or hypersomnia)\n5. Psychomotor agitation or retardation\n6. Fatigue/loss of energy\n7. Worthlessness or excessive guilt\n8. Difficulty concentrating\n9. Recurrent thoughts of death or suicidal ideation\n\n## Generalised Anxiety Disorder (GAD) — DSM-5\nExcessive anxiety ≥6 months + 3+ of: restlessness, fatigue, concentration difficulties, irritability, muscle tension, sleep disturbance\n\n## Schizophrenia — DSM-5\n2+ symptoms ≥1 month (at least one = delusions/hallucinations/disorganised speech): + occupational dysfunction >6 months`,
        examples: [{ title: 'DSM-5 in clinical practice', language: 'text', code: `CASE: Priya, 28F, software engineer\nPresents with: "I've been feeling awful for 3 months"\n\nSYMPTOM REVIEW:\n✓ Depressed mood most days for 3 months\n✓ Lost interest in coding, gym, friends (anhedonia)\n✓ Weight loss 4kg (appetite down)\n✓ Insomnia — waking at 3am, can't sleep\n✓ Profound fatigue — "exhausted even after 8 hours"\n✓ Feeling worthless, blaming herself\n✓ Difficulty concentrating — errors at work\n✓ No suicidal ideation currently\n× Psychomotor change — not clearly present\n\nDSM-5 CHECKLIST:\n• Symptom count: 7 of 9 ✓ (needs 5)\n• Duration: 3 months ✓ (needs 2 weeks)\n• Functional impairment: Yes — work affected ✓\n• Not substance-related ✓\n• Depressed mood + anhedonia both present ✓\n\nDIAGNOSIS: Major Depressive Disorder\nSpecifier: Moderate severity (7/9 symptoms, work impairment)\nPLAN: CBT + SSRI + safety assessment + sleep hygiene`, explanation: 'DSM-5 criteria apply systematically — not "vibes". Counting symptoms, checking duration, and ruling out other causes ensures diagnostic reliability.' }],
        keyPoints: ['DSM-5 requires BOTH symptom criteria AND functional impairment — subclinical symptoms causing no distress don\'t meet diagnostic threshold', 'Comorbidity is common — 70% of people with depression also have anxiety; comorbid diagnoses require separate treatment attention', 'Differential diagnosis: medical conditions (hypothyroidism, anaemia, malignancy) can mimic psychiatric disorders — rule these out before psychiatric diagnosis']
      },
      evaluate: { questions: [{ question: 'For Major Depressive Episode diagnosis per DSM-5, the minimum required symptoms are:', options: ['2 symptoms for 1 week', '3 symptoms for 3 weeks', '5 symptoms for 2 weeks (including depressed mood or anhedonia)', 'Any 5 symptoms for any duration'], correctIndex: 2, explanation: 'MDD requires 5+ symptoms for ≥2 weeks AND at least one of the first two (depressed mood or anhedonia) must be present. Duration and anchor symptoms are essential.' }, { question: 'DSM-5 diagnosis always requires:', options: ['A specific biological test or imaging finding', 'Symptoms cause clinically significant distress or functional impairment — not just presence of symptoms alone', 'At least 12 months of symptoms', 'Psychiatric hospitalisation'], correctIndex: 1, explanation: 'DSM-5 requires functional impairment — symptoms that don\'t significantly affect daily life don\'t meet diagnostic threshold. This prevents over-pathologising normal distress.' }, { question: 'Schizophrenia diagnosis in DSM-5 requires active symptoms for at least:', options: ['1 week', '1 month (active phase) with total disturbance >6 months', '3 months', '12 months continuously'], correctIndex: 1, explanation: 'Schizophrenia: ≥2 active-phase symptoms for 1+ month, with continuous signs of disturbance for ≥6 months. Brief psychotic disorder and schizophreniform have shorter durations.' }] }
    },
  },
  'Nutrition Science': {
    'Macronutrients (Carbs/Proteins/Fats)': {
      understand: {
        theory: `# Macronutrients\nMacronutrients are the energy-providing nutrients required in large quantities: carbohydrates, proteins, and fats.\n\n## Carbohydrates\n**Energy**: 4 kcal/g\n**Types**:\n- Simple (sugars): Glucose, fructose, sucrose — rapid absorption, high glycaemic index\n- Complex (starch): Slow digestion, steady glucose release\n- Dietary fibre: Non-digestible; feeds gut microbiome; reduces cholesterol and glycaemic response\n\n**Recommended**: 45-65% of total calories; prefer complex/high-fibre sources\n\n## Proteins\n**Energy**: 4 kcal/g\n**Functions**: Building/repairing tissues, enzymes, hormones, antibodies, transport proteins\n**Essential amino acids**: 9 cannot be synthesised by body (must be consumed)\n**Complete proteins**: Contain all essential AAs (eggs, meat, fish, dairy, soy)\n**Incomplete proteins**: Missing 1+ essential AA (most plant proteins — combine complementary sources)\n**Recommended**: 0.8g/kg/day (sedentary); 1.2-1.7g/kg/day (athletes)\n\n## Fats\n**Energy**: 9 kcal/g (most energy-dense)\n**Types**:\n- **Saturated**: Animal products; raise LDL (limit to <10% calories)\n- **Unsaturated (mono/poly)**: Olive oil, nuts, fish; anti-inflammatory; lower LDL\n- **Trans fats**: Artificially hydrogenated; raise LDL + lower HDL (most harmful; banned in many countries)\n- **Omega-3 (EPA/DHA)**: Fatty fish, flaxseed; anti-inflammatory; cardioprotective`,
        examples: [{ title: 'Macronutrient calculation for a student', language: 'text', code: `MACRONUTRIENT CALCULATION:\nStudent: Male, 22 years, 70kg, moderately active\n\nSTEP 1: Calculate TDEE (Total Daily Energy Expenditure)\nBMR (Mifflin-St Jeor):\n= (10 × 70) + (6.25 × 175) - (5 × 22) + 5\n= 700 + 1093.75 - 110 + 5 = 1688.75 kcal\n\nActivity multiplier (moderate = 1.55):\nTDEE = 1689 × 1.55 = 2618 kcal/day\n\nSTEP 2: Macronutrient Split (balanced)\n• Protein: 1.5g/kg = 105g → 420 kcal (16%)\n• Fat: 25% of TDEE = 654 kcal → 73g\n• Carbs: Remainder = 1544 kcal → 386g (59%)\n\nFOOD EXAMPLES:\n105g protein = 3 eggs + 150g chicken + 200g dahi + 100g paneer\n73g fat = 4 tsp ghee + 30g nuts + cooking oil\n386g carbs = 3 cups rice + 4 roti + fruits + vegetables`, explanation: 'Macronutrient targets are personalised — vary by body weight, activity level, and goals (weight loss/gain/maintenance). Tracking enables precision nutrition.' }],
        keyPoints: ['Dietary fibre (complex carb) reduces postprandial glucose spike, lowers cholesterol, and feeds beneficial gut microbiome — most Indians consume <half the recommended 25-38g/day', 'Not all fats are bad — monounsaturated (olive oil) and omega-3 (fish, flaxseed) are protective. Trans fats are uniquely harmful — raise LDL AND lower HDL simultaneously', 'Protein quality matters: animal proteins are complete; plant proteins require combination (rice + lentils = complete protein). Important for vegetarian Indian diets']
      },
      evaluate: { questions: [{ question: 'Complete proteins contain:', options: ['All 9 essential amino acids', 'Only branched-chain amino acids', 'The highest amount of calories', 'Only plant-based amino acids'], correctIndex: 0, explanation: 'Complete proteins provide all 9 essential amino acids (which cannot be synthesised). Animal products (eggs, meat, dairy) and soy are complete. Most plant proteins are incomplete — combine rice + legumes for completeness.' }, { question: 'Trans fats are particularly harmful because:', options: ['They contain the most calories per gram', 'They both raise LDL (bad) cholesterol AND lower HDL (good) cholesterol simultaneously', 'They cause kidney damage', 'They are only found in fast food'], correctIndex: 1, explanation: 'Trans fats (partially hydrogenated oils) are the most harmful dietary fat — they raise LDL and lower HDL. Most health authorities recommend <1% of calories from trans fats.' }, { question: 'The energy density of fat compared to carbohydrates and protein is:', options: ['Same as both (4 kcal/g)', 'Lower (3 kcal/g)', 'Higher (9 kcal/g) — more than double carbs/protein', 'The same as carbohydrates (4 kcal/g) but more than protein'], correctIndex: 2, explanation: 'Fat = 9 kcal/g; carbohydrates and protein = 4 kcal/g each. Fat\'s high energy density means small amounts provide significant calories — relevant for calorie-counting and obesity.' }] }
    },
  },
};
