export const MEDICINE_CONTENT: Record<string, Record<string, any>> = {
  'Medical Terminology': {
    'Anatomical Terminology': {
      understand: {
        theory: `# Anatomical Terminology\nMedical language uses standardised terms based primarily on Greek and Latin roots. Anatomical position is the reference point: body upright, facing forward, arms at sides, palms forward.\n\n## Directional Terms\n| Term | Meaning | Example |\n|------|---------|----------|\n| Anterior/Ventral | Front | Sternum is anterior to spine |\n| Posterior/Dorsal | Back | Spine is posterior to sternum |\n| Superior/Cranial | Above | Head is superior to neck |\n| Inferior/Caudal | Below | Stomach is inferior to lungs |\n| Medial | Toward midline | Heart is medial to lungs |\n| Lateral | Away from midline | Lungs are lateral to heart |\n| Proximal | Closer to attachment | Shoulder is proximal to wrist |\n| Distal | Farther from attachment | Hand is distal to elbow |\n\n## Body Planes\n- **Sagittal**: Divides left/right (midsagittal = equal halves)\n- **Frontal/Coronal**: Divides front/back\n- **Transverse/Horizontal**: Divides top/bottom\n\n## Body Cavities\n- **Dorsal**: Cranial (brain) + Spinal (cord)\n- **Ventral**: Thoracic (lungs/heart) + Abdominopelvic (organs/reproductive)`,
        examples: [{ title: 'Clinical note using anatomical terms', language: 'text', code: `CLINICAL EXAMPLE:\n"Patient presents with tenderness in the right lower\nquadrant (RLQ) of the abdomen, approximately 5 cm\nlateral to the midline and 3 cm inferior to the\numbilicus. Pain radiates from the RLQ to the right\nflank in the posterior direction."\n\nBREAKDOWN:\n• Right lower quadrant = specific regional location\n• Lateral to midline = away from center\n• Inferior to umbilicus = below the navel\n• Posterior = toward the back\n\nDIAGNOSTIC SIGNIFICANCE:\nRLQ pain → primary concern: appendicitis\n(appendix located in RLQ; McBurney's point = 2/3\ndistance from umbilicus to right anterior iliac spine)`, explanation: 'Precise anatomical language enables any clinician to immediately understand the location without ambiguity — critical for documentation and consultations.' }],
        keyPoints: ['Anatomical position is the universal reference point — all directional terms are relative to this standard position', 'Medial = toward midline of body; lateral = away from midline. These are relative terms, not absolute left/right', 'The 9 abdominal regions (RUQ, epigastric, LUQ, right flank, umbilical, left flank, RLQ, hypogastric, LLQ) are essential for clinical documentation']
      },
      evaluate: { questions: [{ question: 'The knee is ___ to the hip:', options: ['Superior', 'Inferior', 'Proximal', 'Lateral'], correctIndex: 1, explanation: 'Inferior = below/toward the feet. The hip is superior (above) the knee; therefore the knee is inferior to the hip.' }, { question: 'A transverse (horizontal) plane divides the body into:', options: ['Left and right halves', 'Anterior and posterior halves', 'Superior and inferior halves', 'Medial and lateral halves'], correctIndex: 2, explanation: 'Transverse/horizontal plane cuts the body into upper (superior) and lower (inferior) sections — like cutting a body at the waist.' }, { question: 'The radius bone (forearm) is ___ to the humerus (upper arm):', options: ['Medial', 'Lateral', 'Distal', 'Inferior'], correctIndex: 2, explanation: 'Distal = farther from the point of limb attachment (shoulder). Radius is distal to the humerus; humerus is proximal to the radius.' }] }
    },
    'Medical Prefixes & Suffixes': {
      understand: {
        theory: `# Medical Prefixes & Suffixes\nMedical terms are constructed from building blocks. Understanding roots, prefixes, and suffixes allows you to decode any medical term.\n\n## Common Prefixes\n| Prefix | Meaning | Example |\n|--------|---------|----------|\n| a-/an- | Without/absence | Anemia (no iron/blood) |\n| brady- | Slow | Bradycardia (slow heart) |\n| tachy- | Fast | Tachycardia (fast heart) |\n| hyper- | Above/excess | Hypertension |\n| hypo- | Below/deficiency | Hypoglycemia |\n| peri- | Around | Pericardium |\n| intra- | Within | Intravenous |\n| post- | After | Postoperative |\n\n## Common Suffixes\n| Suffix | Meaning | Example |\n|--------|---------|----------|\n| -itis | Inflammation | Appendicitis |\n| -ectomy | Surgical removal | Appendectomy |\n| -ology | Study of | Cardiology |\n| -oscopy | Visual examination | Colonoscopy |\n| -oma | Tumor/mass | Carcinoma |\n| -plasty | Surgical repair | Rhinoplasty |\n| -rrhagia | Excessive flow | Hemorrhagia |\n| -emia | Blood condition | Anemia, Septicemia |`,
        examples: [{ title: 'Decoding complex medical terms', language: 'text', code: `TERM: "electrocardiography"\nBreakdown:\n  electro- = electricity\n  cardio-  = heart\n  -graphy  = process of recording\nMeaning: Recording the electrical activity of the heart\n\nTERM: "gastrointestinal"\n  gastro-  = stomach\n  intestin- = intestine\n  -al      = pertaining to\nMeaning: Pertaining to the stomach and intestines\n\nTERM: "pancreatitis"\n  pancreato- = pancreas\n  -itis      = inflammation\nMeaning: Inflammation of the pancreas\n\nTERM: "subcutaneous"\n  sub-    = under/below\n  cutane- = skin\n  -ous    = pertaining to\nMeaning: Pertaining to (the area) beneath the skin`, explanation: 'Break any medical term into prefix + root + suffix. This decoding skill is more valuable than memorising 10,000 individual terms.' }],
        keyPoints: ['-itis = inflammation; -oma = tumor; -ectomy = removal; -oscopy = visual exam. These four cover a huge portion of clinical documentation', 'The same root can combine with different suffixes: cardi(o) + -logy = cardiology (study), + -gram = cardiogram (recording), + -megaly = cardiomegaly (enlargement)', 'Always understand context — "hyper-" with thyroid = too much hormone; "hypo-" with glycemia = too little blood sugar']
      },
      evaluate: { questions: [{ question: 'What does "hepat-itis" mean?', options: ['Removal of the liver', 'Study of the liver', 'Inflammation of the liver', 'X-ray of the liver'], correctIndex: 2, explanation: 'Hepat(o)- = liver; -itis = inflammation. Hepatitis = inflammation of the liver (commonly caused by hepatitis A/B/C viruses).' }, { question: 'Tachycardia means:', options: ['Slow heart rate (< 60 bpm)', 'Abnormal heart rhythm', 'Fast heart rate (> 100 bpm)', 'Heart inflammation'], correctIndex: 2, explanation: 'Tachy- = fast; cardio = heart; -ia = condition. Tachycardia = heart rate > 100 beats per minute.' }, { question: 'The suffix -ectomy means:', options: ['Inflammation', 'Surgical removal', 'Visual examination', 'Recording/measurement'], correctIndex: 1, explanation: '-ectomy = surgical excision/removal. Appendectomy = removal of appendix; cholecystectomy = removal of gallbladder.' }] }
    },
    'Body Systems Overview': {
      understand: {
        theory: `# Body Systems Overview\n## The 11 Major Body Systems\n1. **Integumentary**: Skin, hair, nails — protection, temperature regulation\n2. **Skeletal**: 206 bones — support, protection, movement, blood cell production\n3. **Muscular**: 600+ muscles — movement, posture, heat production\n4. **Nervous**: Brain, spinal cord, nerves — communication, control\n5. **Endocrine**: Glands, hormones — chemical communication, homeostasis\n6. **Cardiovascular**: Heart, blood vessels — transport of O2, nutrients, waste\n7. **Lymphatic/Immune**: Lymph nodes, thymus — immunity, fluid balance\n8. **Respiratory**: Lungs, airways — gas exchange (O2 in, CO2 out)\n9. **Digestive**: GI tract — digestion, absorption, elimination\n10. **Urinary**: Kidneys, bladder — filtration, excretion, fluid balance\n11. **Reproductive**: Gonads, accessory organs — reproduction, sex hormones\n\n## Homeostasis\nThe tendency of the body to maintain internal stability. Disruption of homeostasis = disease.\n\n**Negative feedback** (most common): Response reduces the stimulus\nExample: Rising blood glucose → insulin released → glucose taken up → glucose falls`,
        examples: [{ title: 'Cardiovascular system — quick clinical overview', language: 'text', code: `CARDIOVASCULAR SYSTEM:\n\nStructure:\n• Heart: 4 chambers (RA, LA, RV, LV)\n• Pulmonary circulation: Heart → Lungs → Heart\n  (right side pumps deoxygenated blood to lungs)\n• Systemic circulation: Heart → Body → Heart\n  (left side pumps oxygenated blood to body)\n\nKey vessels:\n• Aorta: Largest artery; carries oxygenated blood from LV\n• Pulmonary artery: Carries deoxygenated blood to lungs\n• Vena cava (Superior + Inferior): Returns deoxygenated blood to RA\n\nClinical links:\n• Hypertension → Damage to arterial walls → Atherosclerosis → MI/Stroke\n• Heart failure → Left = pulmonary edema; Right = peripheral edema\n• Coronary artery disease = blockage of arteries supplying heart muscle`, explanation: 'Understanding the cardiovascular loop (right side = pulmonary, left side = systemic) is foundational for understanding most cardiac pathology.' }],
        keyPoints: ['All 11 body systems are interdependent — disease in one system affects others. Diabetes (endocrine) damages cardiovascular, nervous, and urinary systems', 'Homeostasis via negative feedback is the fundamental operating principle — most diseases are failures of feedback regulation', 'The autonomic nervous system (sympathetic = fight/flight; parasympathetic = rest/digest) controls most involuntary body functions']
      },
      evaluate: { questions: [{ question: 'The right side of the heart pumps blood to:', options: ['The entire body (systemic circulation)', 'The lungs (pulmonary circulation) for oxygenation', 'The liver only', 'The brain and upper body'], correctIndex: 1, explanation: 'Right side = pulmonary circulation. Deoxygenated blood from body → RA → RV → pulmonary artery → lungs. Left side handles systemic circulation.' }, { question: 'Negative feedback in homeostasis means:', options: ['A response that amplifies the original stimulus', 'A response that reduces/opposes the original stimulus to maintain balance', 'Feedback from nerves', 'Hormonal feedback only'], correctIndex: 1, explanation: 'Negative feedback restores homeostasis. Rising temperature → sweating → temperature falls. Rising blood sugar → insulin → glucose decreases.' }, { question: 'Which system is primarily responsible for blood glucose regulation?', options: ['Digestive system', 'Urinary system', 'Endocrine system (pancreas secretes insulin/glucagon)', 'Cardiovascular system'], correctIndex: 2, explanation: 'The endocrine system: pancreatic beta cells secrete insulin (lowers glucose); alpha cells secrete glucagon (raises glucose). Failure = diabetes mellitus.' }] }
    },
    'Clinical Documentation': {
      understand: {
        theory: `# Clinical Documentation\nAccurate documentation is a legal, ethical, and clinical requirement. Medical records must be contemporaneous, accurate, and complete.\n\n## SOAP Note Structure\n- **S** (Subjective): Patient's own description — chief complaint, HPI, review of systems\n- **O** (Objective): Measurable findings — vitals, physical examination, labs, imaging\n- **A** (Assessment): Clinical judgment — diagnosis, differential diagnoses\n- **P** (Plan): Management — investigations, treatment, follow-up, patient education\n\n## HPI (History of Present Illness) — OLDCARTS\n- **O**nset: When did it start?\n- **L**ocation: Where exactly?\n- **D**uration: How long has it lasted?\n- **C**haracter: Sharp, dull, burning, squeezing?\n- **A**lleviating/Aggravating factors\n- **R**adiation: Does it spread?\n- **T**iming: Constant, intermittent?\n- **S**everity: Pain scale 1-10\n\n## Prescription Writing\n- Drug name (generic preferred), dose, route, frequency, duration\n- e.g., "Tab. Amoxicillin 500mg PO TID × 7 days" (by mouth, three times daily)`,
        examples: [{ title: 'SOAP note for chest pain', language: 'text', code: `S: 48M presents with chest pain × 2 hours.\n   Sharp, substernal, 8/10. Started at rest.\n   Radiation to left arm. Diaphoresis+. No relief with antacids.\n   PMH: HTN, DM2, smoker 20 pack-years\n\nO: BP 156/94 mmHg, HR 102, RR 20, SpO2 97% RA\n   ECG: ST elevation leads II, III, aVF (inferior pattern)\n   Troponin I: Pending\n   Exam: Diaphoretic, mild respiratory distress\n\nA: 1. Inferior STEMI (ST-elevation Myocardial Infarction) — primary dx\n   2. Unstable angina — less likely (ECG changes present)\n   Differentials: Aortic dissection, PE — lower probability\n\nP: 1. Activate Cath Lab — primary PCI within 90 min\n   2. Aspirin 325mg PO STAT + Clopidogrel loading dose\n   3. IV heparin, oxygen if SpO2 <94%\n   4. Consult Cardiology STAT\n   5. Troponin repeat at 3 hours`, explanation: 'SOAP notes are concise yet complete. Assessment includes differential diagnosis. Plan addresses each problem systematically.' }],
        keyPoints: ['SOAP format is universal — any clinician can quickly scan a note and understand the complete clinical picture', 'OLDCARTS history framework ensures no critical symptom characterisation is missed — especially for pain assessment', 'Abbreviations must be used carefully — "QD" (once daily) vs "QID" (four times daily) — errors cause medication mistakes']
      },
      evaluate: { questions: [{ question: 'In SOAP documentation, the "Assessment" section contains:', options: ['Patient\'s reported symptoms', 'Vital signs and lab results', 'Clinical diagnosis and differential diagnoses', 'Treatment plan'], correctIndex: 2, explanation: 'Assessment = the clinician\'s interpretation — primary diagnosis and differentials. Distinguishes clinical judgment from raw data (Objective).' }, { question: 'HPI in medical documentation stands for:', options: ['Health Profile Index', 'History of Present Illness — the chronological story of the chief complaint', 'Hospital Protocol Index', 'High Priority Intervention'], correctIndex: 1, explanation: 'HPI is the narrative story of the patient\'s current complaint — when it started, character, progression, associated symptoms.' }, { question: 'Why is the OLDCARTS framework used in history-taking?', options: ['It is legally required', 'It ensures systematic pain/symptom characterisation — preventing missed dimensions of the clinical history', 'It speeds up documentation', 'For billing purposes only'], correctIndex: 1, explanation: 'OLDCARTS ensures all clinically relevant dimensions of a symptom are captured: onset, location, duration, character, alleviating/aggravating factors, radiation, timing, severity.' }] }
    },
    'Pharmacology Basics': {
      understand: {
        theory: `# Pharmacology Basics\n## Pharmacokinetics (What the body does to the drug)\nADME:\n- **Absorption**: Drug enters bloodstream (bioavailability — % of dose reaching systemic circulation)\n- **Distribution**: Drug spreads to tissues (Vd = volume of distribution)\n- **Metabolism**: Drug modified (primarily liver; CYP450 enzymes)\n- **Excretion**: Drug eliminated (primarily kidneys; half-life)\n\n## Pharmacodynamics (What the drug does to the body)\n- **Receptor agonist**: Activates receptor (e.g., morphine activates opioid receptors)\n- **Receptor antagonist**: Blocks receptor (e.g., naloxone blocks opioid receptors)\n- **Dose-response curve**: Higher dose → greater effect (up to ceiling)\n- **ED50**: Dose effective in 50% of population\n- **LD50**: Lethal dose in 50% — determines therapeutic index\n\n## Drug Interactions\n- **Pharmacokinetic**: One drug affects ADME of another\n  E.g., Rifampicin induces CYP450 → reduces levels of many drugs\n- **Pharmacodynamic**: Additive, synergistic, or antagonistic effects\n  E.g., Two CNS depressants → respiratory depression risk`,
        examples: [{ title: 'Drug half-life and dosing interval', language: 'text', code: `CONCEPT: Half-life (t½) = time for drug concentration to halve\n\nExample: Paracetamol t½ = 2-3 hours\n\nDosing schedule: 500mg every 4-6 hours\nRationale: Dose interval ≈ 1.5× t½ maintains therapeutic level\n\n5 × t½ = elimination (>96% cleared)\nParacetamol: 5 × 2.5h = ~12.5 hours to clear\n\nSTEADY STATE:\nReached after ~5 half-lives of regular dosing\n→ Drug in = Drug out (plateau concentration)\n\nCLINICAL IMPLICATION:\nAmiodarone (cardiac drug): t½ = 40-55 DAYS\n→ Loading dose needed to reach therapeutic levels quickly\n→ Effects persist long after stopping — critical for dosing adjustments`, explanation: 'Half-life determines dosing frequency and time to steady state. Long half-life drugs (amiodarone, warfarin) require careful dose adjustment.' }],
        keyPoints: ['Hepatic first-pass metabolism reduces oral bioavailability — some drugs have dramatically lower oral vs. IV effectiveness (e.g., lignocaine)', 'Narrow therapeutic index drugs (digoxin, warfarin, lithium) — small dose changes cause toxicity or therapeutic failure; require blood level monitoring', 'Renal impairment reduces drug excretion → dose adjustments needed to prevent accumulation and toxicity']
      },
      evaluate: { questions: [{ question: 'Bioavailability refers to:', options: ['How quickly a drug is absorbed', 'The fraction of an administered dose that reaches systemic circulation unchanged', 'How long a drug stays in the body', 'The drug\'s effectiveness at the receptor'], correctIndex: 1, explanation: 'Bioavailability = % of dose that reaches systemic circulation. IV injection = 100% bioavailability; oral drugs undergo first-pass metabolism, reducing it.' }, { question: 'A receptor antagonist:', options: ['Activates the receptor to produce a full response', 'Binds and activates the receptor weakly', 'Blocks the receptor, preventing the natural ligand or agonist from activating it', 'Destroys the receptor'], correctIndex: 2, explanation: 'Antagonists bind receptors without activating them, blocking agonist access. E.g., naloxone blocks opioid receptors, reversing morphine overdose.' }, { question: 'Why is drug excretion reduced in renal failure?', options: ['The liver compensates and metabolises more drug', 'The kidneys filter and excrete most drugs — impaired kidney function reduces drug clearance, causing drug accumulation', 'Drug absorption increases', 'Volume of distribution increases'], correctIndex: 1, explanation: 'Most drugs are renally excreted. Reduced GFR means drug accumulates to potentially toxic levels — dose reduction or longer intervals required.' }] }
    },
    'Public Health Fundamentals': {
      understand: {
        theory: `# Public Health Fundamentals\n## What is Public Health?\nPublic health focuses on protecting and improving health at the population level — prevention over treatment, upstream determinants over downstream disease management.\n\n## Epidemiology Key Measures\n**Prevalence**: Proportion of population with condition AT a point in time\n**Incidence**: New cases in a period / Population at risk\n**Mortality rate**: Deaths / Population × 1,000 (or 100,000)\n**Case Fatality Rate (CFR)**: Deaths / Confirmed cases × 100\n\n## Disease Causation Models\n**Epidemiological Triad**: Host × Agent × Environment = Disease\n**Web of Causation** (MacMahon): Multiple interacting factors\n**Social Determinants**: Income, education, housing, access — 80% of health outcomes\n\n## Prevention Levels\n- **Primary**: Prevent disease onset (vaccines, health promotion, lifestyle)\n- **Secondary**: Early detection (screening, early treatment) — catch before symptomatic\n- **Tertiary**: Reduce disability/complications in those with established disease\n\n## India's National Health Programmes\n- RNTCP/NTEP: Tuberculosis elimination (India has 26% of global TB burden)\n- NPCDCS: Non-communicable disease control\n- NHM (National Health Mission): Rural and urban healthcare access`,
        examples: [{ title: 'Outbreak investigation (Epidemiological method)', language: 'text', code: `OUTBREAK INVESTIGATION — STEPS (CDC framework):\n\n1. ESTABLISH EXISTENCE: Is this more than expected? → Epidemic threshold\n2. CONFIRM DIAGNOSIS: Clinical, lab confirmation\n3. DEFINE CASE: Case definition (clinical + lab + time + place)\n4. FIND CASES: Active surveillance, contact tracing\n5. CHARACTERISE: Epidemiological curve (Epi curve)\n   → Point source (common vehicle) vs. Propagated (person-to-person)\n6. IDENTIFY SOURCE/RISK FACTORS: Attack rates, relative risk\n7. CONTROL MEASURES: Specific to source identified\n8. REPORT AND COMMUNICATE\n\nINDIA EXAMPLE — COVID-19 2020:\n• Epi curve: Initially point source (Wuhan returnees)\n• Shifted to propagated (community transmission)\n• Response: Case isolation, contact tracing, lockdown, vaccination`, explanation: 'Epi curve shape reveals transmission pattern: narrow = point source (contaminated food/water); extended = person-to-person propagation.' }],
        keyPoints: ['Social determinants of health (income, education, sanitation) explain more variation in health outcomes than clinical interventions', 'India\'s double burden: infectious diseases (TB, malaria, typhoid) + rising NCDs (diabetes, CVD, cancer) — both require different public health strategies', 'Herd immunity threshold = 1 − (1/R0). For measles (R0=15), 93%+ vaccination coverage needed for herd protection']
      },
      evaluate: { questions: [{ question: 'The difference between incidence and prevalence:', options: ['No difference', 'Incidence = new cases; Prevalence = total existing cases (old + new) at a point in time', 'Incidence counts only deaths; prevalence counts living cases', 'Prevalence is used only for infectious diseases'], correctIndex: 1, explanation: 'Incidence = new cases per unit time. Prevalence = all existing cases (captures disease burden at one moment). Chronic diseases have high prevalence; short illnesses show more in incidence.' }, { question: 'Primary prevention aims to:', options: ['Detect disease early before symptoms', 'Prevent the disease from occurring in the first place (vaccines, lifestyle, risk factor reduction)', 'Reduce disability in people who have the disease', 'Treat complications'], correctIndex: 1, explanation: 'Primary prevention acts before disease onset — vaccines, health education, clean water. Secondary = screening for early disease. Tertiary = managing established disease.' }, { question: 'Social determinants of health are important because:', options: ['Doctors cannot treat social problems', 'They explain up to 80% of health outcomes — poverty, education, and housing determine health more than clinical care access', 'They are outside the scope of public health', 'Only genetic factors determine health'], correctIndex: 1, explanation: 'Social determinants (income, education, housing, food security) are the upstream causes of disease. Addressing them is more cost-effective than downstream treatment.' }] }
    },
    'Healthcare Administration': {
      understand: {
        theory: `# Healthcare Administration\n## Healthcare System Structure (India)\n**Tier 1**: Sub-centres (1 per 3,000-5,000 population) — first contact, outreach\n**Tier 2**: PHC (Primary Health Centres) — outpatient, MCH, immunisation\n**Tier 3**: CHC (Community Health Centres) — 30 beds, specialist services\n**Tier 4**: District Hospitals — referral, surgery, specialist care\n**Tier 5**: Medical College Hospitals — tertiary, teaching\n\n## Hospital Administration Key Functions\n- **Medical Staff Management**: Credentialing, privileging, quality review\n- **Operations**: Scheduling, bed management, OT utilisation, supply chain\n- **Finance**: Revenue cycle management, insurance (TPA), cost control\n- **Quality**: NABH accreditation, clinical audits, infection control\n- **HR**: Nurse-to-patient ratios, doctor recruitment, training\n\n## Healthcare Financing (India)\n- **Out-of-pocket**: 58% of health expenditure — among highest globally\n- **Government**: Ayushman Bharat (PMJAY): covers 10.74 Crore poor families up to ₹5L/year\n- **Private Insurance**: Mediclaim, corporate group health insurance\n- **CSR**: Corporate social responsibility health programs`,
        examples: [{ title: 'Hospital operational efficiency metrics', language: 'text', code: `HOSPITAL PERFORMANCE METRICS:\n\nBed Occupancy Rate (BOR):\nFormula: (Patient Days / Available Bed Days) × 100\nBenchmark: 75-85% is ideal\n<60% → underutilisation; >90% → overcrowding, quality risk\n\nAverage Length of Stay (ALOS):\nFormula: Total Patient Days / Total Admissions\nBenchmark varies by case mix; shorter ALOS = efficiency\n\nOperating Theatre Utilisation:\nTarget: >80% prime time usage\nImprovement: Reduce first-case delays, minimise turnover time\n\nPatient Satisfaction (KLAS/NABH scores):\n• Linked to outcomes, readmission rates\n• NABH (National Accreditation Board for Hospitals): Indian quality standard\n\nRevenue Cycle:\nBilling error rate target: <2%\nDenial rate target: <5%\nCash collection within 30 days of discharge`, explanation: 'Hospital KPIs balance quality, efficiency, and financial sustainability. High BOR without quality metrics is dangerous.' }],
        keyPoints: ['NABH accreditation is the Indian hospital quality standard — required for empanelment under Ayushman Bharat and many insurance schemes', 'India\'s high out-of-pocket health expenditure (58%) is a major cause of medical poverty — social health insurance (PMJAY) aims to address this', 'Average Length of Stay (ALOS) is both a quality and efficiency metric — longer stays increase infection risk and costs']
      },
      evaluate: { questions: [{ question: 'Ayushman Bharat (PMJAY) provides healthcare coverage to:', options: ['All Indian citizens equally', 'Top 10.74 Crore poor and vulnerable families — up to ₹5 Lakh per year for secondary and tertiary hospitalisation', 'Only government employees', 'Senior citizens above 65 only'], correctIndex: 1, explanation: 'PMJAY (Pradhan Mantri Jan Arogya Yojana) is the world\'s largest government health insurance scheme — targeting the bottom 40% economically vulnerable families.' }, { question: 'Ideal hospital Bed Occupancy Rate (BOR) is approximately:', options: ['40-50%', '55-65%', '75-85%', '95-100%'], correctIndex: 2, explanation: 'BOR of 75-85% balances utilisation and quality. Below 60% = financial strain; above 90% = staff overload, infection risk, quality decline.' }, { question: 'NABH accreditation for hospitals in India covers:', options: ['Only financial auditing', 'Patient safety, quality of clinical care, infrastructure, and management processes', 'Government hospital pricing only', 'Medical education standards'], correctIndex: 1, explanation: 'NABH (QCI) certification covers all domains: patient rights, clinical care, infection control, staff competence, leadership, and quality improvement processes.' }] }
    },
  },
};

export const DESIGN_CONTENT: Record<string, Record<string, any>> = {
  'UI/UX Design': {
    'Design Thinking Process': {
      understand: {
        theory: `# Design Thinking Process in UI/UX\nDesign Thinking applied to digital product design focuses on understanding users deeply before defining problems, then iterating through solutions rapidly.\n\n## Double Diamond Model\n**Diamond 1 — Discover + Define** (Problem finding)\n- Discover: User research (interviews, surveys, observations, analytics)\n- Define: Synthesise findings → Problem statement, User Personas, Journey Maps\n\n**Diamond 2 — Develop + Deliver** (Solution finding)\n- Develop: Ideation (crazy 8s, design studio), wireframes, prototypes\n- Deliver: Usability testing, iteration, handoff\n\n## Key Research Methods\n| Method | What It Reveals | When |\n|--------|-----------------|------|\n| User interviews | Motivations, mental models | Discovery |\n| Surveys | Quantitative validation | Discovery |\n| Usability testing | Task completion issues | Evaluate |\n| Card sorting | IA/navigation structure | Define |\n| A/B testing | Which design performs better | Post-launch |\n\n## Problem Statement (How Might We)\n"[USER SEGMENT] needs a way to [VERB/NEED] because [INSIGHT]"\n"How might we help [USER SEGMENT] [ACHIEVE GOAL] so that [BENEFIT]?"`,
        examples: [{ title: 'User interview insights → Persona', language: 'text', code: `USER RESEARCH FINDINGS (5 interviews, app redesign):\n• "I always get lost in the settings menu"\n• "I just want the simplest way to do X quickly"\n• "Notifications are overwhelming, I ignore most"\n• "I only use 3-4 features regularly"\n\nSYNTHESIS → PERSONA:\nName: "Priya, The Practical Professional"\nAge: 28 | Product Manager | Mumbai\nBehavior: Uses app during commute, 5-minute sessions\nGoals: Complete key tasks fast without friction\nFrustrations: Complex navigation, notification overload\nNeeds: Simplified navigation, customisable notifications,\n        quick-access shortcuts for frequent tasks\n\nDESIGN IMPLICATIONS:\n• Tab bar with 4-5 most-used features only\n• Batch notification controls\n• Saved shortcuts / home screen customisation`, explanation: 'Personas translate qualitative insights into a vivid user representation that the team can design for. Must be grounded in real research, not assumptions.' }],
        keyPoints: ['Never skip user research — designing based on assumptions creates products that look good but don\'t solve real problems', 'Usability testing with 5 users reveals ~85% of critical usability issues — more users add diminishing returns (Nielsen)', 'HOW MIGHT WE (HMW) questions reframe problems as design opportunities — use them at the transition from Define to Develop']
      },
      evaluate: { questions: [{ question: 'Usability testing with 5 users reveals approximately:', options: ['20% of issues', '50% of issues', '85% of critical usability issues', '100% of issues'], correctIndex: 2, explanation: 'Nielsen\'s research: 5 users expose ~85% of usability problems. Additional users yield diminishing returns. Run multiple rounds of 5 instead of one round of 20.' }, { question: 'Card sorting in UX research is primarily used to:', options: ['Test colour preferences', 'Understand how users categorise information — informs information architecture and navigation', 'Compare two design variants', 'Measure user satisfaction'], correctIndex: 1, explanation: 'Card sorting asks users to group content cards into categories that make sense to them — reveals their mental model for navigation structure.' }, { question: 'The Double Diamond model has how many phases?', options: ['2', '3', '4', '6'], correctIndex: 2, explanation: 'Double Diamond: Discover (research) → Define (synthesise) → Develop (ideate/prototype) → Deliver (test/launch). Two diamonds = two diverge-converge cycles.' }] }
    },
    'Visual Hierarchy & Typography': {
      understand: {
        theory: `# Visual Hierarchy & Typography\nVisual hierarchy guides the eye through content in order of importance. Typography — the art of arranging type — is the primary visual hierarchy tool.\n\n## Visual Hierarchy Principles\n1. **Size**: Larger = more important\n2. **Colour/Contrast**: High contrast draws attention first\n3. **Weight**: Bold text draws more attention than regular\n4. **Position**: Top-left is most read (F-pattern, Z-pattern)\n5. **Whitespace**: Isolated elements gain importance\n6. **Grouping** (Gestalt): Proximity, similarity, continuity\n\n## Type Scale (Modular Scale)\nA harmonious type scale uses a mathematical ratio:\n- 1.25× (Major third): 16px base → 20, 25, 31, 39px\n- 1.5× (Perfect fifth): 16px → 24, 36, 54px\n- Common UI scale: 12, 14, 16, 18, 20, 24, 30, 36, 48px\n\n## Typography Rules\n- **Line length**: 45-75 characters per line (optimal for reading)\n- **Line height**: 1.4-1.6 for body text; 1.0-1.2 for headings\n- **Contrast ratio**: AA standard = 4.5:1 (normal text); AAA = 7:1\n- **Font pairing**: Combine serif + sans-serif; limit 2-3 typefaces`,
        examples: [{ title: 'F-pattern reading behaviour', language: 'text', code: `F-PATTERN EYE-TRACKING FINDINGS (Nielsen Norman Group):\n\nUsers read in an F-shape:\nTop horizontal strip → secondary horizontal → Left vertical\n\n┌──────────────────────────┐\n│ ██████████████████       │  ← Most read (H1, key benefit)\n│ █████████                │  ← Second read (subheading)\n│ █                        │\n│ █                        │\n│ █                        │\n│ █                        │\n└──────────────────────────┘\n\nDESIGN IMPLICATIONS:\n• Put most important content at the TOP\n• Use bold headings to create entry points\n• Don't bury key actions below the fold\n• Front-load sentences (key info first)\n• Lists > paragraphs for scanning\n\nNOTE: Z-pattern applies to sparse layouts\n(landing pages, hero sections)`, explanation: 'Most users scan, not read. Design for scanning: short paragraphs, bold keywords, left-aligned text, clear visual hierarchy.' }],
        keyPoints: ['45-75 characters per line (about 65 optimal) — too long tires the eye; too short creates choppy rhythm', 'WCAG contrast ratio 4.5:1 minimum for normal text — critical for accessibility; check with tools like Colour Contrast Analyser', 'Whitespace (negative space) is not empty — it creates focus, reduces cognitive load, and increases readability (luxury brands use it deliberately)']
      },
      evaluate: { questions: [{ question: 'The optimal line length for body text is:', options: ['15-30 characters', '45-75 characters per line', '100-120 characters', 'No standard exists'], correctIndex: 1, explanation: '45-75 characters per line balances readability and scanning speed. Too long causes eye tracking errors; too short disrupts reading flow.' }, { question: 'WCAG AA contrast ratio requirement for normal text is:', options: ['2:1', '3:1', '4.5:1', '7:1'], correctIndex: 2, explanation: 'WCAG 2.1 Level AA: 4.5:1 contrast ratio for text smaller than 18pt (14pt bold). Level AAA requires 7:1 — used for maximum accessibility.' }, { question: 'In visual hierarchy, which creates the strongest attention pull?', options: ['Colour alone', 'The combination of size + high contrast + position (top-left)', 'Italic text', 'Underlined text'], correctIndex: 1, explanation: 'Visual hierarchy is cumulative. Size matters most, but combining size + contrast + prime position (top-left from F-pattern) creates the strongest visual weight.' }] }
    },
    'Wireframing & Prototyping': {
      understand: {
        theory: `# Wireframing & Prototyping\nWireframes define structure; prototypes demonstrate behaviour. Both serve different purposes in the design process.\n\n## Fidelity Levels\n**Low-fidelity (Lo-Fi)**:\n- Sketches, paper wireframes\n- Purpose: Rapid ideation, structural decisions\n- Tools: Paper, Balsamiq\n- When: Early divergent phase\n\n**Medium-fidelity**:\n- Greyscale wireframes\n- Purpose: Layout, flow, information hierarchy\n- Tools: Figma wireframe mode, FigJam\n- When: Define/Develop phase\n\n**High-fidelity (Hi-Fi)**:\n- Pixel-perfect mockups + interactive prototype\n- Purpose: Usability testing, stakeholder approval, developer handoff\n- Tools: Figma, Framer, Adobe XD\n\n## Prototyping Techniques\n- **Click-through**: Static screens linked — good for flow testing\n- **Interaction prototype**: Microinteractions, transitions — test UX feel\n- **Wizard of Oz**: Human simulates AI/complex behaviour behind the scenes\n- **Concierge MVP**: Real human delivers service manually to validate idea before building`,
        examples: [{ title: 'Figma component system', language: 'text', code: `COMPONENT ARCHITECTURE IN FIGMA:\n\nATOMIC DESIGN HIERARCHY:\nAtoms: Button, Input, Icon, Label, Badge\nMolecules: Form field (Label + Input + Error), Card header (Avatar + Name + Role)\nOrganisms: Navigation bar, Product card, Modal\nTemplates: Dashboard layout, Course detail page\nPages: Full hi-fi screen designs\n\nCOMPONENT BEST PRACTICES:\n• Use Auto Layout for responsive behaviour\n• Define variants: size (sm/md/lg), state (default/hover/active/disabled)\n• Establish a 4px or 8px grid system\n• Create a Colour Styles system: Primary/Secondary/Neutral/Semantic\n• Text Styles: H1-H6, Body-L/M/S, Caption, Label\n\nHANDOFF:\n• Inspect panel shows CSS properties to devs\n• Comment mode for feedback\n• Figma Dev Mode: Direct CSS/React code snippets`, explanation: 'Atomic Design creates a scalable, consistent design system. Every screen is built from reusable components — changes propagate automatically.' }],
        keyPoints: ['Test lo-fi prototypes with users early — paper prototypes reveal 80% of usability issues at zero cost before any Figma work', 'Component libraries in Figma accelerate design by 10× — build once, use everywhere, update globally', 'Developer handoff quality directly impacts build quality — use Auto Layout, consistent naming, and inspect mode rather than emailing PNGs']
      },
      evaluate: { questions: [{ question: 'The primary purpose of low-fidelity wireframes is:', options: ['Final developer handoff', 'Pixel-perfect design approval', 'Rapid ideation and structural decision-making — before investing in high-fidelity', 'SEO optimisation'], correctIndex: 2, explanation: 'Lo-fi wireframes are fast, cheap to change, and focus on structure and flow — not aesthetics. Change paper sketches in seconds vs. hours in Figma.' }, { question: 'A Wizard of Oz prototype technique involves:', options: ['Automated AI responses', 'A human behind the scenes simulating the system\'s intelligent behaviour while users think it is automated', 'Testing with fake users', 'Creating a working code prototype'], correctIndex: 1, explanation: 'Wizard of Oz lets you test AI/complex features before building them. A human manually provides responses while the user interacts with the interface as if it were real.' }, { question: 'Atomic Design\'s "Molecules" are composed of:', options: ['Individual, basic UI elements', 'Combining atoms into simple, functional UI components (e.g., a form field = label + input + error)', 'Full page layouts', 'Large UI sections with multiple interactions'], correctIndex: 1, explanation: 'Molecules are groups of atoms functioning together. A form field (label + input + help text) is a molecule — more complex than an atom, but still a reusable unit.' }] }
    },
    'User Research Methods': {
      understand: {
        theory: `# User Research Methods\nUser research grounds design in reality. Generative research discovers problems; evaluative research tests solutions.\n\n## Research Methods by Type\n\n### Qualitative (Why/How)\n- **In-depth interviews**: 30-60 min; semi-structured; uncover motivations\n- **Contextual inquiry**: Observe users in their actual environment\n- **Diary studies**: Users self-report over days/weeks (longitudinal)\n- **Focus groups**: 6-8 users; explore attitudes, reactions (avoid for usability)\n\n### Quantitative (How many/much)\n- **Surveys**: Scale to hundreds/thousands; validate qualitative findings\n- **Analytics**: Google Analytics, Mixpanel — actual behaviour data\n- **A/B tests**: Controlled experiment on live users\n- **Eye tracking**: Precise attention maps (expensive)\n\n## Research Planning — JTBD (Jobs To Be Done)\n"When [SITUATION], I want to [MOTIVATION], so I can [EXPECTED OUTCOME]"\nExample: "When I'm looking for a job, I want to practice interview skills, so I can feel confident in real interviews"\n\n## Affinity Mapping\nSynthesize 50-100 qualitative insights by clustering similar observations into themes → reveals patterns no single interview shows`,
        examples: [{ title: 'Survey design — avoiding bias', language: 'text', code: `SURVEY QUESTION BIASES TO AVOID:\n\n1. LEADING QUESTION:\n   BAD:  "How much do you enjoy our amazing new feature?"\n   GOOD: "How would you rate your experience with this feature?"\n\n2. DOUBLE-BARRELLED:\n   BAD:  "Was the design clear and easy to use?"\n   GOOD: Ask separately: "Was the design visually clear?"\n         Then: "Was it easy to complete your task?"\n\n3. RECALL BIAS:\n   BAD:  "How often did you use the app last year?"\n   GOOD: "How often do you typically use the app in a week?"\n\n4. SOCIAL DESIRABILITY:\n   BAD:  "Do you read all notifications carefully?"\n   GOOD: Observe behaviour in analytics instead\n\n5. SCALE CONSISTENCY:\n   BAD:  Mixing 5-point and 7-point scales in same survey\n   GOOD: Use NPS (0-10) or Likert (1-5) consistently`, explanation: 'Survey bias leads to data that confirms your assumptions rather than revealing reality. Each question should have one clear, unambiguous interpretation.' }],
        keyPoints: ['Qualitative research (interviews, observations) answers WHY; quantitative (analytics, surveys) answers WHAT and HOW MANY — both are needed', 'Never use focus groups to evaluate usability — groupthink and social pressure distort individual responses. Use 1-on-1 usability testing instead', 'Jobs To Be Done reframes user needs as goals (desired outcomes) not features — prevents designing features for the wrong reasons']
      },
      evaluate: { questions: [{ question: 'Contextual inquiry is valuable because:', options: ['It is the cheapest research method', 'It observes users in their actual work environment — captures real behaviour vs. what users say they do', 'It works best for quantitative data', 'It requires no planning'], correctIndex: 1, explanation: 'What users say they do (interviews) ≠ what they actually do (observation). Contextual inquiry captures real workflows, workarounds, and pain points.' }, { question: 'Affinity mapping is used to:', options: ['Design the navigation structure', 'Synthesise large amounts of qualitative data by clustering insights into themes', 'Compare competitor products', 'Create user personas only'], correctIndex: 1, explanation: 'Affinity mapping (also "affinity diagramming") groups dozens/hundreds of raw observations into emergent themes — makes qualitative data actionable.' }, { question: 'Jobs To Be Done (JTBD) framework focuses on:', options: ['Feature lists', 'User demographics and personas', 'The outcome/goal users are trying to achieve in a given context — independent of product features', 'Technology constraints'], correctIndex: 2, explanation: 'JTBD: people "hire" products to do a job. Understanding the job (desired outcome) reveals what features actually matter vs. what teams think matters.' }] }
    },
    'Accessibility & Inclusive Design': {
      understand: {
        theory: `# Accessibility & Inclusive Design\n## Why Accessibility Matters\n- 15% of the world's population (1.3 billion) has some form of disability\n- In India: Persons with Disabilities Act 2016 requires digital accessibility\n- Accessible design benefits everyone: captions help in noisy environments; high contrast helps in sunlight\n\n## WCAG 2.1 — 4 Principles (POUR)\n1. **Perceivable**: Information must be presentable in ways users can perceive\n   - Alt text for images, captions for video, sufficient colour contrast\n2. **Operable**: UI must be navigable and usable\n   - Keyboard navigation, skip navigation, no seizure-inducing flashing\n3. **Understandable**: Content and UI must be understandable\n   - Plain language, consistent navigation, clear error messages\n4. **Robust**: Content must be interpretable by assistive technologies\n   - Valid semantic HTML, ARIA labels\n\n## Common Accessibility Issues\n- Images without alt text (screen reader users can't understand)\n- Colour alone to convey information (colourblind users miss it)\n- No keyboard navigation support\n- Low contrast text (legibility for visually impaired)\n- Auto-playing audio/video without controls\n- Form errors only described by colour`,
        examples: [{ title: 'Accessible form design', language: 'text', code: `INACCESSIBLE (BAD):\n<input type="email" placeholder="Email" />\n<span style="color:red">Required</span>\n\nISSUES:\n• No label element — screen reader reads only "Edit text"\n• Error shown only in red — colourblind users miss it\n• Placeholder disappears when typing — users forget what field is for\n\nACCESSIBLE (GOOD):\n<label for="email">Email address *</label>\n<input type="email" id="email" aria-describedby="email-error"\n       aria-required="true" />\n<span id="email-error" role="alert">\n  ⚠️ Email is required — please enter a valid email address\n</span>\n\nFIXES:\n✓ Explicit <label> element (screen reader reads it)\n✓ aria-describedby links input to error\n✓ role="alert" announces error when it appears\n✓ Error has text AND icon (not just colour)\n✓ aria-required for screen readers`, explanation: 'Accessible forms are also clearer for all users. Good labels, error messages, and semantic HTML benefit everyone — not just disabled users.' }],
        keyPoints: ['Semantic HTML is the foundation of accessibility — use <button>, <nav>, <main>, <header> instead of <div> for everything', 'Keyboard navigability test: can you use the entire site using only Tab, Enter, Space, and Arrow keys? If not, keyboard users and screen reader users are excluded', 'Legal risk: India\'s PwD Act + WCAG compliance required for government sites and increasingly expected for private digital products']
      },
      evaluate: { questions: [{ question: 'WCAG stands for:', options: ['Web Content Accessibility Guidelines', 'Website Colour and Graphics Compliance', 'Web Coding and Graphic Conventions', 'Worldwide Content Accessibility Grading'], correctIndex: 0, explanation: 'WCAG (Web Content Accessibility Guidelines) is the international standard for web accessibility, published by the W3C. Current version: WCAG 2.1 (2.2 released 2023).' }, { question: 'Alt text for images is important because:', options: ['It improves Google image search SEO only', 'Screen readers read alt text to blind users who cannot see the image', 'It speeds up page loading', 'It is required by law in all countries'], correctIndex: 1, explanation: 'Alt text provides a textual description of images for screen reader users who are blind or visually impaired. Also useful when images fail to load.' }, { question: 'The minimum WCAG AA colour contrast ratio for normal text is:', options: ['2:1', '3:1', '4.5:1', '7:1'], correctIndex: 2, explanation: 'WCAG 2.1 Level AA requires 4.5:1 contrast for text under 18pt normal or 14pt bold. Use tools like WebAIM Contrast Checker to verify.' }] }
    },
    'Design Systems & Figma': {
      understand: {
        theory: `# Design Systems & Figma\n## What is a Design System?\nA design system is a collection of reusable components, guidelines, and standards that enable consistent, efficient product design and development.\n\n## Components of a Design System\n1. **Design Tokens**: Fundamental values (colours, spacing, typography, shadows)\n   Example: \`--color-primary-500: #2563EB;\`\n2. **Component Library**: Buttons, inputs, cards, modals — documented and coded\n3. **Usage Guidelines**: When and how to use each component\n4. **Voice & Tone**: Writing style\n5. **Icon System**: Consistent icon set (Heroicons, Phosphor, custom)\n6. **Grid & Layout**: 12-column grid, breakpoints (360px, 768px, 1024px, 1280px)\n\n## Figma Essentials\n- **Components**: Reusable instances; edit master → all instances update\n- **Auto Layout**: Responsive frames that grow/shrink; equivalent to CSS Flexbox\n- **Variants**: Multiple states/sizes of one component in a single master\n- **Design Tokens**: Via Figma Tokens plugin → sync to codebase\n- **Prototyping**: Link frames → click-through interactions\n- **Dev Mode**: Converts designs to CSS/React code for developers`,
        examples: [{ title: 'Colour token system', language: 'text', code: `DESIGN TOKEN SYSTEM:\n\nPRIMITIVE TOKENS (raw values):\nbrand-blue-100: #DBEAFE\nbrand-blue-500: #2563EB\nbrand-blue-900: #1E3A5F\n\nSEMANTIC TOKENS (purpose-based):\ncolor-action-primary:      brand-blue-500    → buttons, links\ncolor-action-hover:        brand-blue-700    → hover states\ncolor-background-subtle:   brand-blue-50     → section backgrounds\ncolor-text-on-primary:     white             → text on blue buttons\n\nSTATUS TOKENS:\ncolor-status-success:      green-500\ncolor-status-warning:      amber-500\ncolor-status-error:        red-500\ncolor-status-info:         blue-400\n\nBENEFIT:\n• Change brand-blue-500 → EVERYTHING updates at once\n• Semantic naming makes intent clear to devs\n• Dark mode: swap semantic tokens to different primitives`, explanation: 'Two-layer token system (primitive → semantic) enables global theme changes in one edit. This is how Figma Tokens plugin syncs to Tailwind/CSS variables.' }],
        keyPoints: ['Design tokens are the bridge between design and code — they eliminate "design says #2563EB, dev uses #2464EC" discrepancies', 'Auto Layout in Figma = CSS Flexbox — components built with Auto Layout behave responsively like real code', 'Consistent naming conventions in Figma (using /Category/Component/Variant notation) enable easy search and automation']
      },
      evaluate: { questions: [{ question: 'Design tokens in a design system are:', options: ['Icons and images', 'The fundamental design values (colours, spacing, typography) that components are built from', 'Documentation files', 'Figma plugins only'], correctIndex: 1, explanation: 'Design tokens are the primitive values of a design system — colour values, spacing scales, font sizes. They enable consistent, themeable, cross-platform design.' }, { question: 'Auto Layout in Figma behaves similarly to:', options: ['CSS Grid', 'CSS Flexbox — elements stack/space/wrap automatically based on rules', 'HTML tables', 'CSS position: absolute'], correctIndex: 1, explanation: 'Auto Layout is Figma\'s implementation of Flexbox concepts — direction, gap, padding, alignment. Components built with Auto Layout are responsive by default.' }, { question: 'Why is a component library valuable in a design system?', options: ['It reduces the need for user research', 'All team members design with the same components — ensuring consistency and enabling global updates from the master', 'It speeds up only developer work', 'It replaces the need for prototypes'], correctIndex: 1, explanation: 'Component libraries ensure all designers use identical UI elements. Update the master component once → every screen using it updates automatically.' }] }
    },
  },
};
