export const TECHNOLOGY_CONTENT: Record<string, Record<string, any>> = {
  'Python for Automation & AI': {
    'Python Basics & Syntax': {
      understand: {
        theory: `# Python Basics & Syntax\nPython uses **indentation** (4 spaces) for code blocks — no braces. Variables are dynamically typed; no declarations needed. Python reads top-to-bottom, executing each statement.\n\n### Core Data Types\n\`\`\`python\nname = "Alice"        # str\ncount = 42            # int\nrate  = 3.14          # float\nactive = True         # bool\nitems = [1, 2, 3]     # list  (mutable)\npoint = (1, 2)        # tuple (immutable)\ninfo  = {"k": "v"}   # dict  (mutable)\n\`\`\`\n\n### Control Flow\n\`\`\`python\nif x > 0:\n    print("positive")\nelif x == 0:\n    print("zero")\nelse:\n    print("negative")\n\nfor item in items:\n    process(item)\n\nwhile queue:\n    queue.pop()\n\`\`\``,
        examples: [{ title: 'FizzBuzz — loops & conditionals', language: 'python', code: `for i in range(1, 21):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`, explanation: '% is modulo. range(1, 21) generates 1 through 20. if/elif/else chains handle multiple conditions.' }],
        keyPoints: ['Indentation (4 spaces) is mandatory — mixing tabs and spaces causes SyntaxError', 'Lists [] are mutable; tuples () are immutable; dicts {} map keys to values', 'f"Hello {name}" is the modern, fast way to format strings in Python 3.6+']
      },
      evaluate: { questions: [{ question: 'What defines code blocks in Python?', options: ['Curly braces {}', 'Semicolons ;', 'Indentation', 'BEGIN/END keywords'], correctIndex: 2, explanation: 'Python uses 4-space indentation — not braces or keywords.' }, { question: 'Which data type is mutable?', options: ['str', 'tuple', 'int', 'list'], correctIndex: 3, explanation: 'Lists can be modified. Strings, tuples, and numbers are all immutable.' }, { question: 'What does range(4) produce?', options: ['[1,2,3,4]', '[0,1,2,3]', '[0,1,2,3,4]', 'Error'], correctIndex: 1, explanation: 'range(n) → 0 to n-1. range(4) → 0, 1, 2, 3.' }] }
    },
    'Functions & Modules': {
      understand: {
        theory: `# Functions & Modules\nFunctions are reusable blocks defined with \`def\`. Python supports default args, *args (extra positionals as tuple), and **kwargs (extra keywords as dict). Modules are .py files; packages are folders with __init__.py.\n\n\`\`\`python\ndef greet(name, greeting="Hello"):\n    return f"{greeting}, {name}!"\n\ndef total(*nums):          # variable positional\n    return sum(nums)\n\ndef show(**info):          # variable keyword\n    return info\n\nadd = lambda x, y: x + y  # anonymous function\n\nimport os\nfrom pathlib import Path\nimport numpy as np         # aliased import\n\`\`\``,
        examples: [{ title: '*args and **kwargs in action', language: 'python', code: `def report(title, *sections, author="Unknown", **meta):\n    print(f"[{title}] by {author}")\n    for s in sections: print(" -", s)\n    print("Meta:", meta)\n\nreport("Q1", "Revenue", "Costs", author="Alice", year=2026)`, explanation: '*sections collects extra positionals into a tuple. **meta collects keyword args into a dict.' }],
        keyPoints: ['Default parameters must follow required ones: def f(a, b=10) — not def f(b=10, a)', '*args → tuple of extra positionals; **kwargs → dict of extra keywords', 'from module import name brings name into current scope without the module prefix']
      },
      evaluate: { questions: [{ question: 'In def f(a, b=5, *args), what does *args collect?', options: ['All arguments', 'Extra positional args beyond a and b', 'Extra keyword args', 'Default value overrides'], correctIndex: 1, explanation: '*args captures any extra positional arguments after the named ones.' }, { question: 'What does lambda x: x**2 create?', options: ['A class', 'A module', 'An anonymous function squaring x', 'A generator'], correctIndex: 2, explanation: 'lambda creates a small anonymous function. lambda x: x**2 returns x squared.' }, { question: 'from math import sqrt — what can you now call?', options: ['math.sqrt()', 'sqrt()', 'math(sqrt)', 'import.sqrt()'], correctIndex: 1, explanation: 'from X import Y puts Y into the current namespace — use sqrt() directly.' }] }
    },
    'File & OS Automation': {
      understand: {
        theory: `# File & OS Automation\nPython's built-in \`open()\` reads and writes files. Always use \`with open()\` — it automatically closes the file even on error. The \`os\` and \`pathlib\` modules handle filesystem operations portably across OS.\n\n\`\`\`python\nfrom pathlib import Path\nimport os, shutil\n\n# Read a file\nwith open("data.txt", "r") as f:\n    content = f.read()          # whole file\n    lines = f.readlines()       # list of lines\n\n# Write a file\nwith open("out.txt", "w") as f:\n    f.write("Hello\\n")\n\n# Pathlib (modern)\np = Path("reports") / "q1.csv"\np.parent.mkdir(parents=True, exist_ok=True)\n\n# OS operations\nos.rename("old.txt", "new.txt")\nshutil.copy("src.txt", "dst/")   # copy file\nshutil.rmtree("tmp/")            # delete folder\n\`\`\``,
        examples: [{ title: 'Batch rename all .txt files', language: 'python', code: `from pathlib import Path\n\nfolder = Path("documents")\nfor i, f in enumerate(folder.glob("*.txt"), start=1):\n    f.rename(f.parent / f"doc_{i:03d}.txt")\n    print(f"Renamed: {f.name}")`, explanation: 'Path.glob("*.txt") finds all .txt files. f:03d pads the number to 3 digits (001, 002...).' }],
        keyPoints: ['Always use "with open()" — it guarantees the file closes even if an exception occurs', 'Modes: r=read, w=write(overwrites), a=append, rb/wb=binary. Default is text mode.', 'pathlib.Path is the modern OS-agnostic way to build paths: Path("a") / "b" / "c.txt"']
      },
      evaluate: { questions: [{ question: 'Why use "with open(file) as f:" instead of open()?', options: ['It is faster', 'It automatically closes the file', 'It supports binary mode only', 'It creates the file if missing'], correctIndex: 1, explanation: 'The "with" context manager calls f.close() automatically even if an exception is raised.' }, { question: 'Which mode overwrites an existing file?', options: ['"r"', '"a"', '"w"', '"rb"'], correctIndex: 2, explanation: '"w" opens for writing and truncates (empties) the file first. "a" appends without clearing.' }, { question: 'Path("reports") / "2026" / "q1.csv" — what does / do here?', options: ['Division', 'String concatenation', 'Path joining operator', 'Directory creation'], correctIndex: 2, explanation: 'pathlib overloads / as a path join operator, producing Path("reports/2026/q1.csv").' }] }
    },
    'Web Scraping (BeautifulSoup)': {
      understand: {
        theory: `# Web Scraping with BeautifulSoup\n\`requests\` fetches web pages; \`BeautifulSoup\` parses HTML and extracts data. Use CSS selectors or tag-based search to target elements.\n\n\`\`\`python\nimport requests\nfrom bs4 import BeautifulSoup\n\nres = requests.get("https://example.com", headers={"User-Agent": "Mozilla/5.0"})\nres.raise_for_status()  # raise exception on 4xx/5xx\n\nsoup = BeautifulSoup(res.text, "lxml")\n\n# Find methods\ntitle = soup.find("h1").text              # first h1\nlinks = soup.find_all("a", class_="nav") # all nav links\nprice = soup.select_one(".product-price") # CSS selector\nrows  = soup.select("table tr")          # all table rows\n\n# Extract attributes\nhref = soup.find("a")["href"]\n\`\`\`\n\n> ⚠️ Always check the site's robots.txt and ToS before scraping.`,
        examples: [{ title: 'Scrape article headlines from a news page', language: 'python', code: `import requests\nfrom bs4 import BeautifulSoup\n\nurl = "https://news.ycombinator.com"\nres = requests.get(url)\nsoup = BeautifulSoup(res.text, "lxml")\n\nheadlines = soup.select(".titleline > a")\nfor h in headlines[:10]:\n    print(h.text, "→", h.get("href", "N/A"))`, explanation: 'CSS selector ".titleline > a" targets anchor tags that are direct children of .titleline elements.' }],
        keyPoints: ['requests.get() returns a Response; call .raise_for_status() to surface HTTP errors', 'soup.find() returns first match; soup.find_all() returns a list; soup.select() uses CSS selectors', 'Scraping is rate-limited by ethics — add time.sleep(1) between requests and respect robots.txt']
      },
      evaluate: { questions: [{ question: 'Which parser should you use with BeautifulSoup for speed?', options: ['html.parser', 'lxml', 'html5lib', 'xml'], correctIndex: 1, explanation: 'lxml is the fastest HTML parser for BeautifulSoup. Install with: pip install lxml' }, { question: 'soup.find("p", class_="intro") — what does this return?', options: ['All <p class="intro"> tags', 'The first <p class="intro"> tag', 'All paragraphs', 'Error — class is reserved'], correctIndex: 1, explanation: 'find() returns the FIRST matching element. find_all() returns all matches as a list.' }, { question: 'How do you extract an href from <a href="/about">?', options: ['tag.href', 'tag["href"]', 'tag.get_href()', 'tag.attrs.href'], correctIndex: 1, explanation: 'BS4 tags behave like dicts. Access attributes with tag["attr_name"] or tag.get("attr_name").' }] }
    },
    'Data Handling (Pandas)': {
      understand: {
        theory: `# Data Handling with Pandas\nPandas provides **DataFrame** (2D table) and **Series** (1D column). Load data from CSV, Excel, SQL, or JSON. Core operations: filter, sort, groupby, merge, pivot.\n\n\`\`\`python\nimport pandas as pd\n\ndf = pd.read_csv("sales.csv")     # load\ndf.head()                          # first 5 rows\ndf.info()                          # dtypes & nulls\ndf.describe()                      # stats summary\n\n# Filter\nhigh = df[df["revenue"] > 10000]\n\n# New column\ndf["margin"] = df["profit"] / df["revenue"]\n\n# GroupBy\nby_region = df.groupby("region")["revenue"].sum()\n\n# Merge (like SQL JOIN)\nmerged = pd.merge(df, users, on="user_id", how="left")\n\n# Pivot table\npivot = df.pivot_table(values="revenue", index="month",\n                        columns="product", aggfunc="sum")\n\`\`\``,
        examples: [{ title: 'Clean and analyse a sales dataset', language: 'python', code: `df = pd.read_csv("orders.csv", parse_dates=["date"])\ndf.dropna(subset=["customer_id"], inplace=True)\ndf["year"] = df["date"].dt.year\n\ntop = df.groupby("product")["amount"].sum()\\\n         .sort_values(ascending=False).head(5)\nprint(top)`, explanation: 'parse_dates converts the column to datetime. dt.year extracts the year. groupby+sum aggregates revenue per product.' }],
        keyPoints: ['df[condition] filters rows; df.loc[rows, cols] is label-based indexing; df.iloc[rows, cols] is integer-based', 'Always check df.isnull().sum() after loading data to identify missing values', 'groupby().agg() lets you apply multiple aggregation functions at once: {"col": ["sum","mean","count"]}']
      },
      evaluate: { questions: [{ question: 'df[df["age"] > 25] — what does this produce?', options: ['A boolean', 'A filtered DataFrame with rows where age > 25', 'An error', 'A new column'], correctIndex: 1, explanation: 'df["age"] > 25 creates a boolean Series; wrapping it in df[] filters rows where True.' }, { question: 'What does df.groupby("city")["sales"].sum() return?', options: ['A single value', 'Total sales per city as a Series', 'A pivot table', 'A merged DataFrame'], correctIndex: 1, explanation: 'groupby aggregates data by a key column. sum() then totals the sales for each unique city.' }, { question: 'pd.merge(df1, df2, on="id", how="left") — what rows appear?', options: ['Only rows in both', 'All df1 rows + matching df2', 'All rows from both DataFrames', 'All df2 rows + matching df1'], correctIndex: 1, explanation: 'A left join keeps ALL rows from the left DataFrame (df1). Unmatched right rows get NaN.' }] }
    },
    'REST APIs with requests': {
      understand: {
        theory: `# REST APIs with requests\nThe \`requests\` library is the standard for HTTP in Python. REST APIs use HTTP methods (GET, POST, PUT, DELETE) on resource URLs. Responses are typically JSON.\n\n\`\`\`python\nimport requests\n\n# GET with query params\nres = requests.get("https://api.example.com/users",\n                    params={"page": 1, "limit": 20},\n                    headers={"Authorization": "Bearer TOKEN"})\ndata = res.json()          # parse JSON response\nres.raise_for_status()     # throw on 4xx/5xx\n\n# POST with JSON body\nnew_user = {"name": "Alice", "email": "alice@co.com"}\nres = requests.post("https://api.example.com/users",\n                     json=new_user,\n                     headers={"Authorization": "Bearer TOKEN"})\nprint(res.status_code)     # 201 Created\n\n# Session (reuse connection + headers)\nwith requests.Session() as s:\n    s.headers["Authorization"] = "Bearer TOKEN"\n    s.get("https://api.example.com/me")\n\`\`\``,
        examples: [{ title: 'Fetch GitHub repos for a user', language: 'python', code: `import requests\n\ndef get_repos(username):\n    url = f"https://api.github.com/users/{username}/repos"\n    res = requests.get(url, params={"per_page": 5, "sort": "updated"})\n    res.raise_for_status()\n    return [(r["name"], r["stargazers_count"]) for r in res.json()]\n\nfor name, stars in get_repos("torvalds"):\n    print(f"★{stars:4d}  {name}")`, explanation: 'GitHub API is public (no auth needed for public repos). List comprehension extracts name+stars from the JSON list.' }],
        keyPoints: ['Use params= for query strings (auto-encoded); json= for request body (auto-serialized + Content-Type set)', 'Always call res.raise_for_status() after requests to surface API errors as exceptions', 'Use requests.Session() when making multiple calls to the same server — reuses TCP connections']
      },
      evaluate: { questions: [{ question: 'requests.get(url, params={"q": "python"}) — where does the query go?', options: ['Request body', 'Request headers', 'URL query string (?q=python)', 'Cookie'], correctIndex: 2, explanation: 'params= builds the URL query string automatically: url?q=python' }, { question: 'res.raise_for_status() raises an exception when:', options: ['Status is 200', 'Status is 201', 'Status is 4xx or 5xx', 'Response is empty'], correctIndex: 2, explanation: 'raise_for_status() raises HTTPError if the response indicates a client (4xx) or server (5xx) error.' }, { question: 'requests.post(url, json=data) vs requests.post(url, data=str(data))?', options: ['No difference', 'json= auto-serializes dict and sets Content-Type: application/json', 'data= sets Content-Type: application/json', 'json= only works for GET'], correctIndex: 1, explanation: 'json= automatically serializes the dict to JSON and sets the correct Content-Type header.' }] }
    },
    'Scheduling & Cron Jobs': {
      understand: {
        theory: `# Scheduling & Cron Jobs\nThe \`schedule\` library runs Python tasks at intervals within a running script. \`APScheduler\` adds persistence, timezone support, and multiple job stores. For OS-level scheduling, use cron (Linux/Mac) or Task Scheduler (Windows).\n\n\`\`\`python\nimport schedule, time\n\n# schedule library\nschedule.every(10).minutes.do(send_report)\nschedule.every().day.at("09:00").do(fetch_data)\nschedule.every().monday.at("08:00").do(weekly_digest)\n\nwhile True:\n    schedule.run_pending()\n    time.sleep(30)   # check every 30s\n\`\`\`\n\n**Cron syntax (Linux/Mac):**\n\`\`\`\n# min  hr  day  month  weekday  command\n  0    9   *    *      1-5      python /home/jobs/report.py\n\`\`\`\nCron fields: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0=Sun).`,
        examples: [{ title: 'APScheduler with timezone-aware job', language: 'python', code: `from apscheduler.schedulers.blocking import BlockingScheduler\nfrom datetime import datetime\nimport pytz\n\ndef morning_brief():\n    print(f"[{datetime.now()}] Running morning brief")\n\nscheduler = BlockingScheduler(timezone=pytz.timezone("Asia/Kolkata"))\nscheduler.add_job(morning_brief, "cron", hour=8, minute=30)\nscheduler.start()`, explanation: 'APScheduler supports timezone-aware cron expressions. BlockingScheduler runs in the foreground.' }],
        keyPoints: ['schedule library is simple but requires a running Python process — use cron/Task Scheduler for server jobs', 'Cron: "0 9 * * 1-5" = every weekday at 09:00. "*/15 * * * *" = every 15 minutes', 'APScheduler supports cron, interval, and one-time (date) triggers with persistent job stores']
      },
      evaluate: { questions: [{ question: 'In cron: "30 8 * * 1-5" — when does this run?', options: ['8:30 AM every day', '8:30 AM weekdays (Mon-Fri)', '8:30 PM weekdays', 'Every 8 hours on weekdays'], correctIndex: 1, explanation: 'Fields: 30=min, 8=hour, *=any day, *=any month, 1-5=Mon to Fri. So: 8:30 AM weekdays.' }, { question: 'schedule.every(5).minutes.do(job) — what does this do?', options: ['Runs job once after 5 min', 'Runs job every 5 minutes', 'Delays the script 5 minutes', 'Sets a 5-minute timeout'], correctIndex: 1, explanation: 'schedule registers a recurring job. You must call schedule.run_pending() in a loop to actually execute it.' }, { question: 'Why does the schedule library need "while True: schedule.run_pending()"?', options: ['To prevent memory leaks', 'schedule does not run jobs automatically — you must poll for pending jobs', 'To keep the TCP connection alive', 'It is optional'], correctIndex: 1, explanation: 'schedule only checks and runs due jobs when run_pending() is called. The loop keeps the script running.' }] }
    },
    'Python AI Libraries': {
      understand: {
        theory: `# Python AI Libraries\nThe Python AI ecosystem has three tiers: **API clients** (call hosted models), **frameworks** (orchestrate AI workflows), and **local inference** (run models locally).\n\n\`\`\`python\n# 1. API Clients\nimport google.generativeai as genai\nmodel = genai.GenerativeModel("gemini-3.5-flash")\nres = model.generate_content("Explain RAG in 2 lines")\nprint(res.text)\n\n# 2. HuggingFace Transformers (local or Hub)\nfrom transformers import pipeline\nsentiment = pipeline("sentiment-analysis")\nprint(sentiment("This course is amazing!"))\n\n# 3. LangChain (orchestration)\nfrom langchain.chat_models import ChatOpenAI\nfrom langchain.prompts import ChatPromptTemplate\nchain = ChatPromptTemplate.from_template("Summarise: {text}") | ChatOpenAI()\nprint(chain.invoke({"text": "long article..."}))\n\n# 4. FAISS (vector search for RAG)\nimport faiss, numpy as np\nindex = faiss.IndexFlatL2(768)   # 768-dim embeddings\nindex.add(np.random.rand(100, 768).astype("float32"))\n\`\`\``,
        examples: [{ title: 'Simple RAG pipeline with Gemini + FAISS', language: 'python', code: `import google.generativeai as genai\nimport faiss, numpy as np\n\n# Fake embeddings for demo\ndocs = ["Python is great", "AI is the future", "Pandas handles data"]\nembeds = np.random.rand(len(docs), 768).astype("float32")\n\nindex = faiss.IndexFlatL2(768)\nindex.add(embeds)\n\nquery = np.random.rand(1, 768).astype("float32")\n_, idx = index.search(query, k=2)\ncontext = " ".join([docs[i] for i in idx[0]])\n\nmodel = genai.GenerativeModel("gemini-3.5-flash")\nprint(model.generate_content(f"Context: {context}\\nQ: What is Python?").text)`, explanation: 'RAG (Retrieval-Augmented Generation): find relevant docs via vector similarity, inject as context into the LLM prompt.' }],
        keyPoints: ['google-generativeai, openai are thin API wrappers — easiest to start with; no GPU needed', 'transformers (HuggingFace) lets you run 100k+ models locally but requires decent hardware for large models', 'LangChain chains prompts, tools, and memory; LlamaIndex specialises in document Q&A (RAG)']
      },
      evaluate: { questions: [{ question: 'What is RAG (Retrieval-Augmented Generation)?', options: ['A model architecture', 'Retrieving relevant documents and injecting them as context into an LLM prompt', 'A type of reinforcement learning', 'Fine-tuning a model on new data'], correctIndex: 1, explanation: 'RAG fetches relevant context from a vector database and adds it to the LLM prompt, enabling knowledge beyond the training cutoff.' }, { question: 'transformers pipeline("sentiment-analysis") — what does it need?', options: ['An OpenAI API key', 'A GPU always', 'A pre-trained model (downloaded from HuggingFace Hub)', 'A running server'], correctIndex: 2, explanation: 'pipeline() downloads a pre-trained model from HuggingFace Hub on first use. Small models run on CPU fine.' }, { question: 'FAISS is used for:', options: ['Training neural networks', 'Fast approximate nearest-neighbour search on vector embeddings', 'Web scraping', 'Data visualisation'], correctIndex: 1, explanation: 'FAISS (Facebook AI Similarity Search) indexes high-dimensional vectors and finds the nearest neighbours in milliseconds — core to RAG pipelines.' }] }
    },
  },

  'JavaScript (ES6+) Mastery': {
    'ES6 Syntax & Destructuring': {
      understand: {
        theory: `# ES6 Syntax & Destructuring\nES6 introduced concise, expressive syntax that is now standard JavaScript. Key features: \`let\`/\`const\`, arrow functions, template literals, destructuring, and spread/rest operators.\n\n\`\`\`javascript\n// let/const (block-scoped)\nconst MAX = 100;\nlet count = 0;\n\n// Arrow functions\nconst double = x => x * 2;\nconst add = (a, b) => a + b;\n\n// Template literals\nconst msg = \`Hello \${name}, you have \${count} messages.\`;\n\n// Destructuring\nconst [first, second, ...rest] = [1, 2, 3, 4, 5];\nconst { name, age, city = "Unknown" } = user;\n\n// Spread & rest\nconst merged = { ...obj1, ...obj2 };\nconst combined = [...arr1, ...arr2];\n\n// Short-hand object properties\nconst x = 1, y = 2;\nconst point = { x, y };  // same as { x: x, y: y }\n\`\`\``,
        examples: [{ title: 'Destructuring function parameters', language: 'javascript', code: `function renderUser({ name, role = "user", avatar = "default.png" }) {\n  return \`<div class="\${role}">\${name}<img src="\${avatar}"/></div>\`;\n}\n\nconst users = [\n  { name: "Alice", role: "admin" },\n  { name: "Bob" }\n];\n\nusers.map(renderUser).forEach(html => console.log(html));`, explanation: 'Destructuring in function parameters with defaults. map() transforms each user; forEach() iterates results.' }],
        keyPoints: ['Use const by default; use let when reassignment is needed; avoid var (function-scoped, hoisting causes bugs)', 'Destructuring with defaults: const { x = 0 } = obj — x is 0 if obj.x is undefined', 'Spread (...) copies/merges arrays and objects shallowly — nested objects are still references']
      },
      evaluate: { questions: [{ question: 'const [a, , b] = [1, 2, 3] — what is b?', options: ['1', '2', '3', 'undefined'], correctIndex: 2, explanation: 'The empty slot skips index 1 (value 2). b receives index 2 (value 3).' }, { question: 'const {x: myX} = {x: 42} — what does myX equal?', options: ['The string "x"', '42', 'undefined', 'Error'], correctIndex: 1, explanation: 'const {x: myX} renames the destructured x to myX. myX = 42.' }, { question: 'const merged = {...a, ...b} — if both a and b have key "id", which wins?', options: ['a.id', 'b.id', 'Both are kept as an array', 'Error'], correctIndex: 1, explanation: 'Later spread overwrites earlier. b.id wins because ...b comes after ...a.' }] }
    },
    'Closures & Scope': {
      understand: {
        theory: `# Closures & Scope\nA **closure** is a function that remembers the variables from its outer scope even after that outer function has returned. JavaScript has three scope levels: global, function, and block (let/const).\n\n\`\`\`javascript\n// Closure captures outer variable\nfunction makeCounter(start = 0) {\n  let count = start;   // captured by inner functions\n  return {\n    increment() { count++; },\n    decrement() { count--; },\n    value()     { return count; }\n  };\n}\n\nconst counter = makeCounter(10);\ncounter.increment(); counter.increment();\nconsole.log(counter.value()); // 12\n\n// Classic closure bug with var\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 100); // prints 3,3,3 — BAD\n}\n// Fix with let (block scope)\nfor (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 100); // prints 0,1,2 — GOOD\n}\n\`\`\``,
        examples: [{ title: 'Memoisation using closure', language: 'javascript', code: `function memoize(fn) {\n  const cache = {};   // persists across calls\n  return function(...args) {\n    const key = JSON.stringify(args);\n    if (key in cache) {\n      console.log("cache hit:", key);\n      return cache[key];\n    }\n    cache[key] = fn(...args);\n    return cache[key];\n  };\n}\n\nconst fib = memoize(n => n <= 1 ? n : fib(n-1) + fib(n-2));\nconsole.log(fib(40)); // fast`, explanation: 'cache object is captured in the closure. Every call to the memoized function shares the same cache.' }],
        keyPoints: ['Closures = function + its lexical environment. The inner function holds a reference to outer variables, not copies', 'var is function-scoped and hoisted; let/const are block-scoped — use let/const to avoid closure bugs in loops', 'IIFE (Immediately Invoked Function Expression) is a closure pattern: (function() { /* private scope */ })()']
      },
      evaluate: { questions: [{ question: 'What is a closure?', options: ['A function with no parameters', 'A function that remembers variables from its outer scope', 'A function that throws an error', 'An arrow function'], correctIndex: 1, explanation: 'A closure is a function bundled together with references to the variables in its surrounding lexical scope.' }, { question: 'Why does for(var i=0;i<3;i++) setTimeout(()=>console.log(i),0) print 3,3,3?', options: ['setTimeout is async', 'var is function-scoped — one shared i exists; by timeout time i=3', 'setTimeout ignores loops', 'console.log buffers output'], correctIndex: 1, explanation: 'var i is one shared variable in the function scope. All three callbacks close over the same i, which is 3 after the loop.' }, { question: 'What does a module pattern achieve with closures?', options: ['Faster execution', 'Private state not accessible from outside', 'Global variable access', 'Better error handling'], correctIndex: 1, explanation: 'Returning an object from a function exposes only public methods while keeping internal variables private via closure.' }] }
    },
    'Promises & Async/Await': {
      understand: {
        theory: `# Promises & Async/Await\nA **Promise** represents a value that will be available in the future. \`async/await\` is syntactic sugar over Promises, making asynchronous code look synchronous.\n\n\`\`\`javascript\n// Promise creation\nconst fetchUser = (id) => new Promise((resolve, reject) => {\n  if (id > 0) resolve({ id, name: "Alice" });\n  else reject(new Error("Invalid ID"));\n});\n\n// Promise chain\nfetchUser(1)\n  .then(user => user.name.toUpperCase())\n  .then(name => console.log(name))\n  .catch(err => console.error(err.message))\n  .finally(() => console.log("Done"));\n\n// async/await (preferred)\nasync function loadProfile(id) {\n  try {\n    const user  = await fetchUser(id);\n    const posts = await getPosts(user.id);\n    return { user, posts };\n  } catch (err) {\n    console.error("Load failed:", err);\n  }\n}\n\n// Parallel execution\nconst [users, products] = await Promise.all([fetchUsers(), fetchProducts()]);\n\`\`\``,
        examples: [{ title: 'Promise.all for parallel API calls', language: 'javascript', code: `async function getDashboard(userId) {\n  const [profile, orders, notifications] = await Promise.all([\n    fetch(\`/api/users/\${userId}\`).then(r => r.json()),\n    fetch(\`/api/orders?user=\${userId}\`).then(r => r.json()),\n    fetch(\`/api/notifications?user=\${userId}\`).then(r => r.json())\n  ]);\n  return { profile, orders, notifications };\n}\n\n// All 3 requests fire simultaneously — total time = slowest request`, explanation: 'Promise.all fires all requests in parallel and waits for ALL to complete. Much faster than sequential awaits.' }],
        keyPoints: ['async functions always return a Promise. Awaiting a non-Promise value just wraps it: await 42 → 42', 'Unhandled promise rejections crash Node.js — always use try/catch or .catch()', 'Promise.all → fails fast if any rejects. Promise.allSettled → waits for all, reports success/failure each']
      },
      evaluate: { questions: [{ question: 'What does async function always return?', options: ['undefined', 'A Promise', 'The direct value', 'A callback'], correctIndex: 1, explanation: 'async functions always wrap their return value in a resolved Promise.' }, { question: 'Promise.all([a,b,c]) — what happens if b rejects?', options: ['Returns partial results', 'Waits for a and c to finish', 'Rejects immediately with b\'s error', 'Retries b'], correctIndex: 2, explanation: 'Promise.all rejects as soon as ANY promise rejects (fail-fast). Use Promise.allSettled to get all results.' }, { question: 'await keyword can only be used:', options: ['In any function', 'Inside async functions', 'Inside try/catch only', 'In arrow functions only'], correctIndex: 1, explanation: 'await must be inside a function marked async. Using it elsewhere is a SyntaxError.' }] }
    },
    'Event Loop & Concurrency': {
      understand: {
        theory: `# Event Loop & Concurrency\nJavaScript is **single-threaded** but non-blocking. The Event Loop processes tasks from a queue. Understanding it explains why async code works without threads.\n\n**Execution order:**\n1. **Call Stack** — current synchronous code\n2. **Microtask Queue** — Promise callbacks (.then/.catch), queueMicrotask\n3. **Macrotask Queue** — setTimeout, setInterval, I/O, UI events\n\nMicrotasks drain completely before the next macrotask runs.\n\n\`\`\`javascript\nconsole.log("1");              // sync\n\nsetTimeout(() => console.log("2"), 0);  // macrotask\n\nPromise.resolve().then(() => console.log("3"));  // microtask\n\nconsole.log("4");              // sync\n\n// Output: 1, 4, 3, 2\n\`\`\``,
        examples: [{ title: 'Visualising task priorities', language: 'javascript', code: `console.log("start");\n\nsetTimeout(() => console.log("setTimeout"), 0);\n\nqueueMicrotask(() => console.log("microtask 1"));\n\nPromise.resolve().then(() => {\n  console.log("Promise .then");\n  queueMicrotask(() => console.log("nested microtask"));\n});\n\nconsole.log("end");\n// Order: start → end → microtask 1 → Promise .then → nested microtask → setTimeout`, explanation: 'All microtasks (including those queued during microtask processing) run before the next macrotask.' }],
        keyPoints: ['JS is single-threaded — "concurrency" is achieved by deferring I/O callbacks via the event loop', 'Microtasks (Promises) always run before macrotasks (setTimeout) — even setTimeout(fn, 0)', 'Never block the call stack with long synchronous loops — it freezes the UI. Offload heavy work to Web Workers']
      },
      evaluate: { questions: [{ question: 'What is the output order of: console.log("A"); setTimeout(()=>log("B"),0); Promise.resolve().then(()=>log("C")); console.log("D")?', options: ['A B C D', 'A D B C', 'A D C B', 'D A C B'], correctIndex: 2, explanation: 'Sync runs first (A, D), then microtasks (C = Promise), then macrotasks (B = setTimeout).' }, { question: 'Why does setTimeout(fn, 0) not run "immediately"?', options: ['0ms is invalid', 'It is placed in the macrotask queue and must wait for the call stack and microtasks to clear', 'JavaScript ignores 0', 'It runs in a separate thread'], correctIndex: 1, explanation: 'The 0ms delay means "as soon as possible" but still respects queue priority: microtasks clear first.' }, { question: 'What problem does the Event Loop solve?', options: ['Multi-threading', 'Memory management', 'Non-blocking I/O in a single-threaded environment', 'CSS rendering'], correctIndex: 2, explanation: 'The Event Loop allows JS to perform I/O without blocking — async callbacks are queued and executed when the stack is empty.' }] }
    },
    'Prototype & Class System': {
      understand: {
        theory: `# Prototype & Class System\nEvery JS object has a hidden \`[[Prototype]]\` link — a chain that enables inheritance. ES6 \`class\` syntax is clean sugar over this prototype system.\n\n\`\`\`javascript\n// ES6 Class (preferred syntax)\nclass Animal {\n  #name;  // private field\n  constructor(name, sound) {\n    this.#name = name;\n    this.sound = sound;\n  }\n  speak() { return \`\${this.#name} says \${this.sound}\`; }\n  get name() { return this.#name; }\n  static create(name, sound) { return new Animal(name, sound); }\n}\n\nclass Dog extends Animal {\n  constructor(name) {\n    super(name, "Woof");\n    this.tricks = [];\n  }\n  learn(trick) { this.tricks.push(trick); }\n  speak() { return super.speak() + "!"; }  // override\n}\n\nconst dog = new Dog("Rex");\nconsole.log(dog instanceof Animal); // true\n\`\`\``,
        examples: [{ title: 'Mixins — composing behaviour', language: 'javascript', code: `const Serializable = (Base) => class extends Base {\n  toJSON() { return JSON.stringify(this); }\n  static fromJSON(str) { return Object.assign(new this(), JSON.parse(str)); }\n};\n\nconst Validatable = (Base) => class extends Base {\n  validate() { return Object.values(this).every(v => v !== null); }\n};\n\nclass User extends Serializable(Validatable(class {})) {\n  constructor(name, email) {\n    super();\n    Object.assign(this, { name, email });\n  }\n}`, explanation: 'Mixin pattern composes behaviour without deep inheritance chains. Each mixin wraps the Base class.' }],
        keyPoints: ['Class syntax is sugar — underneath it still uses prototypes. Object.getPrototypeOf(dog) === Dog.prototype', 'Private fields (#field) are truly private — not accessible outside the class, even with bracket notation', 'Avoid deep inheritance chains. Prefer composition (mixins, interfaces) for flexible code']
      },
      evaluate: { questions: [{ question: 'class Dog extends Animal — what does super() call in Dog\'s constructor?', options: ['Animal\'s speak()', 'Animal\'s constructor', 'Object constructor', 'Dog\'s own constructor'], correctIndex: 1, explanation: 'super() in a subclass constructor calls the parent class\'s constructor. It must be called before using this.' }, { question: 'What are private class fields (#field)?', options: ['Properties accessible via this.#field only inside the class', 'Properties starting with underscore by convention', 'Properties stored in localStorage', 'Static-only properties'], correctIndex: 0, explanation: 'Private fields (#field) are class-level privacy enforced by the JavaScript engine — not just a naming convention.' }, { question: 'Dog instanceof Animal returns true because:', options: ['Dog and Animal share the same constructor', 'Animal.prototype is in Dog\'s prototype chain', 'Dog extends Animal syntactically', 'instanceof checks the class name'], correctIndex: 1, explanation: 'instanceof traverses the prototype chain. Since Dog.prototype.__proto__ === Animal.prototype, it returns true.' }] }
    },
    'Modules & Bundling': {
      understand: {
        theory: `# Modules & Bundling\nES Modules (ESM) use \`export\`/\`import\`. Bundlers (Vite, webpack, esbuild) bundle modules into optimised files for browsers. Tree-shaking removes unused exports.\n\n\`\`\`javascript\n// math.js\nexport const PI = 3.14159;\nexport function add(a, b) { return a + b; }\nexport default class Calculator { /* ... */ }  // default export\n\n// app.js\nimport Calculator, { PI, add } from "./math.js";  // named + default\nimport * as Math from "./math.js";                 // namespace import\nimport("./heavy.js").then(m => m.doWork());        // dynamic import\n\`\`\`\n\n**Vite config (vite.config.ts):**\n\`\`\`typescript\nexport default defineConfig({\n  build: {\n    rollupOptions: {\n      output: {\n        manualChunks: { vendor: ["react", "react-dom"] }\n      }\n    }\n  }\n});\n\`\`\``,
        examples: [{ title: 'Code splitting with dynamic import', language: 'javascript', code: `// Load a heavy chart library only when needed\nasync function showChart(data) {\n  const { Chart } = await import("chart.js");\n  new Chart(document.getElementById("canvas"), {\n    type: "bar",\n    data: { labels: data.labels, datasets: data.sets }\n  });\n}\n\n// React lazy loading\nconst HeavyDashboard = React.lazy(() => import("./Dashboard"));\n<Suspense fallback={<Spinner />}>\n  <HeavyDashboard />\n</Suspense>`, explanation: 'Dynamic import() is async and returns a Promise. Bundlers create separate chunks that load on demand.' }],
        keyPoints: ['Named exports: export const x = 1. Default export: export default function(). Only one default per module', 'Tree-shaking works with static imports (import { x } from "...") — dynamic require() cannot be tree-shaken', 'Code splitting via dynamic import() reduces initial bundle size — load heavy modules only when needed']
      },
      evaluate: { questions: [{ question: 'import { x } vs import * as M — what is the difference?', options: ['No difference', '{ x } imports one named export; * as M imports all exports as a namespace object', '* as M only works in Node.js', '{ x } requires a default export'], correctIndex: 1, explanation: '{ x } imports only that named export. * as M imports everything into an object: M.x, M.y, etc.' }, { question: 'What is tree-shaking?', options: ['Minifying CSS', 'Removing unused exports from the final bundle', 'Sorting import statements', 'Splitting code into chunks'], correctIndex: 1, explanation: 'Tree-shaking statically analyses imports and removes unused exported code, reducing bundle size.' }, { question: 'import("./heavy.js") returns:', options: ['The module immediately', 'A Promise resolving to the module', 'undefined', 'Error in browsers'], correctIndex: 1, explanation: 'Dynamic import() is always async and returns a Promise that resolves to the module namespace object.' }] }
    },
    'Error Handling Patterns': {
      understand: {
        theory: `# Error Handling Patterns\nRobust JS uses typed errors, async/await try-catch, and proper error propagation. Never swallow errors silently.\n\n\`\`\`javascript\n// Custom error classes\nclass AppError extends Error {\n  constructor(message, code, statusCode = 500) {\n    super(message);\n    this.name = "AppError";\n    this.code = code;\n    this.statusCode = statusCode;\n  }\n}\nclass NotFoundError extends AppError {\n  constructor(resource) {\n    super(\`\${resource} not found\`, "NOT_FOUND", 404);\n  }\n}\n\n// Async error handling\nasync function getUser(id) {\n  try {\n    const res = await fetch(\`/users/\${id}\`);\n    if (!res.ok) throw new AppError("API error", "API_ERR", res.status);\n    return await res.json();\n  } catch (err) {\n    if (err instanceof NotFoundError) return null;  // handled\n    throw err;  // re-throw unexpected errors\n  }\n}\n\`\`\``,
        examples: [{ title: 'Result pattern (no exceptions)', language: 'javascript', code: `// Rust-inspired Result type\nconst Result = {\n  ok: (value) => ({ ok: true, value }),\n  err: (error) => ({ ok: false, error }),\n};\n\nasync function parseJSON(str) {\n  try {\n    return Result.ok(JSON.parse(str));\n  } catch (e) {\n    return Result.err(e.message);\n  }\n}\n\nconst result = await parseJSON('{"name":"Alice"}');\nif (result.ok) console.log(result.value);\nelse console.error("Parse failed:", result.error);`, explanation: 'Result pattern returns error as data — no throws. Callers explicitly handle success/failure without try-catch.' }],
        keyPoints: ['Create custom Error subclasses for domain errors — enables instanceof checks and structured error codes', 'Always re-throw errors you cannot handle. Swallowing errors (empty catch) hides bugs', 'In async code, unhandled rejections crash Node.js — add process.on("unhandledRejection", handler) in production']
      },
      evaluate: { questions: [{ question: 'class NotFoundError extends Error — why is this useful?', options: ['Better performance', 'Allows instanceof checks to identify error type', 'Provides automatic retry logic', 'Required by Node.js'], correctIndex: 1, explanation: 'Custom error classes allow err instanceof NotFoundError to distinguish error types and handle them differently.' }, { question: 'When should you re-throw an error in a catch block?', options: ['Always', 'Never — always handle it', 'When you cannot meaningfully handle it locally', 'Only in production'], correctIndex: 2, explanation: 'Re-throw errors you cannot handle — let higher-level code (or global handlers) deal with them.' }, { question: 'What is wrong with: try { doWork() } catch(e) {} — empty catch?', options: ['SyntaxError', 'Nothing — it is a valid pattern', 'Swallows errors silently making debugging impossible', 'Only works in strict mode'], correctIndex: 2, explanation: 'Empty catch blocks hide bugs. At minimum log the error. Never silently discard exceptions.' }] }
    },
    'Testing with Jest': {
      understand: {
        theory: `# Testing with Jest\nJest is the most popular JS testing framework. Tests are functions with assertions that verify code behaviour. Key concepts: unit tests, mocks, async testing, coverage.\n\n\`\`\`javascript\n// math.test.js\nimport { add, divide } from "./math";\n\ndescribe("arithmetic", () => {\n  test("add returns correct sum", () => {\n    expect(add(2, 3)).toBe(5);\n    expect(add(-1, 1)).toBe(0);\n  });\n\n  test("divide throws on zero", () => {\n    expect(() => divide(5, 0)).toThrow("Division by zero");\n  });\n});\n\n// Mocking\njest.mock("./api");\nimport { fetchUser } from "./api";\nfetchUser.mockResolvedValue({ id: 1, name: "Alice" });\n\n// Async test\ntest("fetchUser returns user", async () => {\n  const user = await fetchUser(1);\n  expect(user.name).toBe("Alice");\n});\n\`\`\``,
        examples: [{ title: 'Testing a React component with Testing Library', language: 'javascript', code: `import { render, screen, fireEvent } from "@testing-library/react";\nimport Counter from "./Counter";\n\ntest("counter increments on click", () => {\n  render(<Counter />);\n  expect(screen.getByText("Count: 0")).toBeInTheDocument();\n  \n  fireEvent.click(screen.getByRole("button", { name: /increment/i }));\n  \n  expect(screen.getByText("Count: 1")).toBeInTheDocument();\n});`, explanation: 'Testing Library queries the DOM as a user would. screen.getByRole finds by accessible role, not implementation details.' }],
        keyPoints: ['Test behaviour, not implementation. If tests break when you refactor without changing behaviour, tests are too tightly coupled', 'jest.mock() replaces a module with a mock version. mockResolvedValue sets what async mocks return', 'Aim for ≥80% code coverage but focus on critical paths — 100% coverage does not mean bug-free']
      },
      evaluate: { questions: [{ question: 'expect(fn).toThrow("message") — what does this assert?', options: ['fn returns "message"', 'Calling fn() throws an error containing "message"', 'fn is a valid function', 'fn has been called once'], correctIndex: 1, explanation: 'toThrow() asserts that calling the wrapped function throws. Pass a string to match the error message.' }, { question: 'jest.mock("./api") — what does this do?', options: ['Runs the api module', 'Replaces all exports of ./api with Jest mock functions', 'Deletes the api module', 'Tests the api module'], correctIndex: 1, explanation: 'jest.mock() auto-mocks the module. All exported functions become jest.fn() spies.' }, { question: 'What is the purpose of beforeEach() in Jest?', options: ['Run once before all tests in the file', 'Run before each individual test in a describe block', 'Reset mocks globally', 'Skip slow tests'], correctIndex: 1, explanation: 'beforeEach() runs setup code before EACH test — ideal for resetting state or creating fresh fixtures.' }] }
    },
  },

  'React 19 Masterclass': {
    'Component Architecture': {
      understand: {
        theory: `# Component Architecture\nReact apps are trees of components. Good architecture: small, focused components; clear data flow; separation of UI, logic, and data fetching.\n\n\`\`\`jsx\n// Presentational (dumb) component — props in, JSX out\nfunction UserCard({ name, role, avatar }) {\n  return (\n    <div className="card">\n      <img src={avatar} alt={name} />\n      <h3>{name}</h3>\n      <p>{role}</p>\n    </div>\n  );\n}\n\n// Container (smart) component — owns state & logic\nfunction UserList() {\n  const [users, setUsers] = useState([]);\n  useEffect(() => { fetchUsers().then(setUsers); }, []);\n  return users.map(u => <UserCard key={u.id} {...u} />);\n}\n\n// Composition over inheritance\nfunction Modal({ title, children, footer }) {\n  return (\n    <div className="modal">\n      <h2>{title}</h2>\n      <div className="body">{children}</div>\n      <div className="footer">{footer}</div>\n    </div>\n  );\n}\n\`\`\``,
        examples: [{ title: 'Compound component pattern', language: 'jsx', code: `// Tabs.jsx — compound component\nexport function Tabs({ children }) {\n  const [active, setActive] = useState(0);\n  return <TabContext.Provider value={{ active, setActive }}>{children}</TabContext.Provider>;\n}\nTabs.List = function TabList({ children }) {\n  return <div className="tab-list">{children}</div>;\n};\nTabs.Tab = function Tab({ index, label }) {\n  const { active, setActive } = useContext(TabContext);\n  return <button className={active === index ? "active" : ""} onClick={() => setActive(index)}>{label}</button>;\n};\n\n// Usage\n<Tabs>\n  <Tabs.List>\n    <Tabs.Tab index={0} label="Profile" />\n    <Tabs.Tab index={1} label="Settings" />\n  </Tabs.List>\n</Tabs>`, explanation: 'Compound components share state via Context without prop drilling. The parent controls shared state; children are specialised pieces.' }],
        keyPoints: ['Lift state up only as far as needed — keep state close to where it is used', 'Composition > Inheritance — build complex UIs by composing simple components, not extending classes', 'Separate concerns: UI components (JSX), custom hooks (logic), services (API calls)']
      },
      evaluate: { questions: [{ question: 'When should you lift state up?', options: ['Always', 'When two sibling components need to share the same state', 'Only in class components', 'When performance is slow'], correctIndex: 1, explanation: 'Lift state to the nearest common ancestor of components that need to share it.' }, { question: 'What is the children prop in React?', options: ['A special prop containing JSX passed between component tags', 'An array of child component classes', 'An event listener', 'A CSS class name'], correctIndex: 0, explanation: 'children is the JSX content passed between opening and closing tags: <Modal>content here</Modal>' }, { question: 'key prop in list rendering — why is it important?', options: ['For CSS styling', 'For React to track elements across re-renders and minimise DOM updates', 'For SEO', 'Required for TypeScript'], correctIndex: 1, explanation: 'key helps React identify which items changed, added, or removed — enabling efficient list reconciliation.' }] }
    },
    'Hooks Deep Dive': {
      understand: {
        theory: `# Hooks Deep Dive\nHooks let functional components use state and lifecycle features. Rules: call only at top level, call only inside React functions.\n\n\`\`\`jsx\n// useState — local state\nconst [count, setCount] = useState(0);\n\n// useEffect — side effects (data fetch, subscriptions, DOM)\nuseEffect(() => {\n  const sub = subscribe(topic);   // setup\n  return () => sub.unsubscribe(); // cleanup on unmount\n}, [topic]);                       // re-run when topic changes\n\n// useRef — mutable value that doesn't trigger re-render\nconst inputRef = useRef(null);\ninputRef.current.focus();\n\n// useMemo — memoize expensive computation\nconst sorted = useMemo(() => items.sort(compare), [items]);\n\n// useCallback — stable function reference\nconst handleClick = useCallback(() => doWork(id), [id]);\n\n// useContext\nconst theme = useContext(ThemeContext);\n\n// useReducer — complex state logic\nconst [state, dispatch] = useReducer(reducer, initialState);\ndispatch({ type: "INCREMENT", payload: 5 });\n\`\`\``,
        examples: [{ title: 'Custom hook — useLocalStorage', language: 'jsx', code: `function useLocalStorage(key, initialValue) {\n  const [value, setValue] = useState(() => {\n    try {\n      const item = localStorage.getItem(key);\n      return item ? JSON.parse(item) : initialValue;\n    } catch {\n      return initialValue;\n    }\n  });\n\n  const setStoredValue = useCallback((newValue) => {\n    setValue(newValue);\n    localStorage.setItem(key, JSON.stringify(newValue));\n  }, [key]);\n\n  return [value, setStoredValue];\n}\n\n// Usage\nconst [theme, setTheme] = useLocalStorage("theme", "dark");`, explanation: 'Custom hooks extract reusable stateful logic. They start with "use" and can call other hooks. Initialiser function in useState runs once.' }],
        keyPoints: ['useEffect cleanup function runs on unmount AND before re-run — essential for subscriptions and timers', 'useMemo/useCallback add overhead — only use when you have measured a real performance problem', 'Custom hooks are the preferred way to share stateful logic between components — better than HOCs or render props']
      },
      evaluate: { questions: [{ question: 'useEffect(fn, []) — when does fn run?', options: ['On every render', 'Only once after the initial render (mount)', 'On every state change', 'Never'], correctIndex: 1, explanation: 'Empty dependency array [] makes useEffect run once — after mount. Equivalent to componentDidMount.' }, { question: 'What does the cleanup function in useEffect do?', options: ['Resets state to initial value', 'Runs before the component unmounts and before the effect re-runs', 'Clears the cache', 'Cancels all pending requests automatically'], correctIndex: 1, explanation: 'The returned function from useEffect cleans up (unsubscribes, clears timers) before unmount or before the next effect run.' }, { question: 'When should you NOT use useCallback?', options: ['When the function is used in a useEffect dependency', 'When the function is passed as a prop to a memoized child', 'For simple inline handlers that do not cause performance issues', 'When the function depends on state'], correctIndex: 2, explanation: 'useCallback adds overhead. Only use it when you\'ve measured re-render problems, not as a default.' }] }
    },
    'State Management (Zustand)': {
      understand: {
        theory: `# State Management with Zustand\nZustand is a minimal, fast state management library. Unlike Redux, no boilerplate — just create a store with state and actions.\n\n\`\`\`typescript\nimport { create } from "zustand";\nimport { persist } from "zustand/middleware";\n\ninterface CartStore {\n  items: CartItem[];\n  total: number;\n  addItem: (item: CartItem) => void;\n  removeItem: (id: string) => void;\n  clearCart: () => void;\n}\n\nexport const useCartStore = create<CartStore>()(\n  persist(\n    (set, get) => ({\n      items: [],\n      total: 0,\n      addItem: (item) => set((state) => ({\n        items: [...state.items, item],\n        total: state.total + item.price,\n      })),\n      removeItem: (id) => set((state) => ({\n        items: state.items.filter(i => i.id !== id),\n        total: state.items.filter(i => i.id !== id).reduce((s, i) => s + i.price, 0),\n      })),\n      clearCart: () => set({ items: [], total: 0 }),\n    }),\n    { name: "cart-storage" }  // persists to localStorage\n  )\n);\n\n// Usage in component\nconst { items, addItem } = useCartStore();\n\`\`\``,
        examples: [{ title: 'Derived state with selectors', language: 'typescript', code: `const useCartStore = create<CartStore>()((set) => ({/*...*/}));\n\n// Selector — only re-renders when itemCount changes\nconst itemCount = useCartStore(state => state.items.length);\nconst total    = useCartStore(state => state.total);\n\n// Accessing store outside React (e.g., in services)\nconst state = useCartStore.getState();\nuseCartStore.setState({ items: [] });  // direct mutation`, explanation: 'Selectors prevent unnecessary re-renders — component only re-renders when the selected slice changes.' }],
        keyPoints: ['Zustand stores are just JS closures — no Provider, no actions/reducers/selectors boilerplate', 'Use selectors (useStore(s => s.slice)) to subscribe to only the part of state you need', 'persist middleware syncs store to localStorage/sessionStorage automatically']
      },
      evaluate: { questions: [{ question: 'create((set, get) => ({...})) — what is "set" in Zustand?', options: ['A React state setter', 'A function to update the store state', 'A localStorage setter', 'A Redux dispatcher'], correctIndex: 1, explanation: 'set() updates the store state. It accepts partial state or a function: set(state => ({count: state.count + 1}))' }, { question: 'How does Zustand prevent unnecessary re-renders?', options: ['It batches all updates', 'Through selectors — components subscribe only to specific slices', 'By using a virtual DOM', 'By disabling StrictMode'], correctIndex: 1, explanation: 'useStore(s => s.count) only re-renders when count changes — not when any other part of the store updates.' }, { question: 'Compared to Redux, Zustand requires:', options: ['More boilerplate (actions, reducers, selectors)', 'The same amount of boilerplate', 'Significantly less boilerplate — just a create() call', 'A Redux DevTools integration'], correctIndex: 2, explanation: 'Zustand eliminates actions, reducers, and Provider — the store is a single create() call.' }] }
    },
    'React Query & Data Fetching': {
      understand: {
        theory: `# React Query & Data Fetching\nReact Query (TanStack Query) manages server state: caching, background refetch, loading/error states, pagination, and mutations.\n\n\`\`\`typescript\nimport { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";\n\n// Query — read data\nfunction UserProfile({ id }) {\n  const { data: user, isLoading, error } = useQuery({\n    queryKey: ["user", id],        // cache key\n    queryFn: () => fetchUser(id),  // fetch function\n    staleTime: 5 * 60 * 1000,     // consider fresh for 5 min\n  });\n\n  if (isLoading) return <Spinner />;\n  if (error) return <Error message={error.message} />;\n  return <div>{user.name}</div>;\n}\n\n// Mutation — write data\nfunction CreatePost() {\n  const queryClient = useQueryClient();\n  const mutation = useMutation({\n    mutationFn: (post) => createPost(post),\n    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["posts"] }),\n  });\n  return <button onClick={() => mutation.mutate({ title: "Hello" })}>Post</button>;\n}\n\`\`\``,
        examples: [{ title: 'Paginated query with infinite scroll', language: 'typescript', code: `const { data, fetchNextPage, hasNextPage, isFetchingNextPage } = useInfiniteQuery({\n  queryKey: ["products"],\n  queryFn: ({ pageParam = 1 }) => fetchProducts(pageParam),\n  getNextPageParam: (lastPage) => lastPage.nextCursor ?? undefined,\n});\n\n// In JSX\n{data?.pages.flat().map(p => <ProductCard key={p.id} {...p} />)}\n<button onClick={fetchNextPage} disabled={!hasNextPage || isFetchingNextPage}>\n  {isFetchingNextPage ? "Loading..." : "Load More"}\n</button>`, explanation: 'useInfiniteQuery appends new pages to existing data. getNextPageParam tells React Query what to pass as pageParam next.' }],
        keyPoints: ['queryKey must be unique and serialisable. Include all variables the fetch depends on: ["user", userId]', 'staleTime controls how long cached data is considered fresh. After staleTime, background refetch triggers', 'invalidateQueries() after mutations forces the related queries to refetch — keeps UI in sync']
      },
      evaluate: { questions: [{ question: 'useQuery queryKey: ["user", userId] — why include userId?', options: ['For logging', 'So each userId gets a separate cache entry and refetches when userId changes', 'For TypeScript generics', 'Required by React Query'], correctIndex: 1, explanation: 'React Query uses queryKey as the cache key. Different userIds need different keys to avoid cache collisions.' }, { question: 'What does queryClient.invalidateQueries() do?', options: ['Deletes the query from cache', 'Marks queries as stale and triggers background refetch', 'Cancels pending requests', 'Resets the form'], correctIndex: 1, explanation: 'invalidateQueries marks matching cached data as stale, triggering a background refetch on next access.' }, { question: 'staleTime: 5 * 60 * 1000 means:', options: ['Fetch every 5 minutes', 'Consider data fresh for 5 minutes (no refetch during this window)', 'Cache expiry after 5 minutes', 'Timeout after 5 minutes'], correctIndex: 1, explanation: 'staleTime is how long cached data is "fresh". During this window, React Query serves from cache without refetching.' }] }
    },
    'Performance Optimization': {
      understand: {
        theory: `# React Performance Optimization\nReact re-renders a component when its state or props change. Optimisation prevents unnecessary re-renders and expensive computations.\n\n\`\`\`jsx\n// React.memo — skip re-render if props unchanged\nconst ExpensiveList = React.memo(function({ items, onSelect }) {\n  return items.map(i => <Item key={i.id} {...i} onClick={() => onSelect(i.id)} />);\n});\n\n// useMemo — cache expensive calculation\nconst sorted = useMemo(\n  () => [...items].sort((a, b) => a.price - b.price),\n  [items]  // only re-sort when items changes\n);\n\n// useCallback — stable function reference for memo'd children\nconst handleSelect = useCallback((id) => {\n  setSelected(prev => [...prev, id]);\n}, []);  // stable — empty deps\n\n// Lazy loading routes\nconst Dashboard = React.lazy(() => import("./Dashboard"));\n<Suspense fallback={<Skeleton />}><Dashboard /></Suspense>\n\n// Virtualise long lists (react-window)\nimport { FixedSizeList } from "react-window";\n<FixedSizeList height={600} itemCount={10000} itemSize={50}>\n  {({ index, style }) => <div style={style}>{items[index].name}</div>}\n</FixedSizeList>\n\`\`\``,
        examples: [{ title: 'Profiler-driven optimisation', language: 'jsx', code: `import { Profiler } from "react";\n\nfunction onRender(id, phase, duration) {\n  if (duration > 16) {  // 1 frame at 60fps\n    console.warn(\`[PERF] \${id} (\${phase}) took \${duration.toFixed(1)}ms\`);\n  }\n}\n\n<Profiler id="ProductList" onRender={onRender}>\n  <ProductList items={filteredItems} />\n</Profiler>`, explanation: 'React Profiler measures render duration. Log renders over 16ms (1 frame budget at 60fps). Only add memoisation after measuring.' }],
        keyPoints: ['Profile before optimising — React DevTools Profiler shows which components re-render and how long they take', 'React.memo + useCallback must be used together: memo prevents re-renders on same props; useCallback keeps function references stable', 'Virtualise lists over ~100 items with react-window/react-virtual — rendering 10,000 DOM nodes is the real bottleneck']
      },
      evaluate: { questions: [{ question: 'React.memo prevents re-renders when:', options: ['State changes anywhere in the app', 'The component\'s own state changes', 'Props passed to the component are shallowly equal to previous props', 'The parent is memo\'d'], correctIndex: 2, explanation: 'React.memo does a shallow comparison of props. If props are shallowly equal, it skips re-render.' }, { question: 'A memo\'d child still re-renders. Most likely cause:', options: ['memo() is broken', 'A prop is an object/function created inline in the parent — new reference each render', 'The child has useEffect', 'TypeScript issue'], correctIndex: 1, explanation: 'Inline objects/functions ({} or () => {}) create new references every render, failing shallow equality — use useMemo/useCallback.' }, { question: 'When should you use react-window?', options: ['For lists under 50 items', 'For lists over ~100-200 items where all DOM nodes would be expensive', 'Only for infinite scroll', 'For all lists'], correctIndex: 1, explanation: 'react-window renders only visible rows in the viewport, drastically reducing DOM nodes for large lists.' }] }
    },
    'Server Components': {
      understand: {
        theory: `# React Server Components (RSC)\nServer Components (React 19 / Next.js App Router) run on the server — zero client JS bundle impact. They can directly access databases, file system, and server secrets.\n\n\`\`\`typescript\n// app/dashboard/page.tsx — Server Component (default)\nasync function DashboardPage() {\n  // Direct DB access — no API needed!\n  const user = await db.users.findUnique({ where: { id: session.userId } });\n  const stats = await db.stats.aggregate(/* ... */);\n\n  return (\n    <main>\n      <h1>Welcome, {user.name}</h1>\n      <StatsGrid stats={stats} />          {/* also Server */}\n      <InteractiveChart data={stats} />    {/* Client Component */}\n    </main>\n  );\n}\n\n// components/InteractiveChart.tsx — Client Component\n"use client";\nimport { useState } from "react";\n\nexport function InteractiveChart({ data }) {\n  const [filter, setFilter] = useState("all");\n  // ... chart with useState/useEffect/event handlers\n}\n\`\`\``,
        examples: [{ title: 'Data fetching waterfall vs parallel', language: 'typescript', code: `// Bad — waterfall (sequential)\nasync function Page({ params }) {\n  const user = await getUser(params.id);  // wait\n  const posts = await getPosts(user.id);  // wait\n  return <div>{/*...*/}</div>;\n}\n\n// Good — parallel\nasync function Page({ params }) {\n  const [user, posts] = await Promise.all([\n    getUser(params.id),\n    getPosts(params.id),  // can fetch in parallel\n  ]);\n  return <div>{/*...*/}</div>;\n}`, explanation: 'Server Components can use Promise.all to run multiple DB queries in parallel — eliminating N+1 query waterfalls.' }],
        keyPoints: ['"use client" marks a Client Component — it ships to the browser. Server Components never ship JS to the client', 'Server Components can pass data (not functions) to Client Components as props — no event handlers or state', 'Streaming with Suspense boundaries shows content progressively — fast Time to First Byte even with slow data']
      },
      evaluate: { questions: [{ question: 'What makes a component a Server Component in Next.js App Router?', options: ['It is in the /server/ folder', 'It imports from "server-only"', 'It is the default — no "use client" directive needed', 'It uses useServerData hook'], correctIndex: 2, explanation: 'In App Router, all components are Server Components by default. Add "use client" at the top to opt into a Client Component.' }, { question: 'Can Server Components use useState?', options: ['Yes, with "use server" directive', 'No — hooks require client-side JS runtime', 'Yes, but only with React 19', 'Only useReducer works on server'], correctIndex: 1, explanation: 'Server Components run once on the server at request time — no interactive re-rendering, no hooks like useState/useEffect.' }, { question: 'The main benefit of Server Components is:', options: ['Better SEO', 'Zero client bundle cost — their code never ships to the browser', 'Faster hydration', 'Automatic code splitting'], correctIndex: 1, explanation: 'Server Component code never ships to the client. Database calls, heavy parsing, and secret env vars stay on the server.' }] }
    },
    'Testing React Apps': {
      understand: {
        theory: `# Testing React Apps\nTest at three levels: unit (single function), component (rendered output + interactions), E2E (full browser flow). React Testing Library (RTL) is the standard for components.\n\n\`\`\`typescript\nimport { render, screen, fireEvent, waitFor } from "@testing-library/react";\nimport userEvent from "@testing-library/user-event";\n\n// Component test\ntest("login form submits correctly", async () => {\n  const onSubmit = jest.fn();\n  render(<LoginForm onSubmit={onSubmit} />);\n\n  await userEvent.type(screen.getByLabelText(/email/i), "alice@co.com");\n  await userEvent.type(screen.getByLabelText(/password/i), "Secret123");\n  await userEvent.click(screen.getByRole("button", { name: /sign in/i }));\n\n  expect(onSubmit).toHaveBeenCalledWith({\n    email: "alice@co.com",\n    password: "Secret123",\n  });\n});\n\n// Async — wait for loading state to resolve\ntest("shows users after load", async () => {\n  render(<UserList />);\n  expect(screen.getByText(/loading/i)).toBeInTheDocument();\n  await waitFor(() => expect(screen.getByText("Alice")).toBeInTheDocument());\n});\n\`\`\``,
        examples: [{ title: 'Mocking a hook with jest', language: 'typescript', code: `jest.mock("../hooks/useAuth", () => ({\n  useAuth: () => ({ user: { name: "Alice", role: "admin" }, isLoading: false })\n}));\n\ntest("admin sees delete button", () => {\n  render(<PostActions postId="123" />);\n  expect(screen.getByRole("button", { name: /delete/i })).toBeInTheDocument();\n});\n\ntest("loading state shows skeleton", () => {\n  jest.mock("../hooks/useAuth", () => ({ useAuth: () => ({ isLoading: true }) }));\n  render(<PostActions postId="123" />);\n  expect(screen.getByTestId("skeleton")).toBeInTheDocument();\n});`, explanation: 'jest.mock() replaces the entire module. Return what the component needs. Test behaviour from the user\'s perspective.' }],
        keyPoints: ['Test from the user\'s perspective — query by role/label/text, not by CSS class or implementation details', 'userEvent is more realistic than fireEvent — it simulates real browser events (focus, keyboard, pointer)', 'msw (Mock Service Worker) is the best tool for mocking API calls in tests — intercepts at the network level']
      },
      evaluate: { questions: [{ question: 'Why does RTL prefer screen.getByRole over getByClassName?', options: ['getByClassName is slower', 'getByRole tests from the user\'s perspective — resilient to CSS changes', 'getByClassName requires setup', 'RTL does not support className queries'], correctIndex: 1, explanation: 'getByRole reflects how users and assistive technology perceive the UI. Tests don\'t break when class names change.' }, { question: 'waitFor() is needed when:', options: ['Testing synchronous state', 'Asserting on content that appears after an async operation', 'Every test', 'Only with useEffect'], correctIndex: 1, explanation: 'waitFor() retries the assertion until it passes or times out — needed when content appears after API calls or state updates.' }, { question: 'What is the testing pyramid recommendation for a React app?', options: ['Mostly E2E, some unit, no integration', 'Mostly unit, some integration/component, few E2E', 'Equal amounts of all three', 'Only E2E tests'], correctIndex: 1, explanation: 'Unit tests are fast and cheap. E2E tests are slow and expensive. Pyramid: many unit → some component/integration → few E2E.' }] }
    },
    'Deployment & CI/CD': {
      understand: {
        theory: `# Deployment & CI/CD for React Apps\nModern React apps deploy to CDN-backed platforms (Vercel, Netlify, Cloudflare Pages). CI/CD pipelines run tests and deploy automatically on push.\n\n**Vite production build:**\n\`\`\`bash\nnpm run build    # outputs dist/\nnpx serve dist   # preview locally\n\`\`\`\n\n**GitHub Actions CI/CD pipeline (.github/workflows/deploy.yml):**\n\`\`\`yaml\nname: Deploy\non:\n  push:\n    branches: [main]\n\njobs:\n  test-and-deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: 20 }\n      - run: npm ci\n      - run: npm test -- --watchAll=false\n      - run: npm run build\n      - uses: amondnet/vercel-action@v25\n        with:\n          vercel-token: \${{ secrets.VERCEL_TOKEN }}\n          vercel-org-id: \${{ secrets.ORG_ID }}\n          vercel-project-id: \${{ secrets.PROJECT_ID }}\n          vercel-args: "--prod"\n\`\`\``,
        examples: [{ title: 'Environment variable handling', language: 'typescript', code: `// vite.config.ts — expose only VITE_ prefixed vars\nexport default defineConfig({\n  define: { "import.meta.env.APP_VERSION": JSON.stringify(process.env.npm_package_version) },\n});\n\n// In component\nconst apiUrl = import.meta.env.VITE_API_URL;  // safe: bundled\n// NEVER: const secret = import.meta.env.SECRET_KEY  // exposed to client!\n\n// .env files\n// .env.local         → local dev only (not committed)\n// .env.production    → production values (committed if public)`, explanation: 'Vite only exposes VITE_ prefixed vars to the client bundle. Secrets should never have the VITE_ prefix.' }],
        keyPoints: ['Never commit .env.local — it contains dev secrets. Add to .gitignore. Set production env vars in the hosting platform dashboard', 'npm ci (not npm install) in CI — uses exact lockfile versions for reproducible builds', 'Preview deployments (Vercel/Netlify) create a unique URL per PR — QA before merging to main']
      },
      evaluate: { questions: [{ question: 'Why use npm ci instead of npm install in CI pipelines?', options: ['npm ci is faster always', 'npm ci installs exact versions from package-lock.json for reproducible builds', 'npm install does not work in CI', 'npm ci skips dev dependencies'], correctIndex: 1, explanation: 'npm ci strictly uses package-lock.json and fails if lock is outdated — guaranteeing reproducible builds across environments.' }, { question: 'In Vite, which env var is safe to include in the client bundle?', options: ['DATABASE_URL', 'JWT_SECRET', 'VITE_API_URL', 'All process.env variables'], correctIndex: 2, explanation: 'Only VITE_ prefixed variables are bundled into the client. Others remain server-only.' }, { question: 'A preview deployment creates:', options: ['A new branch', 'A temporary URL for the PR build — separate from production', 'A database copy', 'A Docker container'], correctIndex: 1, explanation: 'Preview deploys give each PR its own URL for testing. Merging to main triggers the production deployment.' }] }
    },
  },
};
